/**
 * Default content for the Chinese games (HSK 1 level). Answers are compared
 * after foldChinese: pinyin with tone marks, tone numbers or none all match,
 * "v" stands for "ü"; characters match as typed.
 */

/** Vocabulary — chữ Hán | pinyin | nghĩa tiếng Việt (used by Đọc Pinyin and Từ vựng) */
export const CHINESE_WORDS_BANK = [
  '你好 | nǐ hǎo | xin chào',
  '谢谢 | xiè xie | cảm ơn',
  '再见 | zài jiàn | tạm biệt',
  '对不起 | duì bu qǐ | xin lỗi',
  '没关系 | méi guān xi | không sao',
  '我 | wǒ | tôi',
  '你 | nǐ | bạn',
  '他 | tā | anh ấy',
  '她 | tā | cô ấy',
  '我们 | wǒ men | chúng tôi',
  '人 | rén | người',
  '大 | dà | to, lớn',
  '小 | xiǎo | nhỏ',
  '好 | hǎo | tốt',
  '不 | bù | không',
  '是 | shì | là',
  '有 | yǒu | có',
  '吃 | chī | ăn',
  '喝 | hē | uống',
  '看 | kàn | xem, nhìn',
  '听 | tīng | nghe',
  '说 | shuō | nói',
  '去 | qù | đi',
  '来 | lái | đến',
  '爱 | ài | yêu',
  '水 | shuǐ | nước',
  '茶 | chá | trà',
  '米饭 | mǐ fàn | cơm',
  '猫 | māo | con mèo',
  '狗 | gǒu | con chó',
  '鱼 | yú | con cá',
  '家 | jiā | nhà',
  '学校 | xué xiào | trường học',
  '老师 | lǎo shī | giáo viên',
  '学生 | xué sheng | học sinh',
  '朋友 | péng you | bạn bè',
  '中国 | Zhōng guó | Trung Quốc',
  '越南 | Yuè nán | Việt Nam',
  '今天 | jīn tiān | hôm nay',
  '明天 | míng tiān | ngày mai',
  '昨天 | zuó tiān | hôm qua',
  '一 | yī | số một',
  '二 | èr | số hai',
  '三 | sān | số ba',
  '四 | sì | số bốn',
  '五 | wǔ | số năm',
  '六 | liù | số sáu',
  '七 | qī | số bảy',
  '八 | bā | số tám',
  '九 | jiǔ | số chín',
  '十 | shí | số mười',
  '爸爸 | bà ba | bố',
  '妈妈 | mā ma | mẹ',
  '书 | shū | sách',
  '车 | chē | xe',
  '天气 | tiān qì | thời tiết',
  '热 | rè | nóng',
  '冷 | lěng | lạnh',
  '高兴 | gāo xìng | vui vẻ',
  '喜欢 | xǐ huan | thích',
  '电脑 | diàn nǎo | máy tính',
  '手机 | shǒu jī | điện thoại',
  '苹果 | píng guǒ | quả táo',
  '医生 | yī shēng | bác sĩ'
].join('\n');

/** Chinese quiz (Vietnamese prompts) — Question | A | B | C | D | correct letter */
export const CHINESE_QUIZ_BANK = [
  '「你好」 nghĩa là gì? | Cảm ơn | Xin chào | Xin lỗi | Tạm biệt | B',
  '「谢谢」 nghĩa là gì? | Không sao | Tạm biệt | Cảm ơn | Xin chào | C',
  '「再见」 nghĩa là gì? | Xin chào | Tạm biệt | Mời ngồi | Cảm ơn | B',
  '「对不起」 nghĩa là gì? | Cảm ơn | Xin lỗi | Chúc mừng | Không sao | B',
  '「猫」 là con gì? | Con cá | Con chó | Con mèo | Con chim | C',
  '「狗」 là con gì? | Con mèo | Con chó | Con ngựa | Con lợn | B',
  '「水」 nghĩa là gì? | Đất | Lửa | Cây | Nước | D',
  '「大」 nghĩa là gì? | Dài | Nhỏ | Ngắn | To, lớn | D',
  '「小」 nghĩa là gì? | Ít | Nhỏ | To | Nhiều | B',
  '「吃」 nghĩa là gì? | Đi | Ngủ | Ăn | Uống | C',
  '「喝」 nghĩa là gì? | Ăn | Xem | Nghe | Uống | D',
  '「老师」 nghĩa là gì? | Giáo viên | Bạn bè | Học sinh | Bác sĩ | A',
  '「朋友」 nghĩa là gì? | Giáo viên | Gia đình | Hàng xóm | Bạn bè | D',
  '「今天」 nghĩa là gì? | Ngày mai | Hôm qua | Năm nay | Hôm nay | D',
  '「明天」 nghĩa là gì? | Tuần sau | Hôm nay | Hôm qua | Ngày mai | D',
  '「中国」 là nước nào? | Hàn Quốc | Trung Quốc | Nhật Bản | Việt Nam | B',
  '「越南」 là nước nào? | Lào | Thái Lan | Trung Quốc | Việt Nam | D',
  '「三」 là số mấy? | 5 | 3 | 4 | 2 | B',
  '「八」 là số mấy? | 7 | 6 | 9 | 8 | D',
  '「十」 là số mấy? | 1 | 10 | 100 | 7 | B',
  '「你好」 đọc là? | xiè xie | duì bu qǐ | zài jiàn | nǐ hǎo | D',
  '「谢谢」 đọc là? | zài jiàn | méi guān xi | nǐ hǎo | xiè xie | D',
  '「人」 đọc là? | kǒu | dà | shuǐ | rén | D',
  '「妈妈」 là ai? | Bố | Bà | Chị | Mẹ | D',
  '「爸爸」 là ai? | Mẹ | Bố | Ông | Anh | B',
  '"Cảm ơn" tiếng Trung là? | 对不起 | 谢谢 | 再见 | 你好 | B',
  '"Con mèo" tiếng Trung là? | 猫 | 鸟 | 鱼 | 狗 | A',
  '"Tôi" tiếng Trung là? | 你 | 她 | 他 | 我 | D',
  '"Nước" tiếng Trung là? | 水 | 木 | 火 | 山 | A',
  '「喜欢」 nghĩa là gì? | Ghét | Biết | Thích | Muốn | C',
  '「热」 nghĩa là gì? | Mát | Lạnh | Ấm | Nóng | D',
  '「冷」 nghĩa là gì? | Ướt | Nóng | Lạnh | Khô | C',
  '「手机」 nghĩa là gì? | Máy tính | Ti vi | Đồng hồ | Điện thoại | D',
  '「电脑」 nghĩa là gì? | Điện thoại | Máy tính | Tủ lạnh | Máy ảnh | B',
  '「米饭」 nghĩa là gì? | Cơm | Bánh bao | Mì | Cháo | A',
  '「学校」 nghĩa là gì? | Nhà hàng | Ngân hàng | Bệnh viện | Trường học | D',
  '「家」 nghĩa là gì? | Chợ | Trường | Công viên | Nhà | D',
  'Tiếng Trung phổ thông có mấy thanh điệu chính? | 4 | 2 | 6 | 8 | A',
  'Phiên âm tiếng Trung bằng chữ Latin gọi là gì? | Pinyin | Romaji | Hangul | Kana | A',
  'Trung Quốc dùng đơn vị tiền nào? | Won | Baht | Yên | Nhân dân tệ | D'
].join('\n');

/** Memory pairs — chữ Hán | nghĩa */
export const HANZI_PAIRS = [
  '猫 | mèo',
  '狗 | chó',
  '鱼 | cá',
  '水 | nước',
  '火 | lửa',
  '山 | núi',
  '人 | người',
  '大 | to',
  '小 | nhỏ',
  '日 | mặt trời',
  '月 | mặt trăng',
  '口 | miệng',
  '木 | cây',
  '书 | sách',
  '车 | xe',
  '家 | nhà',
  '爱 | yêu',
  '吃 | ăn'
].join('\n');
