/**
 * Default content for the English games. Streamers can replace every bank in
 * the app; each line is plain text split on "|" (answers may use "/" aliases).
 */

/** english[/alias] | nghĩa tiếng Việt */
export const VOCAB_BANK = [
  'apple | quả táo',
  'banana | quả chuối',
  'orange | quả cam',
  'teacher | giáo viên',
  'student/pupil | học sinh',
  'school | trường học',
  'family | gia đình',
  'mother/mom/mum | mẹ',
  'father/dad | bố',
  'friend | bạn bè',
  'house/home | ngôi nhà',
  'kitchen | nhà bếp',
  'window | cửa sổ',
  'water | nước',
  'elephant | con voi',
  'tiger | con hổ',
  'monkey | con khỉ',
  'rabbit | con thỏ',
  'butterfly | con bướm',
  'flower | bông hoa',
  'river | dòng sông',
  'mountain | ngọn núi',
  'beach | bãi biển',
  'weather | thời tiết',
  'umbrella | cái ô',
  'computer | máy tính',
  'bicycle/bike | xe đạp',
  'airplane/plane/aeroplane | máy bay',
  'happy | vui vẻ',
  'beautiful | xinh đẹp',
  'delicious | ngon',
  'difficult/hard | khó',
  'library | thư viện',
  'hospital | bệnh viện',
  'breakfast | bữa sáng',
  'birthday | sinh nhật',
  'yesterday | hôm qua',
  'tomorrow | ngày mai',
  'grandmother/grandma | bà',
  'chicken | con gà',
  'grape | quả nho',
  'lemon | quả chanh',
  'mango | quả xoài',
  'pineapple | quả dứa',
  'watermelon | quả dưa hấu',
  'strawberry | quả dâu tây',
  'coconut | quả dừa',
  'papaya | quả đu đủ',
  'peach | quả đào',
  'pear | quả lê',
  'durian | quả sầu riêng',
  'carrot | củ cà rốt',
  'potato | củ khoai tây',
  'tomato | quả cà chua',
  'onion | củ hành tây',
  'garlic | tỏi',
  'cabbage | bắp cải',
  'cucumber | dưa chuột',
  'pumpkin | quả bí ngô',
  'corn | ngô',
  'mushroom | cây nấm',
  'dog | con chó',
  'cat | con mèo',
  'horse | con ngựa',
  'cow | con bò',
  'pig | con lợn',
  'sheep | con cừu',
  'goat | con dê',
  'duck | con vịt',
  'lion | con sư tử',
  'bear | con gấu',
  'zebra | con ngựa vằn',
  'giraffe | con hươu cao cổ',
  'dolphin | con cá heo',
  'shark | con cá mập',
  'whale | con cá voi',
  'snake | con rắn',
  'frog | con ếch',
  'turtle | con rùa',
  'penguin | chim cánh cụt',
  'eagle | chim đại bàng',
  'parrot | con vẹt',
  'owl | con cú',
  'mouse | con chuột',
  'squirrel | con sóc',
  'camel | con lạc đà',
  'kangaroo | con chuột túi',
  'crocodile | con cá sấu',
  'octopus | con bạch tuộc',
  'spider | con nhện',
  'bee | con ong',
  'ant | con kiến',
  'head | cái đầu',
  'hand | bàn tay',
  'finger | ngón tay',
  'shoulder | cái vai',
  'knee | đầu gối',
  'tooth | cái răng',
  'tongue | cái lưỡi',
  'heart | trái tim',
  'brain | bộ não',
  'bedroom | phòng ngủ',
  'bathroom | phòng tắm',
  'garden | khu vườn',
  'door | cửa ra vào',
  'table | cái bàn',
  'chair | cái ghế',
  'pillow | cái gối',
  'blanket | cái chăn',
  'mirror | cái gương',
  'clock | đồng hồ',
  'television/tv | ti vi',
  'refrigerator/fridge | tủ lạnh',
  'lamp | cái đèn',
  'spoon | cái thìa',
  'fork | cái nĩa',
  'knife | con dao',
  'bowl | cái bát',
  'plate | cái đĩa',
  'bottle | cái chai',
  'cup | cái cốc',
  'pencil | bút chì',
  'eraser/rubber | cục tẩy',
  'ruler | thước kẻ',
  'notebook | quyển vở',
  'dictionary | từ điển',
  'classroom | lớp học',
  'homework | bài tập về nhà',
  'lesson | bài học',
  'exam | kỳ thi',
  'science | môn khoa học',
  'history | môn lịch sử',
  'geography | môn địa lý',
  'music | âm nhạc',
  'doctor | bác sĩ',
  'nurse | y tá',
  'farmer | nông dân',
  'engineer | kỹ sư',
  'pilot | phi công',
  'singer | ca sĩ',
  'dancer | vũ công',
  'chef/cook | đầu bếp',
  'driver | tài xế',
  'lawyer | luật sư',
  'artist | họa sĩ',
  'soldier | người lính',
  'firefighter/fireman | lính cứu hỏa',
  'dentist | nha sĩ',
  'market | cái chợ',
  'supermarket | siêu thị',
  'restaurant | nhà hàng',
  'bank | ngân hàng',
  'airport | sân bay',
  'station | nhà ga',
  'museum | bảo tàng',
  'cinema | rạp chiếu phim',
  'park | công viên',
  'zoo | sở thú',
  'bridge | cây cầu',
  'village | ngôi làng',
  'city | thành phố',
  'country | đất nước',
  'island | hòn đảo',
  'forest | khu rừng',
  'desert | sa mạc',
  'ocean | đại dương',
  'lake | cái hồ',
  'storm | cơn bão',
  'snow | tuyết',
  'rainbow | cầu vồng',
  'thunder | tiếng sấm',
  'moon | mặt trăng',
  'star | ngôi sao',
  'sky | bầu trời',
  'tree | cái cây',
  'grass | bãi cỏ',
  'leaf | chiếc lá',
  'car | xe ô tô',
  'bus | xe buýt',
  'train | tàu hỏa',
  'boat | con thuyền',
  'ship | tàu thủy',
  'motorbike/motorcycle | xe máy',
  'helicopter | trực thăng',
  'truck | xe tải',
  'strong | khỏe mạnh',
  'weak | yếu ớt',
  'rich | giàu có',
  'poor | nghèo',
  'clean | sạch sẽ',
  'dirty | bẩn',
  'easy | dễ',
  'angry | tức giận',
  'tired | mệt mỏi',
  'hungry | đói bụng',
  'thirsty | khát nước',
  'sad | buồn',
  'funny | buồn cười',
  'brave | dũng cảm',
  'kind | tốt bụng',
  'lazy | lười biếng',
  'quiet | yên tĩnh',
  'noisy | ồn ào',
  'expensive | đắt tiền',
  'cheap | rẻ',
  'swim | bơi',
  'sing | hát',
  'dance | nhảy múa',
  'read | đọc',
  'write | viết',
  'listen | lắng nghe',
  'speak | nói',
  'sleep | ngủ',
  'drink | uống',
  'walk | đi bộ',
  'jump | nhảy lên',
  'climb | leo trèo',
  'draw | vẽ',
  'study | học bài',
  'open | mở',
  'close | đóng',
  'buy | mua',
  'sell | bán',
  'help | giúp đỡ',
  'laugh | cười lớn',
  'cry | khóc',
  'travel | đi du lịch',
  'remember | ghi nhớ',
  'forget | quên',
  'morning | buổi sáng',
  'afternoon | buổi chiều',
  'evening | buổi tối',
  'night | ban đêm',
  'today | hôm nay',
  'week | tuần',
  'month | tháng',
  'year | năm',
  'spring | mùa xuân',
  'summer | mùa hè',
  'autumn/fall | mùa thu',
  'winter | mùa đông',
  'brother | anh em trai',
  'sister | chị em gái',
  'uncle | chú / bác',
  'aunt | cô / dì',
  'cousin | anh chị em họ',
  'grandfather/grandpa | ông',
  'son | con trai',
  'daughter | con gái',
  'baby | em bé',
  'rice | cơm / gạo',
  'bread | bánh mì',
  'noodles/noodle | mì sợi',
  'soup | món súp',
  'egg | quả trứng',
  'milk | sữa',
  'coffee | cà phê',
  'tea | trà',
  'juice | nước ép',
  'sugar | đường',
  'salt | muối',
  'cake | bánh ngọt',
  'candy/sweets | kẹo',
  'cheese | pho mát',
  'meat | thịt',
  'fish | con cá',
  'lunch | bữa trưa',
  'dinner | bữa tối'
].join('\n');

/** emoji | answer[/alias] | gợi ý tiếng Việt */
export const EMOJI_BANK = [
  '🧈🪰 | butterfly | con bướm',
  '🌧️🎀 | rainbow | cầu vồng',
  '🦶⚽ | football | bóng đá',
  '🥚🌱 | eggplant | cà tím',
  '🧊🍦 | ice cream | kem',
  '🔥🪰 | firefly | đom đóm',
  '🍵🍲 | teapot | ấm trà',
  '☀️🌻 | sunflower | hoa hướng dương',
  '❄️⛄ | snowman | người tuyết',
  '⭐🐟 | starfish | sao biển',
  '🏠👷 | homework | bài tập về nhà',
  '📚🐛 | bookworm | mọt sách',
  '🐴👞 | horseshoe | móng ngựa',
  '🍎🥧 | apple pie | bánh táo',
  '🎂🎉 | birthday party | tiệc sinh nhật',
  '⭐🎬 | movie star/film star | ngôi sao điện ảnh',
  '☀️👓 | sunglasses | kính râm',
  '🌊🏄 | surfing | lướt sóng',
  '🐝🏠 | beehive | tổ ong',
  '🔥🚒 | fire truck/fire engine | xe cứu hỏa',
  '☀️⬆️ | sunrise | bình minh',
  '☀️⬇️ | sunset | hoàng hôn',
  '🌧️🧥 | raincoat | áo mưa',
  '🐱🐟 | catfish | cá trê',
  '💥🌽 | popcorn | bỏng ngô',
  '🌍🔥 | global warming | trái đất nóng lên',
  '👨‍🚀🚀 | astronaut | phi hành gia',
  '🌊🐢 | sea turtle | rùa biển',
  '👂🎧 | headphones/earphones | tai nghe',
  '⏰🛏️ | alarm clock | đồng hồ báo thức',
  '🧊🐻 | polar bear | gấu Bắc Cực',
  '🍓🍰 | strawberry cake | bánh dâu',
  '🍫🍪 | chocolate cookie/cookie | bánh quy sô cô la',
  '🏫🚌 | school bus | xe buýt trường học',
  '🌴🏝️ | island | hòn đảo',
  '🎄🎅 | christmas | Giáng sinh',
  '🎃👻 | halloween | lễ hội hóa trang',
  '🧧🐉 | lunar new year/tet | Tết Nguyên đán',
  '🏀⛹️ | basketball | bóng rổ',
  '🧑‍🍳🍲 | chef/cook | đầu bếp',
  '👨‍⚕️🏥 | doctor | bác sĩ',
  '🐶🏠 | doghouse/kennel | chuồng chó',
  '🐄🥛 | milk | sữa',
  '🐝🍯 | honey | mật ong',
  '🌧️☂️ | umbrella | cái ô',
  '🔥⛰️ | volcano | núi lửa',
  '🦷🪥 | toothbrush | bàn chải đánh răng',
  '🌙🍰 | mooncake/moon cake | bánh trung thu',
  '🕷️👨 | spiderman/spider man | người nhện',
  '🦇👨 | batman | người dơi',
  '🏔️⛷️ | skiing | trượt tuyết',
  '🎤🎶 | singer | ca sĩ',
  '🌙⭐ | night | ban đêm',
  '🍉🔪 | watermelon | dưa hấu',
  '🐟🎣 | fishing | câu cá',
  '📚🏛️ | library | thư viện',
  '✈️🛫 | airport | sân bay',
  '🎂🕯️ | birthday cake | bánh sinh nhật',
  '🐻🧸 | teddy bear | gấu bông',
  '🍔🍟 | fast food | đồ ăn nhanh',
  '🥤🧋 | bubble tea/milk tea | trà sữa',
  '🍜🥢 | noodles/noodle | mì sợi',
  '🎁🎄 | christmas present/christmas gift | quà Giáng sinh',
  '🎓📜 | graduation | lễ tốt nghiệp',
  '💍👰 | wedding | đám cưới',
  '🏥🚑 | ambulance | xe cứu thương',
  '👮🚓 | police car | xe cảnh sát',
  '🚀🌌 | spaceship/rocket | tàu vũ trụ',
  '🌳🏠 | treehouse/tree house | nhà trên cây',
  '📸🤳 | selfie | ảnh tự chụp',
  '🎮🕹️ | video game/game | trò chơi điện tử',
  '📺📰 | news | tin tức',
  '🌍🗺️ | world map/map | bản đồ thế giới',
  '🏝️🌞 | summer holiday/summer vacation/holiday/vacation | kỳ nghỉ hè',
  '🎒📚 | schoolbag/school bag | cặp sách',
  '🦁👑 | lion king | vua sư tử',
  '🐼🎋 | panda | gấu trúc',
  '🧜‍♀️🌊 | mermaid | nàng tiên cá',
  '🧚‍♀️✨ | fairy | nàng tiên',
  '👸🏰 | princess | công chúa',
  '🤴🏰 | prince | hoàng tử',
  '🧙‍♂️🪄 | wizard/magician | phù thủy',
  '👻🏠 | haunted house | nhà ma',
  '🧛🦇 | vampire | ma cà rồng',
  '🐸👑 | frog prince | hoàng tử ếch',
  '🌪️🌀 | tornado | lốc xoáy',
  '⚡🌩️ | thunderstorm/storm | giông bão',
  '🌈🦄 | unicorn | kỳ lân',
  '🐉🔥 | dragon | con rồng',
  '🦖🦕 | dinosaur | khủng long',
  '🐒🍌 | monkey | con khỉ',
  '🐔🥚 | egg | quả trứng',
  '🥛🍪 | milk and cookies | sữa và bánh quy',
  '🍞🧈 | bread and butter | bánh mì bơ',
  '🔥🐶 | hot dog | xúc xích kẹp bánh mì',
  '🐭🧀 | cheese | pho mát',
  '🐟🍚 | sushi | món Nhật',
  '🥶🧊 | cold/freezing | lạnh cóng',
  '🥵☀️ | hot | nóng',
  '😴🛏️ | sleepy/sleep | buồn ngủ',
  '😭💧 | cry/tears | khóc',
  '❤️💌 | love letter | thư tình',
  '💔😢 | broken heart/heartbreak | tan vỡ',
  '🎵👂 | music | âm nhạc',
  '📖👀 | reading/read | đọc sách',
  '✍️📄 | writing/write | viết',
  '🏃💨 | running/run | chạy',
  '🏊🌊 | swimming/swim | bơi lội',
  '🚴🛣️ | cycling/bike | đạp xe',
  '🧘🕉️ | yoga | yoga',
  '⚽🥅 | goal | bàn thắng',
  '🏆🥇 | champion/winner | nhà vô địch',
  '🎬🍿 | movie/cinema/film | xem phim',
  '🎹🎼 | piano | đàn piano',
  '🎸🤘 | rock music/rock | nhạc rock',
  '🥁🎶 | drums/drum | cái trống',
  '💻🐭 | computer mouse/mouse | chuột máy tính',
  '📱🔋 | battery/phone battery | pin điện thoại',
  '🔑🚪 | key | chìa khóa',
  '🕰️⏳ | time | thời gian',
  '🏔️🧗 | climbing/mountain climbing | leo núi',
  '🐄🌾 | farm | nông trại',
  '🏭💨 | pollution | ô nhiễm',
  '♻️🗑️ | recycling/recycle | tái chế',
  '🍂🍁 | autumn/fall | mùa thu',
  '🌸🌷 | spring | mùa xuân',
  '☀️🏖️ | summer | mùa hè',
  '❄️🧣 | winter | mùa đông',
  '🌙😴 | good night/goodnight | chúc ngủ ngon',
  '☀️👋 | good morning | chào buổi sáng',
  '🙏💝 | thank you/thanks | cảm ơn',
  '🍬🦷 | toothache | đau răng',
  '🤒🌡️ | fever/sick | bị sốt',
  '💊🩺 | medicine | thuốc',
  '👓👀 | glasses/eyeglasses | kính mắt',
  '👟🏃 | sneakers/running shoes | giày thể thao',
  '👕👖 | clothes | quần áo',
  '🧤❄️ | gloves | găng tay',
  '🎩🐰 | magic/magician | ảo thuật',
  '🐝🌼 | bee | con ong',
  '🐜🍰 | ant | con kiến',
  '🐌🏠 | snail | ốc sên',
  '🐧❄️ | penguin | chim cánh cụt',
  '🐫🏜️ | camel | lạc đà',
  '🦒🌳 | giraffe | hươu cao cổ',
  '🐊🌊 | crocodile | cá sấu',
  '🦉🌙 | owl | con cú',
  '🐺🌕 | wolf | chó sói'
].join('\n');

/** sentence | nghĩa tiếng Việt */
export const SENTENCE_BANK = [
  'I go to school every day | Tôi đi học mỗi ngày',
  'She likes to read books | Cô ấy thích đọc sách',
  'They are playing football in the park | Họ đang chơi bóng đá trong công viên',
  'We had dinner at seven o\'clock | Chúng tôi ăn tối lúc bảy giờ',
  'My brother is taller than me | Anh trai tôi cao hơn tôi',
  'Can you help me with my homework | Bạn giúp tôi làm bài tập được không',
  'What time does the movie start | Mấy giờ bộ phim bắt đầu',
  'He has lived here for five years | Anh ấy đã sống ở đây năm năm',
  'It is raining outside now | Bây giờ bên ngoài đang mưa',
  'I have never been to London | Tôi chưa bao giờ đến London',
  'Where did you buy that bag | Bạn đã mua cái túi đó ở đâu',
  'The cat is sleeping under the table | Con mèo đang ngủ dưới gầm bàn',
  'Please turn off the lights | Làm ơn tắt đèn',
  'She is good at playing the piano | Cô ấy chơi piano giỏi',
  'How many languages can you speak | Bạn nói được bao nhiêu ngôn ngữ',
  'I like to eat noodles for breakfast | Tôi thích ăn mì vào bữa sáng',
  'My mother is cooking in the kitchen | Mẹ tôi đang nấu ăn trong bếp',
  'We will go to the beach this summer | Mùa hè này chúng tôi sẽ đi biển',
  'The dog is running in the garden | Con chó đang chạy trong vườn',
  'He drinks a cup of coffee every morning | Anh ấy uống một cốc cà phê mỗi sáng',
  'Can I borrow your pen | Tôi mượn bút của bạn được không',
  'It is very hot today | Hôm nay trời rất nóng',
  'I usually get up at six o\'clock | Tôi thường dậy lúc sáu giờ',
  'She is wearing a red dress | Cô ấy đang mặc một chiếc váy đỏ',
  'They live in a small village | Họ sống ở một ngôi làng nhỏ',
  'Do you like watching movies | Bạn có thích xem phim không',
  'My father works in a hospital | Bố tôi làm việc ở bệnh viện',
  'There are thirty students in my class | Lớp tôi có ba mươi học sinh',
  'I am learning English every day | Tôi học tiếng Anh mỗi ngày',
  'Let\'s play badminton after school | Chơi cầu lông sau giờ học nhé',
  'The book is on the table | Quyển sách ở trên bàn',
  'What is your favorite color | Màu yêu thích của bạn là gì',
  'I want to be a doctor in the future | Tôi muốn trở thành bác sĩ trong tương lai',
  'We visited our grandparents last Sunday | Chủ nhật tuần trước chúng tôi thăm ông bà',
  'The train leaves at ten o\'clock | Tàu rời đi lúc mười giờ',
  'Please speak more slowly | Làm ơn nói chậm hơn',
  'How much does this shirt cost | Chiếc áo này giá bao nhiêu',
  'I don\'t understand this question | Tôi không hiểu câu hỏi này',
  'She can swim very well | Cô ấy bơi rất giỏi',
  'It takes two hours to get there | Mất hai tiếng để đến đó',
  'My sister is two years older than me | Chị gái tôi hơn tôi hai tuổi',
  'We should protect the environment | Chúng ta nên bảo vệ môi trường',
  'He forgot to bring his umbrella | Anh ấy quên mang ô',
  'The children are singing a song | Bọn trẻ đang hát một bài hát',
  'I will call you tomorrow morning | Tôi sẽ gọi cho bạn vào sáng mai',
  'Where is the nearest bus stop | Trạm xe buýt gần nhất ở đâu',
  'Reading books makes me happy | Đọc sách làm tôi vui',
  'Tet is the most important holiday in Vietnam | Tết là ngày lễ quan trọng nhất ở Việt Nam',
  'My favorite subject is math | Môn học yêu thích của tôi là toán',
  'Don\'t forget to do your homework | Đừng quên làm bài tập về nhà',
  'I am going to visit Da Nang next month | Tháng sau tôi sẽ đi Đà Nẵng',
  'The weather is nice for a picnic | Thời tiết đẹp để đi dã ngoại',
  'He usually rides his bike to work | Anh ấy thường đạp xe đi làm',
  'Thank you for watching my live stream | Cảm ơn bạn đã xem livestream của tôi',
  'Please follow me and share this video | Hãy theo dõi tôi và chia sẻ video này',
  'We are having a lot of fun | Chúng tôi đang rất vui',
  'Could you open the window please | Bạn mở cửa sổ giúp tôi được không',
  'My phone is running out of battery | Điện thoại của tôi sắp hết pin',
  'The movie was really interesting | Bộ phim thật sự thú vị',
  'I have two cats and a dog | Tôi có hai con mèo và một con chó',
  'I brush my teeth every morning | Tôi đánh răng mỗi sáng',
  'She walks to school with her friends | Cô ấy đi bộ đến trường cùng bạn bè',
  'We are watching a football match | Chúng tôi đang xem một trận bóng đá',
  'My brother plays the guitar very well | Anh trai tôi chơi guitar rất giỏi',
  'Please close the door behind you | Làm ơn đóng cửa sau khi vào',
  'The sun is shining brightly today | Hôm nay mặt trời chiếu sáng rực rỡ',
  'I would like a glass of orange juice | Tôi muốn một cốc nước cam',
  'They are building a new bridge | Họ đang xây một cây cầu mới',
  'Our teacher is very kind and funny | Cô giáo của chúng tôi rất tốt bụng và vui tính',
  'He cannot find his keys anywhere | Anh ấy không tìm thấy chìa khóa ở đâu cả',
  'We go shopping every Saturday | Chúng tôi đi mua sắm mỗi thứ Bảy',
  'The baby is sleeping in the bedroom | Em bé đang ngủ trong phòng ngủ',
  'I have a lot of homework tonight | Tối nay tôi có rất nhiều bài tập',
  'She wants to travel around the world | Cô ấy muốn đi du lịch vòng quanh thế giới',
  'My grandmother tells me stories every night | Bà kể chuyện cho tôi mỗi tối',
  'The shop opens at eight in the morning | Cửa hàng mở cửa lúc tám giờ sáng',
  'Do you want to play a game | Bạn có muốn chơi một trò chơi không',
  'It is too cold to go outside | Trời quá lạnh để ra ngoài',
  'I learn new words every day | Tôi học từ mới mỗi ngày',
  'He is the tallest boy in our class | Cậu ấy là bạn nam cao nhất lớp tôi',
  'We planted some trees in the garden | Chúng tôi đã trồng vài cây trong vườn',
  'The birds are singing in the trees | Những chú chim đang hót trên cây',
  'Can you tell me the way to the station | Bạn chỉ đường giúp tôi đến nhà ga được không',
  'My mother bought a new dress for me | Mẹ tôi mua cho tôi một chiếc váy mới',
  'The concert starts at seven thirty | Buổi hòa nhạc bắt đầu lúc bảy giờ ba mươi',
  'I am very happy to see you again | Tôi rất vui được gặp lại bạn',
  'Water boils at one hundred degrees | Nước sôi ở một trăm độ',
  'She has lived in Hanoi since she was a child | Cô ấy sống ở Hà Nội từ khi còn nhỏ',
  'We should drink more water every day | Chúng ta nên uống nhiều nước hơn mỗi ngày',
  'They won the game last night | Họ đã thắng trận đấu tối qua',
  'The flowers smell really nice | Những bông hoa thơm thật',
  'I usually take a bus to school | Tôi thường đi xe buýt đến trường',
  'He always helps his friends | Anh ấy luôn giúp đỡ bạn bè',
  'My dog likes to chase the ball | Con chó của tôi thích đuổi theo quả bóng',
  'Let\'s meet at the park after lunch | Gặp nhau ở công viên sau bữa trưa nhé',
  'The museum is closed on Mondays | Bảo tàng đóng cửa vào thứ Hai',
  'I forgot my umbrella at home | Tôi để quên ô ở nhà',
  'She is making a cake for her mother | Cô ấy đang làm bánh cho mẹ',
  'We had a great time at the beach | Chúng tôi đã có khoảng thời gian tuyệt vời ở bãi biển',
  'Turn left at the traffic lights | Rẽ trái ở chỗ đèn giao thông',
  'He speaks three languages fluently | Anh ấy nói trôi chảy ba thứ tiếng',
  'The students are listening to the teacher | Học sinh đang nghe cô giáo giảng',
  'My favorite food is fried rice | Món ăn yêu thích của tôi là cơm chiên',
  'It snows a lot in winter in Canada | Ở Canada mùa đông tuyết rơi nhiều',
  'I will finish my homework before dinner | Tôi sẽ làm xong bài tập trước bữa tối',
  'The cat jumped onto the sofa | Con mèo nhảy lên ghế sofa',
  'She is afraid of the dark | Cô ấy sợ bóng tối',
  'Please wash your hands before eating | Hãy rửa tay trước khi ăn',
  'We are going to have a party tonight | Tối nay chúng tôi sẽ tổ chức tiệc',
  'The library has many interesting books | Thư viện có nhiều sách hay',
  'He fell asleep while watching TV | Anh ấy ngủ quên khi đang xem TV',
  'I need to buy some milk and eggs | Tôi cần mua sữa và trứng',
  'Our team practices every afternoon | Đội chúng tôi luyện tập mỗi chiều',
  'The weather will be sunny tomorrow | Ngày mai trời sẽ nắng',
  'My father drives me to school | Bố tôi chở tôi đến trường',
  'She sings beautifully at every party | Cô ấy hát rất hay ở mọi bữa tiệc',
  'Do not run in the classroom | Không được chạy trong lớp học',
  'They are waiting for the train | Họ đang đợi tàu',
  'I have never seen snow before | Tôi chưa bao giờ nhìn thấy tuyết',
  'Could you help me carry this bag | Bạn giúp tôi xách cái túi này được không',
  'The children are playing hide and seek | Bọn trẻ đang chơi trốn tìm',
  'He is reading a comic book | Cậu ấy đang đọc truyện tranh',
  'We live on the fifth floor | Chúng tôi sống ở tầng năm',
  'My phone is on the kitchen table | Điện thoại của tôi ở trên bàn bếp',
  'She drinks green tea every afternoon | Cô ấy uống trà xanh mỗi chiều',
  'I am saving money to buy a bike | Tôi đang tiết kiệm tiền để mua xe đạp',
  'The river is very wide and deep | Con sông rất rộng và sâu',
  'Our school has a big playground | Trường chúng tôi có một sân chơi lớn',
  'He was late because of the rain | Anh ấy đến muộn vì trời mưa',
  'I like spring more than winter | Tôi thích mùa xuân hơn mùa đông',
  'The moon is bright tonight | Tối nay trăng sáng',
  'She always wears a red hat | Cô ấy luôn đội một chiếc mũ đỏ',
  'Let\'s take a photo together | Cùng chụp một tấm ảnh nhé',
  'Everyone in my family loves music | Mọi người trong gia đình tôi đều yêu âm nhạc',
  'I get up early on school days | Tôi dậy sớm vào những ngày đi học',
  'The bakery sells fresh bread every morning | Tiệm bánh bán bánh mì mới mỗi sáng',
  'He is going to be a famous singer | Anh ấy sẽ trở thành một ca sĩ nổi tiếng',
  'Comment the answer as fast as you can | Hãy comment đáp án nhanh nhất có thể',
  'Who will win this round | Ai sẽ thắng vòng này',
  'Thank you for the lovely gifts | Cảm ơn vì những món quà dễ thương'
].join('\n');

/** Category | answer[/alias] | answer | … (2–12 answers) */
export const CATEGORY_BANK = [
  'Fruits 🍎 | apple | banana | orange | mango | grape | watermelon | pineapple | strawberry | lemon | peach',
  'Farm animals 🐄 | cow | pig | chicken/hen/rooster | horse | sheep | goat | duck | dog | cat | rabbit',
  'Colors 🎨 | red | blue | green | yellow | black | white | pink | purple | orange | brown',
  'Jobs 👩‍⚕️ | teacher | doctor | nurse | farmer | engineer | police officer/policeman/policewoman | chef/cook | driver | singer | pilot',
  'Body parts 🧍 | head | hand | eye | nose | mouth | ear | leg | arm | foot/feet | hair',
  'Days of the week 📅 | monday | tuesday | wednesday | thursday | friday | saturday | sunday',
  'In the classroom 🏫 | desk | chair | board/whiteboard/blackboard | book | pen | pencil | ruler | eraser/rubber | schoolbag/bag | clock',
  'Weather ☀️ | sunny | rainy | cloudy | windy | snowy | stormy | foggy | hot | cold | warm',
  'Sports ⚽ | football/soccer | basketball | volleyball | tennis | badminton | swimming | running | baseball | golf | boxing',
  'Vegetables 🥕 | carrot | potato | tomato | onion | cabbage | cucumber | corn | pumpkin | garlic | lettuce | pea/peas | bean/beans',
  'Wild animals 🦁 | lion | tiger | elephant | giraffe | zebra | monkey | bear | wolf | fox | kangaroo | deer | leopard',
  'Sea animals 🐠 | fish | shark | whale | dolphin | octopus | crab | jellyfish | starfish | seahorse | turtle | squid | shrimp',
  'Birds 🐦 | parrot | eagle | owl | penguin | duck | chicken/hen | pigeon | swan | sparrow | crow | peacock | ostrich',
  'Insects 🐞 | ant | bee | butterfly | mosquito | fly | ladybug/ladybird | dragonfly | cockroach | grasshopper | beetle | cricket | moth',
  'Drinks 🥤 | water | milk | juice | tea | coffee | cola/coke | lemonade | smoothie | milk tea/bubble tea | soda | hot chocolate/cocoa | yogurt',
  'Food 🍔 | rice | bread | noodles/noodle | pizza | hamburger/burger | sandwich | soup | cake | egg/eggs | chicken | cheese | salad',
  'Clothes 👕 | shirt | dress | skirt | jeans | trousers/pants | jacket | coat | sweater | shorts | hat | socks | scarf',
  'Kitchen things 🍳 | spoon | fork | knife | plate | bowl | cup | pan | pot | kettle | fridge/refrigerator | stove | chopsticks',
  'Furniture 🛋️ | bed | chair | table | sofa | desk | wardrobe | shelf | bookcase/bookshelf | lamp | mirror | cupboard | armchair',
  'Transport 🚗 | car | bus | train | plane/airplane | boat | ship | bicycle/bike | motorbike/motorcycle | taxi | truck | helicopter | subway/metro',
  'School subjects 📚 | math/maths | english | science | history | geography | music | art | physics | chemistry | biology | literature | informatics/computer science',
  'Family 👨‍👩‍👧 | mother/mom/mum | father/dad | brother | sister | grandmother/grandma | grandfather/grandpa | uncle | aunt | cousin | son | daughter | baby',
  'Musical instruments 🎸 | piano | guitar | violin | drum/drums | flute | trumpet | saxophone | harp | cello | ukulele | keyboard | xylophone',
  'Places in town 🏙️ | school | hospital | bank | market | supermarket | park | library | museum | cinema | restaurant | post office | police station',
  'Countries 🌏 | vietnam | japan | china | korea | thailand | france | england | america/usa | australia | canada | india | brazil',
  'Nature 🌳 | tree | flower | river | mountain | lake | sea | forest | beach | island | sky | grass | cloud',
  'Shapes 🔺 | circle | square | triangle | rectangle | star | heart | oval | diamond | pentagon | hexagon | cross | arrow',
  'Feelings 😊 | happy | sad | angry | tired | scared/afraid | excited | bored | surprised | nervous | proud | shy | worried',
  'Toys 🧸 | doll | ball | teddy bear | kite | robot | puzzle | yoyo | toy car | blocks/lego | balloon | toy train | skateboard',
  'In the bedroom 🛏️ | bed | pillow | blanket | lamp | wardrobe | clock | mirror | curtain/curtains | desk | carpet/rug | poster | closet',
  'Months 📅 | january | february | march | april | may | june | july | august | september | october | november | december',
  'Numbers 🔢 | one | two | three | four | five | six | seven | eight | nine | ten | eleven | twelve',
  'Actions 🏃 | run | jump | swim | walk | dance | sing | read | write | eat | drink | sleep | cook',
  'Technology 💻 | computer | laptop | phone/smartphone | tablet | keyboard | mouse | printer | camera | television/tv | headphones | speaker | charger',
  'Tropical fruits 🥭 | mango | papaya | pineapple | coconut | durian | banana | guava | lychee | longan | rambutan | dragon fruit | jackfruit',
  'Hobbies 🎨 | reading | drawing | painting | singing | dancing | swimming | cooking | gaming | fishing | hiking | camping | photography',
  'Planets 🪐 | mercury | venus | earth | mars | jupiter | saturn | uranus | neptune',
  'Continents 🌍 | asia | africa | europe | antarctica | australia/oceania | north america | south america',
  'Rooms in a house 🏠 | kitchen | bedroom | bathroom | living room | dining room | garage | garden | attic | basement | hall/hallway | balcony | office',
  'Things in a bag 🎒 | book | pen | pencil | notebook | phone | wallet | key/keys | water bottle/bottle | umbrella | tissues/tissue | charger | snack/snacks'
].join('\n');

/** Question | A | B | C | D | correct letter */
export const ENGLISH_QUIZ_BANK = [
  'She ___ to school every day. | go | goes | going | gone | B',
  'I ___ a student. | am | is | are | be | A',
  'They ___ football yesterday. | play | plays | played | playing | C',
  'Past tense of "buy"? | buyed | bought | brought | buys | B',
  'Which word is a fruit? | carrot | potato | mango | onion | C',
  'Opposite of "hot"? | warm | cold | big | fast | B',
  '"Con mèo" in English? | dog | cat | mouse | bird | B',
  'He is ___ than his brother. | tall | taller | tallest | more tall | B',
  'I have lived here ___ 2020. | for | since | from | at | B',
  'There ___ many books on the table. | is | are | am | be | B',
  'What ___ you do last weekend? | do | does | did | done | C',
  'Plural of "child"? | childs | childes | children | childrens | C',
  'We are going ___ the cinema tonight. | to | at | in | on | A',
  'Best reply to "Thank you"? | Yes, please | You\'re welcome | Sorry | Goodbye | B',
  'Which sentence is correct? | She don\'t like milk | She doesn\'t like milk | She not like milk | She isn\'t like milk | B',
  'My birthday is ___ May. | on | at | in | by | C',
  'If it rains, I ___ at home. | stay | will stay | stayed | staying | B',
  'Synonym of "big"? | small | large | short | thin | B',
  'How ___ apples do you want? | much | many | long | often | B',
  'The sun ___ in the east. | rise | rises | rising | rose | B',
  'Past tense of "go"? | went | goed | going | gone | A',
  'Past tense of "eat"? | ate | eated | eaten | eating | A',
  'Past participle of "write"? | writed | written | wrote | writing | B',
  'Plural of "mouse"? | mouses | mices | mice | mouse | C',
  'Plural of "tooth"? | teeth | teeths | toothes | tooths | A',
  'Plural of "woman"? | womans | womanes | womens | women | D',
  'Opposite of "happy"? | sad | glad | funny | kind | A',
  'Opposite of "young"? | old | new | short | small | A',
  'Opposite of "early"? | late | fast | before | soon | A',
  'Opposite of "cheap"? | expensive | easy | poor | cheerful | A',
  'Synonym of "quick"? | slow | fast | late | quiet | B',
  'Synonym of "begin"? | finish | start | stop | end | B',
  '"Quả dưa hấu" in English? | watermelon | pineapple | coconut | papaya | A',
  '"Bác sĩ" in English? | driver | dancer | farmer | doctor | D',
  '"Thư viện" in English? | classroom | bookstore | laboratory | library | D',
  '"Con voi" in English? | tiger | giraffe | elephant | monkey | C',
  'I ___ my homework already. | have done | doing | did have | has done | A',
  'She ___ TV when I called her. | was watching | watches | is watching | watch | A',
  '___ you like some tea? | Do | Would | Are | Will | B',
  'He can ___ very fast. | runs | run | ran | running | B',
  'This is ___ best day of my life. | the | a | an | some | A',
  '___ apple a day keeps the doctor away. | A | An | Some | The | B',
  'She is interested ___ music. | on | of | in | at | C',
  'We have English ___ Monday. | on | in | at | by | A',
  'The meeting starts ___ 9 o\'clock. | on | at | by | in | B',
  'Which word is a verb? | blue | happy | table | swim | D',
  'Which word is an adjective? | beautiful | run | tree | quickly | A',
  'Which word is an adverb? | slower | slow | slowness | slowly | D',
  'Comparative of "good"? | better | best | more good | gooder | A',
  'Superlative of "bad"? | worse | worst | most bad | baddest | B',
  'Best reply to "How are you?" | Nice to meet you | I\'m a student | I\'m fine, thank you | I\'m 10 years old | C',
  'Best reply to "What\'s your name?" | My name is Lan | I\'m fine | It\'s seven o\'clock | I\'m from Hanoi | A',
  'How many days are there in a week? | six | five | seven | eight | C',
  'The first month of the year? | February | January | December | March | B',
  'The day after Monday? | Sunday | Tuesday | Wednesday | Thursday | B',
  '"Twelve" is? | 11 | 2 | 20 | 12 | D',
  '"Thirty" is? | 3 | 33 | 13 | 30 | D',
  'Where do you go to see a doctor? | hospital | cinema | bank | library | A',
  'A person who teaches is a ___. | teaching | taught | teacher | teach | C',
  'If I ___ you, I would study harder. | am | will be | is | were | D',
  'He ___ swim when he was five. | coulds | cans | could | can | C',
  'I\'m looking forward to ___ you. | see | saw | seen | seeing | D',
  'You ___ smoke here. It\'s forbidden. | needn\'t | aren\'t | mustn\'t | don\'t have to | C',
  '"Break a leg" means? | Good luck | Get hurt | Stop now | Run fast | A',
  '"Piece of cake" means? | Very easy | Very sweet | A small gift | Very hungry | A',
  'The capital of England is ___. | Paris | London | Sydney | New York | B',
  'A kitchen is a room for ___. | sleeping | bathing | studying | cooking | D',
  'Choose the correct spelling: | beatiful | butiful | beautiful | beautifull | C',
  'Choose the correct spelling: | because | becuase | beacause | becouse | A',
  'She has two ___. | brothers | brotheres | brothers\' | brother | A',
  'My father ___ coffee every morning. | drinked | drinking | drink | drinks | D',
  'Look! The children ___ in the garden. | played | plays | are playing | play | C',
  'I was born ___ 2010. | by | at | in | on | C',
  'Can you ___ me the salt, please? | to pass | pass | passing | passed | B',
  'We ___ to Da Nang last summer. | went | go | have gone | goes | A',
  'Past tense of "see"? | saw | seen | sawed | seed | A',
  'Past tense of "take"? | tooked | took | taken | taked | B',
  'Past tense of "make"? | made | make | maked | maded | A',
  'Past tense of "run"? | runs | ran | runned | running | B',
  'Past tense of "swim"? | swam | swimmed | swum | swims | A',
  'Past tense of "drink"? | drunk | drank | drinked | drinks | B',
  'Past tense of "come"? | comed | coming | came | comes | C',
  'Past tense of "give"? | given | gived | gives | gave | D',
  'Past tense of "teach"? | teaches | tought | taught | teached | C',
  'Past tense of "catch"? | catches | catched | caught | cought | C',
  'Past tense of "sleep"? | slep | slept | sleeped | sleeps | B',
  'Past tense of "speak"? | spoken | speaked | speaks | spoke | D',
  'Past participle of "go"? | gone | went | goed | going | A',
  'Past participle of "eat"? | eated | eaten | ate | eating | B',
  'Plural of "foot"? | feet | foots | footes | feets | A',
  'Plural of "box"? | boxen | boxes | boxies | boxs | B',
  'Plural of "baby"? | babis | babyes | babys | babies | D',
  'Plural of "leaf"? | leavs | leafs | leaves | leafes | C',
  'Plural of "man"? | men | mens | mans | manes | A',
  'Plural of "sheep"? | sheep | sheepes | shoop | sheeps | A',
  'Plural of "knife"? | knifs | knifes | knives | knive | C',
  'Opposite of "big"? | small | wide | huge | large | A',
  'Opposite of "fast"? | rapid | slow | quick | early | B',
  'Opposite of "strong"? | heavy | tall | weak | hard | C',
  'Opposite of "rich"? | cheap | sad | weak | poor | D',
  'Opposite of "full"? | heavy | empty | busy | tired | B',
  'Opposite of "heavy"? | light | thin | soft | quiet | A',
  'Opposite of "clean"? | new | tidy | dirty | fresh | C',
  'Opposite of "easy"? | soft | simple | difficult | light | C',
  'Opposite of "remember"? | learn | know | forget | recall | C',
  'Opposite of "buy"? | shop | spend | sell | pay | C',
  'Opposite of "arrive"? | come | enter | reach | leave | D',
  'Synonym of "happy"? | glad | angry | bored | sad | A',
  'Synonym of "smart"? | shy | lazy | slow | clever | D',
  'Synonym of "small"? | huge | little | wide | tall | B',
  'Synonym of "beautiful"? | dirty | plain | ugly | pretty | D',
  'Synonym of "finish"? | begin | start | end | open | C',
  'Synonym of "angry"? | glad | kind | calm | mad | D',
  '"Con bướm" in English? | ladybug | butterfly | bee | dragonfly | B',
  '"Máy bay" in English? | helicopter | airplane | ship | train | B',
  '"Bệnh viện" in English? | museum | hospital | school | hotel | B',
  '"Nhà bếp" in English? | garden | kitchen | bathroom | bedroom | B',
  '"Mùa đông" in English? | winter | summer | autumn | spring | A',
  '"Cầu vồng" in English? | cloud | thunder | rainbow | raindrop | C',
  '"Bạn bè" in English? | neighbor | friend | teacher | family | B',
  '"Ngày mai" in English? | tomorrow | today | tonight | yesterday | A',
  '"Con cá mập" in English? | shark | whale | dolphin | octopus | A',
  '"Cái ô" in English? | umbrella | raincoat | hat | bag | A',
  '"Xe đạp" in English? | bicycle | motorbike | bus | car | A',
  '"Thước kẻ" in English? | pencil | eraser | ruler | notebook | C',
  '"Tức giận" in English? | tired | hungry | sleepy | angry | D',
  '"Đói bụng" in English? | thirsty | full | hungry | angry | C',
  '"Nông dân" in English? | fireman | chef | farmer | driver | C',
  '"Library" means? | Phòng thí nghiệm | Lớp học | Thư viện | Hiệu sách | C',
  '"Delicious" means? | Ngon | Đẹp | Đắt | Cay | A',
  '"Brave" means? | Thông minh | Nhút nhát | Dũng cảm | Lười biếng | C',
  '"Thirsty" means? | Buồn ngủ | Đói bụng | Khát nước | Mệt mỏi | C',
  '"Grandmother" means? | Cô | Bà | Chị | Mẹ | B',
  '"Weather" means? | Bầu trời | Thời tiết | Mùa | Nhiệt độ | B',
  'The cat is ___ the table. (ở dưới) | under | at | on | in | A',
  'I live ___ Hanoi. | at | in | to | on | B',
  'She was born ___ May 5th. | in | at | by | on | D',
  'He is good ___ math. | at | in | for | on | A',
  'I\'m afraid ___ spiders. | from | with | of | at | C',
  'Listen ___ the teacher! | for | on | at | to | D',
  'We waited ___ the bus for 20 minutes. | for | on | at | to | A',
  'She ___ English for three years. | study | has studied | studies | is studying | B',
  'Look! It ___. | rains | rain | rained | is raining | D',
  'I ___ to the cinema tomorrow evening. | went | have gone | go | am going | D',
  'They ___ dinner when the phone rang. | has had | are having | were having | have | C',
  'He ___ never been to Japan. | has | is | have | was | A',
  'My sister is ___ than me. (young) | youngest | younger | more young | youngger | B',
  'This is the ___ building in the city. (tall) | most tall | more taller | taller | tallest | D',
  'Mount Everest is the ___ mountain in the world. | higher | high | most high | highest | D',
  'She speaks English very ___. | well | good | best | nice | A',
  'There isn\'t ___ milk in the fridge. | some | a | any | many | C',
  'How ___ water do you drink a day? | much | many | often | long | A',
  'How ___ brothers do you have? | much | long | many | old | C',
  '___ is your birthday? – It\'s in June. | When | What | Where | Who | A',
  '___ do you live? – In Da Nang. | Why | When | Where | Who | C',
  '___ are you crying? – Because I\'m sad. | What | Why | How | Where | B',
  '___ is that man? – He\'s my uncle. | What | Where | Who | Which | C',
  '___ old are you? | Who | Which | What | How | D',
  'I can\'t swim, ___ my brother can. | and | because | but | so | C',
  'It was raining, ___ we stayed at home. | so | or | because | but | A',
  'She is tired ___ she worked all day. | so | because | but | or | B',
  'This is the house ___ I was born. | which | when | who | where | D',
  'If you heat ice, it ___. | melted | melt | melting | melts | D',
  'I wish I ___ a bird. | will be | were | am | being | B',
  'The letter ___ yesterday. | sends | is sending | was sent | sent | C',
  'English ___ all over the world. | is speaking | is spoken | speaks | spoke | B',
  'Let\'s go swimming, ___? | do we | shall we | will we | don\'t we | B',
  'She likes coffee, ___? | doesn\'t she | does she | don\'t she | isn\'t she | A',
  'You are a student, ___? | aren\'t you | isn\'t it | don\'t you | are you | A',
  'I enjoy ___ to music. | to listening | listened | listen | listening | D',
  'She decided ___ a new phone. | to buy | buy | bought | buying | A',
  'Stop ___! The baby is sleeping. | talking | talked | talks | talk | A',
  'Which word has a different "oo" sound? | blood | cool | food | moon | A',
  '"It\'s raining cats and dogs" means? | Có bão tuyết | Trời nắng đẹp | Chó mèo rơi xuống | Mưa rất to | D',
  '"Once in a blue moon" means? | Rất hiếm khi | Hằng tháng | Mỗi đêm | Trăng màu xanh | A',
  '"Hit the books" means? | Học chăm chỉ | Ném sách | Đánh vào sách | Đọc truyện tranh | A',
  '"Under the weather" means? | Rất vui | Đi dạo | Đứng dưới mưa | Hơi mệt, không khỏe | D',
  '"Cost an arm and a leg" means? | Miễn phí | Rất rẻ | Rất đắt | Bị thương | C',
  '"See you later" means? | Xin lỗi | Cảm ơn | Hẹn gặp lại | Xin chào | C',
  '"Excuse me" is used to ___. | get attention politely | say goodbye | agree | say thank you | A',
  'Best reply to "Sorry I\'m late"? | That\'s OK | Me too | Good job | You\'re welcome | A',
  'Best reply to "Happy birthday!"? | You\'re welcome | I\'m sorry | Thank you! | Me too | C',
  '"What time is it?" – ___ | It\'s seven dollars | It\'s half past seven | It\'s Monday | It\'s sunny | B',
  '"What\'s the weather like?" – ___ | I\'m fine | It\'s Monday | It\'s sunny | It\'s eight o\'clock | C',
  '"How much is it?" – ___ | It\'s big | It\'s fifty thousand dong | It\'s mine | It\'s red | B',
  '"Where are you from?" – ___ | I\'m a student | I\'m fine | I\'m ten | I\'m from Vietnam | D',
  'The opposite of "left" is ___. | write | right | wrong | light | B',
  'Which word is a color? | pencil | pear | puppy | purple | D',
  'Which word is an animal? | basket | rocket | rabbit | carrot | C',
  'Which word is a job? | English | engine | engineer | energy | C',
  'Which day comes before Friday? | Saturday | Sunday | Wednesday | Thursday | D',
  'The last month of the year? | January | December | October | November | B',
  'How many months are there in a year? | ten | twelve | thirteen | eleven | B',
  '"Fifteen" is? | 16 | 5 | 15 | 50 | C',
  '"A hundred" is? | 10 | 100 | 10000 | 1000 | B',
  'Which word is spelled correctly? | Wednesday | Wensday | Wednsday | Wedensday | A',
  'Which word is spelled correctly? | friend | frend | friand | freind | A'
].join('\n');
