/**
 * Beginner English quiz (default for "Quiz A/B/C/D"): colors, numbers, animals,
 * everyday words, am/is/are, a/an, greetings. Each line:
 * Question | A | B | C | D | correct letter
 */
export const ENGLISH_EASY_QUIZ_BANK = [
  'What color is the sky? ☁️ | red | green | black | blue | D',
  'What color is a banana? 🍌 | purple | yellow | pink | blue | B',
  'What color is grass? 🌿 | orange | white | red | green | D',
  'What color is snow? ❄️ | black | brown | white | blue | C',
  'What color is a tomato? 🍅 | red | gray | purple | green | A',
  'What color is chocolate? 🍫 | blue | white | yellow | brown | D',
  'Red + yellow = ? | orange | pink | purple | green | A',
  'One, two, three, ___ | ten | six | four | five | C',
  'What number is "ten"? | 10 | 100 | 2 | 12 | A',
  'What number is "seven"? | 11 | 7 | 17 | 1 | B',
  'What number is "twenty"? | 20 | 2 | 12 | 22 | A',
  '2 + 3 = ? | four | six | three | five | D',
  '10 − 4 = ? | six | five | seven | four | A',
  'How many legs does a dog have? 🐕 | six | four | eight | two | B',
  'How many days are in a week? | six | seven | ten | five | B',
  '🐶 is a ___ | fish | cow | dog | cat | C',
  '🐱 is a ___ | duck | pig | dog | cat | D',
  '🐮 is a ___ | goat | sheep | horse | cow | D',
  '🐷 is a ___ | pig | lion | dog | bear | A',
  '🐔 is a ___ | duck | goose | bird | chicken | D',
  '🐟 is a ___ | shark | fish | crab | frog | B',
  '🐘 is an ___ | ant | owl | eagle | elephant | D',
  '🦁 is a ___ | bear | wolf | lion | tiger | C',
  '🐒 is a ___ | mouse | rabbit | monkey | panda | C',
  '🐰 is a ___ | cat | fox | rat | rabbit | D',
  '🍎 is an ___ | apple | orange | egg | onion | A',
  '🍌 is a ___ | banana | mango | lemon | pear | A',
  '🍇 are ___ | lemons | grapes | apples | cherries | B',
  '🥚 is an ___ | orange | egg | apple | ice | B',
  '🍞 is ___ | cake | bread | cheese | rice | B',
  '🥛 is ___ | water | tea | juice | milk | D',
  '🍚 is ___ | noodles | bread | rice | soup | C',
  '🍉 is a ___ | papaya | coconut | watermelon | pineapple | C',
  '🚗 is a ___ | bus | car | bike | train | B',
  '🚌 is a ___ | truck | taxi | car | bus | D',
  '✈️ is a ___ | plane | ship | car | train | A',
  '🚲 is a ___ | car | bike | bus | boat | B',
  '📚 are ___ | bags | pens | books | desks | C',
  '✏️ is a ___ | ruler | chair | book | pencil | D',
  '🏫 is a ___ | bank | school | hospital | park | B',
  '🏠 is a ___ | shop | hotel | house | school | C',
  '☀️ is the ___ | star | cloud | moon | sun | D',
  '🌙 is the ___ | sky | sun | moon | star | C',
  '🌧️ It is ___ | rainy | snowy | sunny | windy | A',
  '☀️ It is ___ | sunny | cloudy | rainy | snowy | A',
  '"Con chó" in English? | cow | cat | dog | pig | C',
  '"Con mèo" in English? | fish | cat | dog | bird | B',
  '"Quả táo" in English? | banana | orange | apple | grape | C',
  '"Trường học" in English? | house | school | hospital | market | B',
  '"Mẹ" in English? | mother | sister | brother | father | A',
  '"Bố" in English? | mother | uncle | father | grandfather | C',
  '"Anh/em trai" in English? | sister | cousin | friend | brother | D',
  '"Chị/em gái" in English? | aunt | brother | mother | sister | D',
  '"Bạn bè" in English? | friend | doctor | teacher | baby | A',
  '"Giáo viên" in English? | farmer | student | teacher | doctor | C',
  '"Học sinh" in English? | nurse | driver | student | teacher | C',
  '"Bác sĩ" in English? | teacher | singer | doctor | chef | C',
  '"Nước" in English? | milk | tea | juice | water | D',
  '"Cái bàn" in English? | bed | table | chair | door | B',
  '"Cái ghế" in English? | lamp | table | window | chair | D',
  '"Cửa sổ" in English? | wall | door | floor | window | D',
  '"Cái giường" in English? | desk | bed | sofa | chair | B',
  '"Màu đỏ" in English? | blue | yellow | green | red | D',
  '"Màu xanh dương" in English? | green | blue | red | white | B',
  '"Mắt" in English? | eye | ear | mouth | nose | A',
  '"Tai" in English? | leg | ear | hand | eye | B',
  '"Mũi" in English? | hair | head | mouth | nose | D',
  '"Bàn tay" in English? | arm | leg | hand | foot | C',
  '"Đầu" in English? | face | hair | neck | head | D',
  '"Hôm nay" in English? | yesterday | tonight | today | tomorrow | C',
  '"Ngày mai" in English? | morning | today | tomorrow | yesterday | C',
  '"Buổi sáng" in English? | afternoon | night | evening | morning | D',
  '"Vui vẻ" in English? | tired | happy | angry | sad | B',
  '"Buồn" in English? | hot | big | sad | happy | C',
  '"To, lớn" in English? | small | short | thin | big | D',
  '"Nhỏ" in English? | small | tall | big | long | A',
  '"Nóng" in English? | cool | warm | cold | hot | D',
  '"Lạnh" in English? | hot | sunny | dry | cold | D',
  '"Ăn" in English? | run | drink | sleep | eat | D',
  '"Uống" in English? | sing | eat | drink | swim | C',
  '"Ngủ" in English? | read | sleep | walk | play | B',
  '"Chạy" in English? | run | sit | stand | jump | A',
  '"Hát" in English? | sing | write | dance | draw | A',
  '"Bơi" in English? | run | walk | swim | fly | C',
  '"Dog" means? | Con chó | Con cá | Con gà | Con mèo | A',
  '"Cat" means? | Con chó | Con chuột | Con mèo | Con vịt | C',
  '"Book" means? | Quyển sách | Cái bàn | Cái bút | Cái cặp | A',
  '"Pen" means? | Quyển vở | Cái thước | Cục tẩy | Cái bút | D',
  '"House" means? | Cửa hàng | Trường học | Bệnh viện | Ngôi nhà | D',
  '"Car" means? | Xe đạp | Tàu hỏa | Máy bay | Ô tô | D',
  '"Sun" means? | Mặt trăng | Mặt trời | Đám mây | Ngôi sao | B',
  '"Water" means? | Sữa | Nước ép | Trà | Nước | D',
  '"Happy" means? | Tức giận | Buồn | Mệt | Vui vẻ | D',
  '"Big" means? | Nhỏ | Cao | To, lớn | Thấp | C',
  '"Red" means? | Màu đen | Màu vàng | Màu đỏ | Màu xanh | C',
  '"Friend" means? | Hàng xóm | Gia đình | Bạn bè | Giáo viên | C',
  '"Morning" means? | Buổi tối | Buổi sáng | Ban đêm | Buổi trưa | B',
  '"Thank you" means? | Cảm ơn | Xin chào | Tạm biệt | Xin lỗi | A',
  '"Sorry" means? | Tạm biệt | Cảm ơn | Chúc mừng | Xin lỗi | D',
  '"Goodbye" means? | Tạm biệt | Xin chào | Cảm ơn | Chúc ngủ ngon | A',
  '"Good night" means? | Tạm biệt | Chúc ngủ ngon | Cảm ơn | Chào buổi sáng | B',
  'I ___ a student. | is | am | are | be | B',
  'She ___ my sister. | am | is | be | are | B',
  'They ___ my friends. | are | am | is | be | A',
  'He ___ ten years old. | is | am | have | are | A',
  'We ___ happy. | are | is | am | be | A',
  'It ___ a cat. | be | is | are | am | B',
  'You ___ my best friend. | are | be | am | is | A',
  'This is ___ apple. | an | a | many | two | A',
  'This is ___ book. | two | many | an | a | D',
  'I have two ___. | cat | cats | an cat | a cat | B',
  'There are three ___. | a dog | dogs | doges | dog | B',
  'I ___ like milk. | aren\'t | don\'t | isn\'t | doesn\'t | B',
  'She ___ a red bag. | has | have | am | is | A',
  'I ___ my teeth every morning. | brushes | brushed | brushing | brush | D',
  'Hello! How ___ you? | is | be | am | are | D',
  '___ is your name? | Where | When | Who | What | D',
  '___ are you from? | What | Who | How | Where | D',
  'How ___ are you? – I\'m 9. | long | much | old | many | C',
  'Best reply to "Hello!"? | Hi! | Sorry! | Goodbye! | No! | A',
  'Best reply to "How are you?" | I\'m fine, thanks. | I\'m from Hanoi. | I\'m Lan. | I\'m ten. | A',
  'Best reply to "Thank you!"? | Me too. | Hello. | You\'re welcome. | Sorry. | C',
  'Best reply to "What\'s your name?" | I\'m 8. | Goodbye. | My name is Nam. | I\'m fine. | C',
  'Which one is a fruit? | bread | rice | mango | carrot | C',
  'Which one is an animal? | tiger | train | table | tree | A',
  'Which one is a color? | pink | pig | pen | park | A',
  'Which one is a number? | nose | night | nice | nine | D',
  'Which one is a day of the week? | Moon | March | Morning | Monday | D',
  'Which one is a month? | June | Sunday | Summer | Sun | A',
  'Which one can fly? 🕊️ | bird | fish | cow | dog | A',
  'Which one lives in water? | chicken | fish | cat | horse | B',
  'Which one do we wear on our feet? | hats | shirts | gloves | shoes | D',
  'Which one do we use to write? | cup | shoe | pen | bed | C',
  'Which one do we drink? | juice | rice | egg | bread | A',
  'Opposite of "big"? | fat | small | tall | long | B',
  'Opposite of "hot"? | wet | sunny | cold | warm | C',
  'Opposite of "happy"? | sad | glad | good | funny | A',
  'Opposite of "up"? | in | down | on | out | B',
  'Opposite of "yes"? | no | ok | hi | so | A',
  'Opposite of "old"? | new | long | fast | big | A',
  'Opposite of "day"? | time | night | week | noon | B',
  'The day after Sunday? | Monday | Friday | Tuesday | Saturday | A',
  'The first month of the year? | June | January | July | December | B',
  'We see with our ___. | ears | hands | eyes | nose | C',
  'We hear with our ___. | mouth | eyes | ears | feet | C',
  'A cow says ___. | woof | meow | quack | moo | D',
  'A dog says ___. | baa | oink | woof | moo | C',
  'A duck says ___. | moo | woof | quack | meow | C',
  'A cat says ___. | meow | woof | quack | moo | A'
].join('\n');
