/**
 * Default content for the Japanese games. Answers are compared after
 * foldJapanese (katakana = hiragana, romaji without macrons, no spaces);
 * "/" adds accepted alternatives (romaji spellings, readings).
 */

/** Hiragana — kana | romaji[/cách viết khác] */
export const HIRAGANA_BANK = [
  'あ | a',
  'い | i',
  'う | u',
  'え | e',
  'お | o',
  'か | ka',
  'き | ki',
  'く | ku',
  'け | ke',
  'こ | ko',
  'さ | sa',
  'し | shi/si',
  'す | su',
  'せ | se',
  'そ | so',
  'た | ta',
  'ち | chi/ti',
  'つ | tsu/tu',
  'て | te',
  'と | to',
  'な | na',
  'に | ni',
  'ぬ | nu',
  'ね | ne',
  'の | no',
  'は | ha',
  'ひ | hi',
  'ふ | fu/hu',
  'へ | he',
  'ほ | ho',
  'ま | ma',
  'み | mi',
  'む | mu',
  'め | me',
  'も | mo',
  'や | ya',
  'ゆ | yu',
  'よ | yo',
  'ら | ra',
  'り | ri',
  'る | ru',
  'れ | re',
  'ろ | ro',
  'わ | wa',
  'を | wo/o',
  'ん | n/nn'
].join('\n');

/** Katakana — kana | romaji[/cách viết khác] */
export const KATAKANA_BANK = [
  'ア | a',
  'イ | i',
  'ウ | u',
  'エ | e',
  'オ | o',
  'カ | ka',
  'キ | ki',
  'ク | ku',
  'ケ | ke',
  'コ | ko',
  'サ | sa',
  'シ | shi/si',
  'ス | su',
  'セ | se',
  'ソ | so',
  'タ | ta',
  'チ | chi/ti',
  'ツ | tsu/tu',
  'テ | te',
  'ト | to',
  'ナ | na',
  'ニ | ni',
  'ヌ | nu',
  'ネ | ne',
  'ノ | no',
  'ハ | ha',
  'ヒ | hi',
  'フ | fu/hu',
  'ヘ | he',
  'ホ | ho',
  'マ | ma',
  'ミ | mi',
  'ム | mu',
  'メ | me',
  'モ | mo',
  'ヤ | ya',
  'ユ | yu',
  'ヨ | yo',
  'ラ | ra',
  'リ | ri',
  'ル | ru',
  'レ | re',
  'ロ | ro',
  'ワ | wa',
  'ヲ | wo/o',
  'ン | n/nn'
].join('\n');

/** Short words in kana — từ | romaji | nghĩa */
export const KANA_WORDS_BANK = [
  'ねこ | neko | con mèo',
  'いぬ | inu | con chó',
  'さかな | sakana | con cá',
  'すし | sushi/susi | món sushi',
  'さくら | sakura | hoa anh đào',
  'やま | yama | núi',
  'みず | mizu | nước',
  'ほん | hon | sách',
  'くるま | kuruma | xe hơi',
  'ともだち | tomodachi | bạn bè',
  'ありがとう | arigatou/arigato | cảm ơn',
  'こんにちは | konnichiwa/konnichiha | xin chào',
  'せんせい | sensei | giáo viên',
  'がっこう | gakkou/gakko | trường học',
  'たまご | tamago | trứng',
  'りんご | ringo | quả táo',
  'テレビ | terebi | ti vi',
  'パン | pan | bánh mì',
  'カメラ | kamera | máy ảnh',
  'トマト | tomato | cà chua',
  'アイス | aisu | kem',
  'ゲーム | geemu/gemu | trò chơi',
  'ピアノ | piano | đàn piano',
  'バナナ | banana | quả chuối'
].join('\n');

/** Vocabulary — chữ Nhật | cách đọc/romaji… | nghĩa tiếng Việt */
export const JAPANESE_VOCAB_BANK = [
  '猫 | ねこ/neko | con mèo',
  '犬 | いぬ/inu | con chó',
  '魚 | さかな/sakana | con cá',
  '鳥 | とり/tori | con chim',
  '水 | みず/mizu | nước',
  '山 | やま/yama | núi',
  '川 | かわ/kawa | sông',
  '花 | はな/hana | hoa',
  '木 | き/ki | cây',
  '月 | つき/tsuki/tuki | mặt trăng',
  '雨 | あめ/ame | mưa',
  '人 | ひと/hito | người',
  '友達 | ともだち/tomodachi | bạn bè',
  '先生 | せんせい/sensei | giáo viên',
  '学生 | がくせい/gakusei | học sinh',
  '学校 | がっこう/gakkou/gakko | trường học',
  '本 | ほん/hon | sách',
  '車 | くるま/kuruma | xe hơi',
  '家 | いえ/ie | nhà',
  'お金 | おかね/okane | tiền',
  '時間 | じかん/jikan | thời gian',
  '今日 | きょう/kyou/kyo | hôm nay',
  '明日 | あした/ashita | ngày mai',
  '昨日 | きのう/kinou/kino | hôm qua',
  '朝 | あさ/asa | buổi sáng',
  '夜 | よる/yoru | ban đêm',
  'ご飯 | ごはん/gohan | cơm',
  'お茶 | おちゃ/ocha | trà',
  'コーヒー | kōhī/koohii/kohi | cà phê',
  'パン | pan | bánh mì',
  '卵 | たまご/tamago | trứng',
  '肉 | にく/niku | thịt',
  '野菜 | やさい/yasai | rau',
  'りんご | 林檎/ringo | quả táo',
  '大きい | おおきい/ookii/okii | to, lớn',
  '小さい | ちいさい/chiisai/chisai | nhỏ',
  '綺麗 | きれい/kirei | đẹp',
  '美味しい | おいしい/oishii | ngon',
  '楽しい | たのしい/tanoshii | vui vẻ',
  '暑い | あつい/atsui | nóng (thời tiết)',
  '寒い | さむい/samui | lạnh (thời tiết)',
  '食べる | たべる/taberu | ăn',
  '飲む | のむ/nomu | uống',
  '行く | いく/iku | đi',
  '来る | くる/kuru | đến',
  '見る | みる/miru | xem, nhìn',
  '寝る | ねる/neru | ngủ',
  '読む | よむ/yomu | đọc',
  '書く | かく/kaku | viết',
  'ありがとう | arigatou/arigato | cảm ơn',
  'こんにちは | konnichiwa/konnichiha | xin chào',
  'すみません | sumimasen/ごめんなさい/gomennasai | xin lỗi',
  'さようなら | sayounara/sayonara | tạm biệt',
  'おはよう | ohayou/ohayo/おはようございます/ohayougozaimasu | chào buổi sáng',
  '母 | はは/haha/お母さん/okaasan | mẹ',
  '父 | ちち/chichi/お父さん/otousan | bố',
  '一 | いち/ichi | số một',
  '二 | に/ni | số hai',
  '三 | さん/san | số ba',
  '十 | じゅう/juu/ju | số mười',
  '日本 | にほん/nihon/nippon | Nhật Bản',
  '日本語 | にほんご/nihongo | tiếng Nhật',
  'ベトナム | betonamu | Việt Nam'
].join('\n');

/** Japanese quiz (Vietnamese prompts) — Question | A | B | C | D | correct letter */
export const JAPANESE_QUIZ_BANK = [
  '「ありがとう」 nghĩa là gì? | Cảm ơn | Tạm biệt | Xin lỗi | Xin chào | A',
  '「こんにちは」 nghĩa là gì? | Cảm ơn | Chúc ngủ ngon | Hẹn gặp lại | Xin chào | D',
  '「さようなら」 nghĩa là gì? | Tạm biệt | Cảm ơn | Xin chào | Mời ăn | A',
  '「すみません」 nghĩa là gì? | Tạm biệt | Chúc mừng | Cảm ơn | Xin lỗi | D',
  '「ねこ」 là con gì? | Con mèo | Con chim | Con cá | Con chó | A',
  '「いぬ」 là con gì? | Con gà | Con chó | Con mèo | Con bò | B',
  '「みず」 nghĩa là gì? | Gió | Nước | Đất | Lửa | B',
  '「やま」 nghĩa là gì? | Sông | Rừng | Biển | Núi | D',
  '「せんせい」 nghĩa là gì? | Bác sĩ | Bạn bè | Học sinh | Giáo viên | D',
  '「たべる」 nghĩa là gì? | Ngủ | Uống | Ăn | Đi | C',
  '「のむ」 nghĩa là gì? | Ăn | Đọc | Viết | Uống | D',
  '「おいしい」 nghĩa là gì? | Đắt | Rẻ | Ngon | Cay | C',
  '「おおきい」 nghĩa là gì? | To, lớn | Nhỏ | Ngắn | Dài | A',
  '「あさ」 nghĩa là gì? | Buổi trưa | Buổi tối | Ban đêm | Buổi sáng | D',
  '「あした」 nghĩa là gì? | Tuần sau | Ngày mai | Hôm qua | Hôm nay | B',
  '「きょう」 nghĩa là gì? | Năm nay | Hôm qua | Hôm nay | Ngày mai | C',
  'Chữ 「あ」 đọc là? | o | i | e | a | D',
  'Chữ 「し」 đọc là? | su | tsu | chi | shi | D',
  'Chữ 「つ」 đọc là? | su | nu | shi | tsu | D',
  'Chữ 「ね」 đọc là? | re | nu | ne | wa | C',
  'Chữ katakana 「ア」 đọc là? | ma | a | ku | ya | B',
  'Chữ katakana 「ン」 đọc là? | so | shi | tsu | n | D',
  'Chữ 「犬」 đọc là? | いぬ | とり | うし | ねこ | A',
  'Chữ 「山」 đọc là? | かわ | やま | そら | うみ | B',
  'Chữ Hán 「水」 nghĩa là? | Cây | Nước | Vàng | Lửa | B',
  'Chữ Hán 「火」 nghĩa là? | Đất | Nước | Gió | Lửa | D',
  '「日本」 là nước nào? | Nhật Bản | Hàn Quốc | Trung Quốc | Việt Nam | A',
  '"Con mèo" tiếng Nhật là? | さかな | いぬ | ねこ | とり | C',
  '"Cảm ơn" tiếng Nhật là? | こんにちは | すみません | さようなら | ありがとう | D',
  '"Nước" tiếng Nhật là? | みず | ごはん | おちゃ | ぎゅうにゅう | A',
  '「さん」 là số mấy? | 2 | 3 | 1 | 4 | B',
  '「じゅう」 là số mấy? | 7 | 10 | 9 | 100 | B',
  '「いち」 là số mấy? | 8 | 5 | 2 | 1 | D',
  '「はい」 nghĩa là gì? | Không | Có lẽ | Vâng / Có | Tại sao | C',
  '「いいえ」 nghĩa là gì? | Vâng | Không | Được | Xin chào | B',
  '「おはよう」 dùng khi nào? | Trước khi ngủ | Buổi sáng | Buổi trưa | Buổi tối | B',
  '「おやすみなさい」 nghĩa là gì? | Chúc ngủ ngon | Chào buổi sáng | Tạm biệt | Mời vào | A',
  '「いただきます」 nói khi nào? | Trước khi ăn | Sau khi ăn | Khi chào hỏi | Khi xin lỗi | A',
  '「ごちそうさまでした」 nói khi nào? | Sau khi ăn | Khi đi ngủ | Trước khi ăn | Khi gặp mặt | A',
  'Tiếng Nhật dùng mấy loại chữ chính? | 2 | 3 (Hiragana, Katakana, Kanji) | 5 | 1 | B',
  'Nhật Bản dùng đơn vị tiền nào? | Nhân dân tệ | Won | Yên | Đô la | C',
  'Núi nổi tiếng nhất Nhật Bản là? | Núi Fansipan | Núi Everest | Núi Phú Sĩ | Núi Thái Sơn | C'
].join('\n');

/** Memory pairs — two faces that belong together. */
export const KANA_PAIRS = [
  'あ | a',
  'い | i',
  'う | u',
  'え | e',
  'お | o',
  'か | ka',
  'き | ki',
  'く | ku',
  'け | ke',
  'こ | ko',
  'さ | sa',
  'し | shi',
  'す | su',
  'せ | se',
  'そ | so',
  'た | ta',
  'ち | chi',
  'つ | tsu',
  'て | te',
  'と | to',
  'な | na',
  'に | ni',
  'ぬ | nu',
  'ね | ne',
  'の | no',
  'は | ha',
  'ひ | hi',
  'ふ | fu',
  'へ | he',
  'ほ | ho'
].join('\n');
