/**
 * Default general-knowledge quiz (Vietnamese). Streamers can replace or extend
 * it in the app (or import a .txt file). Each line:
 * Question | A | B | C | D | correct letter
 */
export const VN_QUIZ_BANK = [
  'Thủ đô của Việt Nam là? | Hà Nội | Huế | Đà Nẵng | TP. Hồ Chí Minh | A',
  '7 × 8 bằng bao nhiêu? | 54 | 56 | 58 | 64 | B',
  'Một năm có bao nhiêu tháng có 31 ngày? | 5 | 6 | 7 | 8 | C',
  'Hành tinh lớn nhất Hệ Mặt Trời? | Trái Đất | Sao Mộc | Sao Thổ | Sao Hỏa | B',
  'Nốt nhạc nào đứng sau nốt Mi? | Rê | Fa | Son | La | B',
  'Đàn piano tiêu chuẩn có bao nhiêu phím? | 66 | 76 | 88 | 98 | C',
  'Con vật nào được gọi là "chúa sơn lâm"? | Sư tử | Hổ | Voi | Gấu | B',
  'Nước sôi ở bao nhiêu độ C (áp suất tiêu chuẩn)? | 90 | 100 | 110 | 120 | B',
  'Một tuần có bao nhiêu giờ? | 148 | 158 | 168 | 178 | C',
  'Ban nhạc The Beatles đến từ nước nào? | Mỹ | Anh | Úc | Canada | B',
  'Đỉnh núi cao nhất Việt Nam? | Fansipan | Bà Đen | Ngọc Linh | Pu Ta Leng | A',
  'Khí nào chiếm nhiều nhất trong không khí? | Oxy | Nitơ | CO2 | Hydro | B',
  'Nhạc cụ nào thường có 6 dây? | Guitar | Violin | Sáo | Trống | A',
  'Tết Trung thu vào ngày nào âm lịch? | 15/7 | 15/8 | 1/1 | 5/5 | B',
  '2 mũ 10 bằng bao nhiêu? | 512 | 1000 | 1024 | 2048 | C',
  'Đại dương lớn nhất thế giới? | Đại Tây Dương | Ấn Độ Dương | Thái Bình Dương | Bắc Băng Dương | C',
  'Loài chim nào không biết bay? | Đà điểu | Đại bàng | Chim sẻ | Bồ câu | A',
  'Tim người có bao nhiêu ngăn? | 2 | 3 | 4 | 5 | C',
  'Ánh sáng Mặt Trời đến Trái Đất mất khoảng bao lâu? | 8 giây | 8 phút | 8 giờ | 8 ngày | B',
  'Vịnh Hạ Long thuộc tỉnh nào? | Quảng Ninh | Hải Phòng | Thanh Hóa | Nghệ An | A',
  'Thủ đô của Nhật Bản? | Osaka | Seoul | Kyoto | Tokyo | D',
  'Thủ đô của Pháp? | Berlin | Roma | Lyon | Paris | D',
  'Thủ đô của Úc? | Canberra | Sydney | Perth | Melbourne | A',
  'Thủ đô của Thái Lan? | Bangkok | Viêng Chăn | Chiang Mai | Phuket | A',
  'Thủ đô của Hàn Quốc? | Bắc Kinh | Seoul | Tokyo | Busan | B',
  'Thủ đô của Canada? | Montreal | Toronto | Ottawa | Vancouver | C',
  'Thủ đô của Lào? | Phnôm Pênh | Luang Prabang | Bangkok | Viêng Chăn | D',
  'Thủ đô của Campuchia? | Viêng Chăn | Phnôm Pênh | Siem Reap | Yangon | B',
  'Thủ đô của Trung Quốc? | Hồng Kông | Bắc Kinh | Thượng Hải | Quảng Châu | B',
  'Thủ đô của Anh? | London | Liverpool | Manchester | Edinburgh | A',
  'Thủ đô của Ý? | Roma | Venezia | Milano | Napoli | A',
  'Thủ đô của Đức? | Munich | Frankfurt | Hamburg | Berlin | D',
  'Thủ đô của Nga? | Moskva | Saint Petersburg | Minsk | Kazan | A',
  'Thủ đô của Brazil? | Buenos Aires | Rio de Janeiro | São Paulo | Brasília | D',
  'Thủ đô của Ai Cập? | Cairo | Luxor | Tunis | Alexandria | A',
  'Quốc gia đông dân nhất thế giới (từ năm 2023)? | Indonesia | Mỹ | Ấn Độ | Trung Quốc | C',
  'Châu lục lớn nhất thế giới? | Châu Mỹ | Châu Phi | Châu Á | Châu Âu | C',
  'Sa mạc nóng lớn nhất thế giới? | Gobi | Kalahari | Sahara | Atacama | C',
  'Núi cao nhất thế giới? | K2 | Kilimanjaro | Everest | Fansipan | C',
  'Tháp Eiffel nằm ở thành phố nào? | Madrid | Roma | London | Paris | D',
  'Kim tự tháp Giza thuộc nước nào? | Ai Cập | Peru | Hy Lạp | Mexico | A',
  'Vạn Lý Trường Thành thuộc nước nào? | Mông Cổ | Nhật Bản | Trung Quốc | Hàn Quốc | C',
  'Tượng Nữ thần Tự do ở thành phố nào? | Chicago | New York | Boston | Washington | B',
  'Sông nào chảy qua Hà Nội? | Sông Sài Gòn | Sông Hồng | Sông Hương | Sông Hàn | B',
  'Sông Hương chảy qua thành phố nào? | Đà Nẵng | Cần Thơ | Hà Nội | Huế | D',
  'Cầu Rồng nằm ở thành phố nào? | Đà Nẵng | Huế | Hà Nội | Hải Phòng | A',
  'Chợ Bến Thành ở thành phố nào? | Hà Nội | TP. Hồ Chí Minh | Cần Thơ | Đà Nẵng | B',
  'Văn Miếu – Quốc Tử Giám ở đâu? | Nam Định | Hà Nội | Bắc Ninh | Huế | B',
  'Hồ Gươm còn có tên gọi khác là? | Hồ Thiền Quang | Hồ Tây | Hồ Trúc Bạch | Hồ Hoàn Kiếm | D',
  'Mũi Cà Mau là điểm cực nào trên đất liền Việt Nam? | Cực Tây | Cực Nam | Cực Đông | Cực Bắc | B',
  'Đồng bằng lớn nhất Việt Nam? | Tây Nguyên | Đồng bằng duyên hải miền Trung | Đồng bằng sông Cửu Long | Đồng bằng sông Hồng | C',
  'Quần đảo Hoàng Sa và Trường Sa nằm ở biển nào? | Biển Đông | Biển Đỏ | Biển Bắc | Biển Đen | A',
  'Đà Lạt được mệnh danh là? | Thành phố hoa phượng đỏ | Thành phố sương mù phương Bắc | Thành phố cảng | Thành phố ngàn hoa | D',
  '"Thành phố hoa phượng đỏ" là? | Huế | Hà Nội | Đà Lạt | Hải Phòng | D',
  'Ngày Quốc khánh Việt Nam? | 19/8 | 1/5 | 2/9 | 30/4 | C',
  'Chiến thắng Điện Biên Phủ vào năm nào? | 1968 | 1945 | 1975 | 1954 | D',
  'Ai đọc bản Tuyên ngôn Độc lập ngày 2/9/1945? | Trường Chinh | Phạm Văn Đồng | Võ Nguyên Giáp | Hồ Chí Minh | D',
  'Tác giả của Truyện Kiều? | Hồ Xuân Hương | Nguyễn Trãi | Nguyễn Du | Nguyễn Đình Chiểu | C',
  '"Bình Ngô đại cáo" do ai viết? | Nguyễn Trãi | Trần Hưng Đạo | Lý Thường Kiệt | Lê Lợi | A',
  'Ai chỉ huy trận Bạch Đằng năm 938? | Ngô Quyền | Trần Hưng Đạo | Lý Bí | Lê Hoàn | A',
  'Ai chỉ huy trận Bạch Đằng năm 1288? | Trần Hưng Đạo | Quang Trung | Lê Lợi | Ngô Quyền | A',
  'Vua Quang Trung đại phá quân Thanh vào năm nào? | 1858 | 1771 | 1802 | 1789 | D',
  'Triều đại phong kiến cuối cùng của Việt Nam? | Nhà Nguyễn | Nhà Trần | Nhà Lý | Nhà Lê | A',
  'Kinh đô của nhà Nguyễn đặt ở đâu? | Gia Định | Hoa Lư | Thăng Long | Huế | D',
  'Lý Thái Tổ dời đô về Thăng Long năm nào? | 968 | 1054 | 1010 | 1009 | C',
  'Chủ tịch Hồ Chí Minh sinh năm nào? | 1911 | 1890 | 1869 | 1945 | B',
  'Bác Hồ ra đi tìm đường cứu nước năm nào? | 1911 | 1890 | 1920 | 1930 | A',
  '12 × 12 bằng bao nhiêu? | 144 | 132 | 124 | 142 | A',
  '15% của 200 là bao nhiêu? | 35 | 20 | 30 | 15 | C',
  'Căn bậc hai của 81 là? | 8 | 7 | 18 | 9 | D',
  '1 km bằng bao nhiêu mét? | 10 | 100 | 10000 | 1000 | D',
  '1 giờ có bao nhiêu giây? | 3600 | 6000 | 360 | 1800 | A',
  'Tổng ba góc trong một tam giác bằng? | 90° | 360° | 180° | 270° | C',
  'Hình lục giác có bao nhiêu cạnh? | 7 | 8 | 6 | 5 | C',
  'Số nguyên tố nhỏ nhất là? | 2 | 3 | 0 | 1 | A',
  '3 mũ 4 bằng bao nhiêu? | 27 | 12 | 81 | 64 | C',
  '100 chia 8 bằng bao nhiêu? | 13,5 | 8,5 | 12,5 | 12 | C',
  'Số La Mã "X" là số mấy? | 5 | 100 | 10 | 50 | C',
  'Số La Mã "L" là số mấy? | 50 | 5 | 100 | 500 | A',
  '25 × 4 bằng bao nhiêu? | 100 | 90 | 104 | 125 | A',
  'Năm nhuận có bao nhiêu ngày? | 360 | 364 | 366 | 365 | C',
  'Tháng 2 của năm nhuận có bao nhiêu ngày? | 28 | 31 | 30 | 29 | D',
  '0,5 bằng phân số nào? | 1/5 | 1/2 | 5/1 | 2/5 | B',
  'Một thế kỷ có bao nhiêu năm? | 100 | 10 | 50 | 1000 | A',
  'Một tá là bao nhiêu? | 6 | 10 | 20 | 12 | D',
  'Một năm có khoảng bao nhiêu tuần? | 50 | 52 | 48 | 56 | B',
  'Công thức hóa học của nước? | CO2 | H2O | NaCl | O2 | B',
  'Muối ăn có công thức hóa học là? | H2O | KCl | CaCO3 | NaCl | D',
  'Hành tinh gần Mặt Trời nhất? | Trái Đất | Sao Kim | Sao Hỏa | Sao Thủy | D',
  'Hành tinh nào được gọi là "hành tinh đỏ"? | Sao Thổ | Sao Hỏa | Sao Kim | Sao Mộc | B',
  'Hành tinh có vành đai nổi bật nhất? | Sao Thổ | Sao Mộc | Sao Hỏa | Trái Đất | A',
  'Hệ Mặt Trời có bao nhiêu hành tinh? | 7 | 8 | 9 | 10 | B',
  'Vệ tinh tự nhiên của Trái Đất là? | Sao Hỏa | Mặt Trời | Sao Kim | Mặt Trăng | D',
  'Cây xanh hấp thụ khí gì để quang hợp? | CO2 | N2 | O2 | H2 | A',
  'Cơ quan nào bơm máu đi khắp cơ thể? | Phổi | Gan | Thận | Tim | D',
  'Cơ thể người trưởng thành có khoảng bao nhiêu chiếc xương? | 306 | 256 | 206 | 106 | C',
  'Kim loại nào ở thể lỏng ở nhiệt độ phòng? | Thủy ngân | Sắt | Đồng | Nhôm | A',
  'Kí hiệu hóa học của vàng? | Fe | Ag | Al | Au | D',
  'Kí hiệu hóa học của sắt? | Ir | Fe | F | Si | B',
  'Tốc độ ánh sáng khoảng bao nhiêu km/s? | 30.000 | 3.000 | 300.000 | 3.000.000 | C',
  'Nước đóng băng ở bao nhiêu độ C (áp suất tiêu chuẩn)? | 4 | 0 | -10 | 10 | B',
  'Động vật lớn nhất hành tinh? | Cá mập trắng | Cá voi xanh | Hươu cao cổ | Voi châu Phi | B',
  'Động vật trên cạn chạy nhanh nhất? | Sư tử | Linh dương | Ngựa | Báo săn | D',
  'Con vật nào có 8 chân? | Bướm | Nhện | Kiến | Ong | B',
  'Con vật nào là động vật có vú? | Cá mập | Cá ngựa | Cá chép | Cá heo | D',
  'Ong mật làm ra sản phẩm nào? | Sữa | Tơ tằm | Mật ong | Nhựa cây | C',
  'Pha màu vàng với màu xanh dương (màu vẽ) được màu gì? | Xanh lá | Tím | Cam | Nâu | A',
  'Cầu vồng có mấy màu? | 7 | 5 | 8 | 6 | A',
  'World Cup bóng đá nam được tổ chức mấy năm một lần? | 3 | 5 | 2 | 4 | D',
  'Mỗi đội bóng đá có bao nhiêu cầu thủ trên sân? | 12 | 10 | 9 | 11 | D',
  'Mỗi đội bóng rổ có bao nhiêu người trên sân? | 11 | 7 | 6 | 5 | D',
  'Thế vận hội mùa hè 2024 được tổ chức ở đâu? | Los Angeles | Paris | London | Tokyo | B',
  'Môn thể thao nào được gọi là "môn thể thao vua"? | Bóng đá | Quần vợt | Cầu lông | Bóng rổ | A',
  'Món bánh truyền thống ngày Tết của miền Bắc? | Bánh chưng | Bánh mì | Bánh xèo | Bánh tét | A',
  'Áo dài là trang phục truyền thống của nước nào? | Thái Lan | Việt Nam | Hàn Quốc | Nhật Bản | B',
  'Kimono là trang phục truyền thống của nước nào? | Nhật Bản | Hàn Quốc | Việt Nam | Trung Quốc | A',
  'Hanbok là trang phục truyền thống của nước nào? | Thái Lan | Lào | Nhật Bản | Hàn Quốc | D',
  'Phở là món ăn nổi tiếng của nước nào? | Hàn Quốc | Việt Nam | Nhật Bản | Thái Lan | B',
  'Sushi là món ăn nổi tiếng của nước nào? | Nhật Bản | Hàn Quốc | Thái Lan | Trung Quốc | A',
  'Kim chi là món ăn nổi tiếng của nước nào? | Hàn Quốc | Nhật Bản | Việt Nam | Ấn Độ | A',
  'Nhạc sĩ sáng tác bài "Tiến quân ca"? | Văn Cao | Phạm Tuyên | Trịnh Công Sơn | Hoàng Việt | A',
  'Ca khúc "Diễm xưa" là của nhạc sĩ nào? | Văn Cao | Trịnh Công Sơn | Phạm Duy | Ngô Thụy Miên | B',
  'Nhà soạn nhạc bị điếc nhưng vẫn viết Giao hưởng số 9? | Chopin | Bach | Beethoven | Mozart | C',
  'Đàn bầu có mấy dây? | 3 | 4 | 2 | 1 | D',
  'Có bao nhiêu nốt nhạc cơ bản (Đô, Rê, Mi…)? | 8 | 5 | 7 | 12 | C',
  'Bức tranh "Mona Lisa" do ai vẽ? | Leonardo da Vinci | Picasso | Van Gogh | Michelangelo | A',
  'Tác giả bộ truyện "Harry Potter"? | Stephen King | Agatha Christie | J.R.R. Tolkien | J.K. Rowling | D',
  '"Dế Mèn phiêu lưu ký" là tác phẩm của ai? | Tô Hoài | Nguyễn Nhật Ánh | Kim Lân | Nam Cao | A',
  '"Cho tôi xin một vé đi tuổi thơ" là tác phẩm của ai? | Nguyễn Nhật Ánh | Xuân Quỳnh | Nguyễn Tuân | Tô Hoài | A',
  'Nhân vật Chí Phèo là của nhà văn nào? | Nguyễn Tuân | Ngô Tất Tố | Nam Cao | Vũ Trọng Phụng | C',
  'Người đầu tiên đặt chân lên Mặt Trăng? | Phạm Tuân | Neil Armstrong | Yuri Gagarin | Buzz Aldrin | B',
  'Người Việt Nam đầu tiên bay vào vũ trụ? | Neil Armstrong | Trần Đại Nghĩa | Tôn Thất Tùng | Phạm Tuân | D',
  'Ai đưa ra thuyết tương đối? | Albert Einstein | Isaac Newton | Galileo Galilei | Charles Darwin | A',
  'Ai phát hiện ra định luật vạn vật hấp dẫn? | Thomas Edison | Isaac Newton | Albert Einstein | Nikola Tesla | B',
  'TikTok thuộc công ty nào? | Meta | Tencent | Google | ByteDance | D',
  'Hãng nào sản xuất iPhone? | Xiaomi | Samsung | Nokia | Apple | D',
  'Đơn vị tiền tệ của Nhật Bản? | Nhân dân tệ | Yên | Baht | Won | B',
  'Đơn vị tiền tệ của Thái Lan? | Baht | Kíp | Riel | Yên | A',
  'Đồng tiền chung của nhiều nước châu Âu? | Euro | Rúp | Đô la | Bảng Anh | A',
  'Đèn giao thông màu nào báo hiệu dừng lại? | Vàng | Xanh | Trắng | Đỏ | D',
  'Số điện thoại gọi cứu hỏa ở Việt Nam? | 115 | 116 | 114 | 113 | C',
  'Số điện thoại gọi cấp cứu y tế ở Việt Nam? | 112 | 115 | 114 | 113 | B',
  'Hình tròn có bao nhiêu trục đối xứng? | 2 | 4 | Vô số | 1 | C',
  'Con giáp đứng đầu trong 12 con giáp? | Rồng (Thìn) | Chuột (Tý) | Trâu (Sửu) | Hổ (Dần) | B',
  'Con giáp cuối cùng trong 12 con giáp? | Chó (Tuất) | Gà (Dậu) | Dê (Mùi) | Lợn (Hợi) | D',
  'Loại quả nào được gọi là "vua của các loại trái cây"? | Măng cụt | Xoài | Sầu riêng | Chôm chôm | C',
  'Khí hậu ôn đới thường có mấy mùa? | 4 | 2 | 3 | 6 | A',
  'Điền vào chỗ trống: "Có công mài sắt, có ngày nên ___" | dao | cột | kim | búa | C',
  'Điền vào chỗ trống: "Ăn quả nhớ kẻ ___ cây" | hái | trồng | bán | tưới | B',
  'Điền vào chỗ trống: "Uống nước nhớ ___" | mưa | nguồn | sông | biển | B',
  'Điền vào chỗ trống: "Ba cây chụm lại nên hòn núi ___" | xanh | to | cao | dài | C',
  'Điền vào chỗ trống: "Gần mực thì đen, gần đèn thì ___" | tắt | nóng | tối | rạng | D',
  'Điền vào chỗ trống: "Tốt gỗ hơn tốt ___" | lớp áo | nước sơn | lá cây | màu vẽ | B',
  'Điền vào chỗ trống: "Chị ngã em ___" | chạy | kéo | cười | nâng | D',
  'Điền vào chỗ trống: "Lá lành đùm lá ___" | khô | rách | úa | non | B',
  'Điền vào chỗ trống: "Đi một ngày đàng, học một sàng ___" | sách | bạn | khôn | chữ | C',
  'Điền vào chỗ trống: "Không thầy đố mày làm ___" | giàu | nên | xong | được việc | B',
  'Điền vào chỗ trống: "Nước chảy đá ___" | trôi | vỡ | lăn | mòn | D',
  'Điền vào chỗ trống: "Ăn cây nào rào cây ___" | kia | đó | nấy | ấy | C',
  'Điền vào chỗ trống: "Học ăn, học nói, học gói, học ___" | mở | làm | đọc | viết | A',
  'Điền vào chỗ trống: "Thương người như thể thương ___" | nhà | thân | ta | con | B',
  'Điền vào chỗ trống: "Một con ngựa đau, cả tàu bỏ ___" | cỏ | ăn | cơm | chạy | A',
  'Điền vào chỗ trống: "Muốn sang thì bắc cầu ___" | đá | kiều | tre | gỗ | B',
  'Điền vào chỗ trống: "Tiên học lễ, hậu học ___" | toán | nghề | chữ | văn | D',
  'Quốc gia có diện tích lớn nhất thế giới? | Mỹ | Trung Quốc | Nga | Canada | C',
  'Đại dương nhỏ nhất thế giới? | Thái Bình Dương | Bắc Băng Dương | Ấn Độ Dương | Đại Tây Dương | B',
  'Sông Mê Kông đổ ra biển ở nước nào? | Việt Nam | Campuchia | Lào | Thái Lan | A',
  'Quốc gia nào có lãnh thổ hình chiếc ủng? | Nhật Bản | Hy Lạp | Chile | Ý | D',
  'Thành phố nào được gọi là "Quả táo lớn"? | London | Los Angeles | New York | Chicago | C',
  'Thủ đô của Singapore? | Singapore | Manila | Jakarta | Kuala Lumpur | A',
  'Thủ đô của Malaysia? | Kuala Lumpur | Singapore | Penang | Bangkok | A',
  'Thủ đô của Philippines? | Cebu | Manila | Davao | Jakarta | B',
  'Thủ đô của Tây Ban Nha? | Madrid | Sevilla | Lisbon | Barcelona | A',
  'Thủ đô của Mỹ? | Los Angeles | New York | Chicago | Washington, D.C. | D',
  'Thủ đô của Ấn Độ? | Mumbai | Kolkata | New Delhi | Bangalore | C',
  'Thủ đô của Argentina? | Lima | Buenos Aires | Montevideo | Santiago | B',
  'Thủ đô của Bồ Đào Nha? | Roma | Lisbon | Madrid | Porto | B',
  'Thủ đô của Hy Lạp? | Sparta | Athens | Roma | Istanbul | B',
  'Thủ đô của Thổ Nhĩ Kỳ? | Istanbul | Ankara | Izmir | Athens | B',
  'Thủ đô của Myanmar? | Bangkok | Mandalay | Yangon | Naypyidaw | D',
  'Núi Phú Sĩ nằm ở nước nào? | Hàn Quốc | Trung Quốc | Nepal | Nhật Bản | D',
  'Tháp nghiêng nổi tiếng của Ý nằm ở thành phố nào? | Pisa | Venezia | Milano | Roma | A',
  'Kênh đào Panama nối hai đại dương nào? | Ấn Độ Dương và Thái Bình Dương | Bắc Băng Dương và Đại Tây Dương | Đại Tây Dương và Ấn Độ Dương | Thái Bình Dương và Đại Tây Dương | D',
  'Sông dài nhất châu Á? | Sông Hằng | Trường Giang | Mê Kông | Hoàng Hà | B',
  'Đền Angkor Wat nằm ở nước nào? | Lào | Campuchia | Myanmar | Thái Lan | B',
  'Nhà hát Opera Sydney thuộc nước nào? | Canada | Anh | Úc | New Zealand | C',
  'Lăng Taj Mahal ở nước nào? | Iran | Thổ Nhĩ Kỳ | Pakistan | Ấn Độ | D',
  'Nước đông dân nhất châu Phi? | Ethiopia | Nam Phi | Ai Cập | Nigeria | D',
  'Chuột túi kangaroo là biểu tượng của nước nào? | Úc | Nam Phi | New Zealand | Brazil | A',
  'Gấu trúc là biểu tượng của nước nào? | Ấn Độ | Nhật Bản | Trung Quốc | Thái Lan | C',
  'Việt Nam nằm ở khu vực nào? | Nam Á | Đông Á | Đông Nam Á | Trung Á | C',
  'Việt Nam giáp những nước nào trên đất liền? | Myanmar, Lào, Campuchia | Trung Quốc, Thái Lan, Lào | Thái Lan, Lào, Campuchia | Trung Quốc, Lào, Campuchia | D',
  'Lá cờ Việt Nam có màu gì? | Nền xanh sao trắng | Nền trắng sao đỏ | Nền vàng sao đỏ | Nền đỏ sao vàng | D',
  'Quốc ca Việt Nam là bài hát nào? | Tiến quân ca | Việt Nam quê hương tôi | Như có Bác trong ngày vui đại thắng | Giải phóng miền Nam | A',
  'Nhã nhạc cung đình gắn với cố đô nào? | Hội An | Hà Nội | Hoa Lư | Huế | D',
  'Ngày Nhà giáo Việt Nam? | 1/6 | 8/3 | 20/11 | 26/3 | C',
  'Ngày Quốc tế Thiếu nhi? | 20/11 | 1/5 | 1/6 | 8/3 | C',
  'Ngày Quốc tế Phụ nữ? | 20/10 | 14/2 | 8/3 | 1/6 | C',
  'Ngày Phụ nữ Việt Nam? | 20/10 | 1/6 | 8/3 | 20/11 | A',
  'Tết Đoan Ngọ vào ngày nào âm lịch? | 7/7 | 5/5 | 15/8 | 1/1 | B',
  'Giỗ Tổ Hùng Vương vào ngày nào? | 15/8 âm lịch | 5/5 âm lịch | 10/3 âm lịch | 15/1 âm lịch | C',
  'Truyền thuyết "Con Rồng cháu Tiên" kể về ai? | Lạc Long Quân và Âu Cơ | Sơn Tinh và Thủy Tinh | Thánh Gióng | An Dương Vương | A',
  'Nhân vật nào nhổ tre đánh giặc Ân? | Lê Lợi | Sơn Tinh | Mai An Tiêm | Thánh Gióng | D',
  'Ai trồng dưa hấu trên đảo hoang trong truyện cổ tích? | Thạch Sanh | Mai An Tiêm | Sọ Dừa | Chử Đồng Tử | B',
  'Sự tích bánh chưng bánh giầy gắn với ai? | Sơn Tinh | Lang Liêu | Chử Đồng Tử | Thánh Gióng | B',
  'Ai trả gươm cho Rùa Vàng ở hồ Hoàn Kiếm? | Quang Trung | Lý Thái Tổ | Lê Lợi | Trần Hưng Đạo | C',
  'Hai Bà Trưng khởi nghĩa chống quân xâm lược nào? | Nhà Nguyên | Nhà Minh | Nhà Hán | Nhà Thanh | C',
  'Vị vua đầu tiên của nhà Lý? | Lý Thái Tổ | Lý Thánh Tông | Lý Nhân Tông | Lý Thái Tông | A',
  'Chữ viết chính thức của tiếng Việt hiện nay? | Chữ Phạn | Chữ Nôm | Chữ Hán | Chữ Quốc ngữ | D',
  'Bảng chữ cái tiếng Việt có bao nhiêu chữ cái? | 24 | 33 | 29 | 26 | C',
  'Tiếng Việt có bao nhiêu thanh điệu? | 5 | 6 | 7 | 4 | B',
  'Cơ quan nào giúp con người hô hấp? | Tim | Phổi | Gan | Dạ dày | B',
  'Máu có màu đỏ nhờ chất nào? | Hemoglobin | Insulin | Tinh bột | Canxi | A',
  'Cơ thể tạo ra vitamin nào khi tắm nắng? | Vitamin C | Vitamin D | Vitamin A | Vitamin B12 | B',
  'Cam, chanh giàu vitamin nào? | Vitamin B1 | Vitamin D | Vitamin C | Vitamin K | C',
  'Nguồn năng lượng chính của Trái Đất? | Núi lửa | Mặt Trời | Gió | Mặt Trăng | B',
  'Trái Đất quay một vòng quanh Mặt Trời mất khoảng bao lâu? | 365 ngày | 100 ngày | 24 giờ | 30 ngày | A',
  'Trái Đất tự quay quanh trục mất khoảng bao lâu? | 7 ngày | 12 giờ | 30 ngày | 24 giờ | D',
  'Con người cần khí gì để thở? | Heli | CO2 | Oxy | Hydro | C',
  'Âm thanh truyền nhanh nhất trong môi trường nào? | Chân không | Chất rắn | Chất lỏng | Không khí | B',
  'Đơn vị đo cường độ dòng điện? | Ampe | Oát | Ôm | Vôn | A',
  'Đơn vị đo hiệu điện thế? | Ampe | Jun | Vôn | Oát | C',
  'Nhiệt kế dùng để đo gì? | Độ ẩm | Tốc độ gió | Áp suất | Nhiệt độ | D',
  'Con vật nào đẻ trứng? | Chó | Mèo | Bò | Gà | D',
  'Con vật nào sống được cả dưới nước và trên cạn? | Ếch | Cá chép | Mèo | Chim sẻ | A',
  'Sâu bướm lớn lên thành con gì? | Ong | Chuồn chuồn | Bướm | Kiến | C',
  'Nòng nọc lớn lên thành con gì? | Thằn lằn | Rắn | Cá | Ếch | D',
  'Loài chim nào bắt chước tiếng người giỏi? | Cú | Vẹt | Đại bàng | Chim cánh cụt | B',
  'Con vật nào có cổ dài nhất? | Đà điểu | Ngựa | Hươu cao cổ | Lạc đà | C',
  'Chim cánh cụt hoàng đế sống ở đâu? | Rừng Amazon | Bắc Cực | Châu Nam Cực | Sa mạc Sahara | C',
  'Gấu Bắc Cực có bộ lông màu gì? | Nâu | Đen | Xám | Trắng | D',
  'Loài cây nào mọc nhanh nhất thế giới? | Lúa | Xương rồng | Tre | Thông | C',
  'Xương rồng thường sống ở đâu? | Bắc Cực | Đáy biển | Đầm lầy | Sa mạc | D',
  '9 × 7 bằng bao nhiêu? | 56 | 72 | 63 | 49 | C',
  '1000 − 1 bằng bao nhiêu? | 999 | 900 | 9999 | 990 | A',
  'Hình vuông có mấy trục đối xứng? | 1 | 2 | 8 | 4 | D',
  'Chu vi hình vuông cạnh 5 cm? | 15 cm | 10 cm | 25 cm | 20 cm | D',
  'Diện tích hình chữ nhật dài 6 cm, rộng 4 cm? | 10 cm² | 20 cm² | 12 cm² | 24 cm² | D',
  'Nửa giờ là bao nhiêu phút? | 15 | 45 | 60 | 30 | D',
  '1 kg bằng bao nhiêu gam? | 100 | 10000 | 10 | 1000 | D',
  '1 lít bằng bao nhiêu mililít? | 100 | 1000 | 10 | 500 | B',
  'Số nào là số chẵn? | 48 | 51 | 37 | 99 | A',
  'Số tiếp theo của dãy 2, 4, 8, 16, …? | 18 | 32 | 24 | 20 | B',
  'Số tiếp theo của dãy 1, 1, 2, 3, 5, 8, …? | 11 | 10 | 13 | 12 | C',
  '20% của 50 là bao nhiêu? | 20 | 25 | 5 | 10 | D',
  'Góc vuông bằng bao nhiêu độ? | 180° | 90° | 45° | 60° | B',
  'Một ngày có bao nhiêu giờ? | 12 | 48 | 24 | 20 | C',
  '11 × 11 bằng bao nhiêu? | 121 | 111 | 112 | 122 | A',
  '6 + 6 × 2 bằng bao nhiêu? | 24 | 18 | 14 | 20 | B',
  'Số La Mã "V" là số mấy? | 50 | 10 | 1 | 5 | D',
  'Số La Mã "C" là số mấy? | 1000 | 100 | 500 | 50 | B',
  'Môn thể thao nào dùng quả cầu có lông? | Bóng chuyền | Cầu lông | Bóng bàn | Quần vợt | B',
  'Cầu thủ Lionel Messi đến từ nước nào? | Brazil | Bồ Đào Nha | Argentina | Tây Ban Nha | C',
  'Cầu thủ Cristiano Ronaldo đến từ nước nào? | Brazil | Bồ Đào Nha | Tây Ban Nha | Ý | B',
  'Mỗi hiệp chính của trận bóng đá dài bao nhiêu phút? | 30 | 45 | 60 | 40 | B',
  'Biểu tượng Olympic có bao nhiêu vòng tròn? | 4 | 5 | 7 | 6 | B',
  'SEA Games là đại hội thể thao của khu vực nào? | Đông Nam Á | Châu Mỹ | Châu Phi | Châu Âu | A',
  'Môn võ nào có nguồn gốc từ Việt Nam? | Taekwondo | Judo | Vovinam | Karate | C',
  'Taekwondo có nguồn gốc từ nước nào? | Nhật Bản | Trung Quốc | Hàn Quốc | Thái Lan | C',
  'Judo có nguồn gốc từ nước nào? | Hàn Quốc | Nhật Bản | Việt Nam | Trung Quốc | B',
  'Muay Thai là môn võ của nước nào? | Thái Lan | Campuchia | Myanmar | Lào | A',
  'Nhạc cụ nào có phím đen và phím trắng? | Trống | Guitar | Sáo | Piano | D',
  'Nhạc cụ nào là nhạc cụ gõ? | Kèn trumpet | Violin | Trống | Sáo | C',
  'Đàn violin chơi bằng cách nào? | Kéo vĩ | Gõ | Bấm phím | Thổi | A',
  'Phim hoạt hình "Doraemon" đến từ nước nào? | Hàn Quốc | Nhật Bản | Trung Quốc | Mỹ | B',
  'Chuột Mickey do hãng nào tạo ra? | Disney | Warner Bros | Pixar | DreamWorks | A',
  'Siêu anh hùng nào được gọi là "Người Dơi"? | Superman | Batman | Iron Man | Spider-Man | B',
  'Tôn Ngộ Không là nhân vật trong tác phẩm nào? | Hồng Lâu Mộng | Tây Du Ký | Thủy Hử | Tam Quốc Diễn Nghĩa | B',
  '"Tam Quốc Diễn Nghĩa" kể về ba nước nào? | Tề, Sở, Yên | Tần, Sở, Hán | Ngụy, Thục, Ngô | Hán, Đường, Tống | C',
  '"www" trong địa chỉ web là viết tắt của? | Wide World Web | World Web Wide | World Wide Web | Web World Wide | C',
  'Ai là người đồng sáng lập Microsoft? | Elon Musk | Bill Gates | Mark Zuckerberg | Steve Jobs | B',
  'Ai là người sáng lập Facebook? | Jeff Bezos | Larry Page | Bill Gates | Mark Zuckerberg | D',
  'Hệ điều hành Android thuộc công ty nào? | Apple | Microsoft | Samsung | Google | D',
  'Đơn vị dung lượng nào lớn nhất? | Terabyte | Megabyte | Gigabyte | Kilobyte | A',
  '1 byte bằng bao nhiêu bit? | 10 | 8 | 16 | 2 | B',
  'Thiết bị nào dùng để gõ chữ vào máy tính? | Màn hình | Máy in | Bàn phím | Loa | C',
  'YouTube chủ yếu là nền tảng chia sẻ gì? | Email | Bản đồ | Ảnh | Video | D',
  'Bánh mì Việt Nam thường làm từ bột gì? | Bột sắn | Bột ngô | Bột gạo | Bột mì | D',
  'Nước mắm được làm chủ yếu từ gì? | Đậu nành | Tôm và đường | Cá và muối | Gạo | C',
  'Món bún chả nổi tiếng của thành phố nào? | Hà Nội | Huế | Cần Thơ | Đà Nẵng | A',
  'Món bún bò nổi tiếng gắn với địa danh nào? | Hà Nội | Cà Mau | Hải Phòng | Huế | D',
  'Cà phê được trồng nhiều nhất ở vùng nào của Việt Nam? | Tây Nguyên | Đồng bằng sông Cửu Long | Đồng bằng sông Hồng | Tây Bắc | A',
  'Loại quả nào vỏ có nhiều gai và mùi rất nồng? | Nho | Chuối | Táo | Sầu riêng | D',
  'Quả nào vỏ tím, ruột múi trắng, được gọi là "nữ hoàng trái cây"? | Nhãn | Vải | Măng cụt | Thanh long | C',
  'Quả nào vỏ đỏ, có "râu", ruột trắng? | Vải | Mận | Chôm chôm | Nhãn | C',
  'Ba màu cơ bản trong hội họa truyền thống? | Trắng, đen, xám | Cam, tím, xanh lá | Đỏ, vàng, xanh dương | Đỏ, xanh lá, xanh dương | C',
  'Pha màu trắng với màu đen được màu gì? | Hồng | Nâu | Xám | Tím | C',
  'Pha màu đỏ với màu trắng được màu gì? | Cam | Tím | Nâu | Hồng | D',
  'Pha màu đỏ với màu vàng được màu gì? | Hồng | Tím | Cam | Xanh lá | C',
  'Pha màu đỏ với màu xanh dương được màu gì? | Tím | Nâu | Cam | Xanh lá | A',
  'Lúc 3 giờ đúng, kim giờ và kim phút tạo góc bao nhiêu độ? | 45° | 90° | 180° | 60° | B',
  'Mặt Trời mọc ở hướng nào? | Nam | Tây | Bắc | Đông | D',
  'La bàn dùng để làm gì? | Đo nhiệt độ | Đo thời gian | Xác định phương hướng | Đo khoảng cách | C',
  'Đơn vị tiền tệ của Việt Nam? | Baht | Đồng | Kíp | Riel | B',
  'Đơn vị tiền tệ của Hàn Quốc? | Yên | Baht | Đô la | Won | D',
  'Đơn vị tiền tệ của Anh? | Đô la | Bảng Anh | Franc | Euro | B'
].join('\n');
