/**
 * Default content for the Vietnamese answer games. Answers are compared
 * without accents, spaces or case; "/" adds accepted alternatives.
 */

/** Đuổi hình bắt chữ — emoji | đáp án[/khác] | gợi ý */
export const EMOJI_VI_BANK = [
  '☕🥛 | cà phê sữa/cafe sữa | đồ uống quen thuộc',
  '🍜🐄 | phở bò | món ăn sáng',
  '🍚🐔 | cơm gà | món ăn',
  '🌙🎂 | bánh trung thu | loại bánh',
  '🧧🌸 | tết/tết nguyên đán | ngày lễ',
  '🌧️🌈 | cầu vồng | xuất hiện sau cơn mưa',
  '⛈️⚡ | sấm sét | thời tiết',
  '🌞🌻 | hoa hướng dương | loài hoa',
  '🐝🍯 | mật ong | đồ ăn ngọt',
  '👨‍🍳🍳 | đầu bếp | nghề nghiệp',
  '👮🚓 | cảnh sát/công an | nghề nghiệp',
  '👨‍⚕️💉 | bác sĩ | nghề nghiệp',
  '👩‍🏫📚 | giáo viên/cô giáo/thầy giáo | nghề nghiệp',
  '🚒🔥 | lính cứu hỏa | nghề nghiệp',
  '✈️👨‍✈️ | phi công | nghề nghiệp',
  '🎤🎶 | ca sĩ | nghề nghiệp',
  '⚽🥅 | bóng đá | môn thể thao',
  '🏸🏸 | cầu lông | môn thể thao',
  '🏊🌊 | bơi lội/bơi | môn thể thao',
  '🍌🐒 | con khỉ/khỉ | con vật',
  '🍵🧊 | trà đá | đồ uống vỉa hè',
  '🥖🥩 | bánh mì thịt/bánh mì | món ăn',
  '🐃🌾 | con trâu/trâu | bạn của nhà nông',
  '🏍️🛣️ | xe máy | phương tiện',
  '🚲👧 | xe đạp | phương tiện',
  '🏮🌕 | trung thu/tết trung thu | ngày lễ',
  '👗🇻🇳 | áo dài | trang phục',
  '🎍🌼 | hoa mai | hoa ngày Tết',
  '🐓🌅 | gà trống/gà gáy | con vật',
  '🌊🏖️ | bãi biển/biển | nơi đi chơi hè',
  '⛰️🥾 | leo núi | hoạt động',
  '📱📸 | chụp ảnh/chụp hình | hoạt động',
  '💤🛏️ | đi ngủ/ngủ | việc buổi tối',
  '🍦❄️ | kem/cây kem | món mát lạnh',
  '🦷🪥 | đánh răng | việc buổi sáng',
  '🧹🏠 | quét nhà | việc nhà',
  '🎂🕯️ | sinh nhật | ngày đặc biệt',
  '💍👰 | đám cưới | sự kiện',
  '🎓📜 | tốt nghiệp | sự kiện',
  '🌧️☂️ | cái ô/ô/dù/cây dù | đồ dùng',
  '🍉🔴 | dưa hấu | trái cây',
  '🥭💛 | xoài/quả xoài | trái cây',
  '🌽🔥 | ngô nướng/bắp nướng | món ăn vặt',
  '🍠🔥 | khoai lang nướng/khoai nướng | món ăn vặt',
  '🥚🦆 | trứng vịt lộn/hột vịt lộn | món ăn',
  '🐟🍲 | canh cá/lẩu cá | món ăn',
  '🦀🍜 | bún riêu/bún riêu cua | món ăn',
  '🐷🍖 | thịt lợn/thịt heo | thực phẩm'
].join('\n');

/** Câu đố vui — câu đố | đáp án[/khác] | gợi ý (tuỳ chọn) */
export const RIDDLE_VI_BANK = [
  'Con gì mang được cả cái nhà trên lưng? | ốc sên/con ốc sên/ốc/con ốc/rùa/con rùa | con vật chậm chạp',
  'Cái gì càng lấy đi càng to ra? | cái hố/hố/cái lỗ/lỗ',
  'Cái gì của bạn nhưng người khác dùng nhiều hơn bạn? | tên/cái tên/tên của bạn',
  'Cái gì có răng mà không cắn? | cái lược/lược | dùng cho tóc',
  'Cái gì có mặt mà không có mắt? | đồng hồ/cái đồng hồ | treo trên tường',
  'Cái gì càng rửa càng bẩn? | nước',
  'Con gì đập thì sống, không đập thì chết? | trái tim/tim/con tim',
  'Tháng nào có 28 ngày? | tất cả/tất cả các tháng/tháng nào cũng có/cả 12 tháng/12 tháng',
  'Cái gì đi thì nằm, đứng cũng nằm, nhưng nằm lại đứng? | bàn chân/chân',
  'Cái gì có cổ mà không có đầu? | cái áo/áo/cái chai/chai',
  'Cái gì có nhiều lỗ nhưng vẫn giữ được nước? | bọt biển/miếng bọt biển',
  'Cái gì bị phá vỡ ngay khi bạn gọi tên nó? | im lặng/sự im lặng',
  'Cái gì đi khắp thế giới mà vẫn nằm ở một góc? | con tem/tem | dán trên phong bì',
  'Cái gì càng lau càng ướt? | cái khăn/khăn/khăn tắm',
  'Con gì đầu dê mình ốc? | con dốc/dốc | chơi chữ',
  'Con gì càng to càng nhỏ? | con cua/cua | chơi chữ',
  'Con gì biết đi nhưng người ta vẫn nói nó bò? | con bò/bò',
  'Cái gì màu đen khi mua, màu đỏ khi dùng và màu xám khi vứt đi? | than/cục than/than củi',
  'Một đàn vịt: 1 con đi trước 2 con, 1 con đi sau 2 con, 1 con đi giữa. Đàn có mấy con? | 3/ba',
  'Bố mẹ có 6 con trai, mỗi con trai có 1 em gái. Nhà có mấy người? | 9/chín',
  'Gà trống đẻ quả trứng trên nóc nhà, trứng lăn về bên nào? | không bên nào/gà trống không đẻ trứng/không có trứng',
  'Có 10 con chim đậu trên cành, bắn rơi 1 con, còn mấy con trên cành? | 0/không/không còn con nào/không con nào',
  'Sở thú bị cháy, con gì chạy ra đầu tiên? | con người/người',
  'Cái gì luôn tăng lên mà không bao giờ giảm? | tuổi/tuổi tác',
  'Cái gì bạn vẫn giữ được sau khi đã trao cho người khác? | lời hứa',
  'Tay trái cầm được gì mà tay phải không cầm được? | tay phải/bàn tay phải',
  'Cái gì giúp bạn nhìn xuyên qua tường? | cửa sổ/cái cửa sổ',
  'Cái gì luôn sắp đến nhưng không bao giờ tới? | ngày mai',
  'Cái gì phải đập vỡ trước khi dùng? | quả trứng/trứng',
  'Có 3 quả táo, bạn lấy đi 2 quả. Bạn có mấy quả? | 2/hai',
  'Bạn đang thứ 2 trong cuộc đua và vượt người thứ 2. Bạn đứng thứ mấy? | 2/thứ 2/thứ hai/hai',
  'Cái gì có chân mà không biết đi? | cái bàn/bàn/cái ghế/ghế',
  'Con gì có 4 chân nhưng sáng 4 chân, trưa 2 chân, tối 3 chân? | con người/người | câu đố nhân sư',
  'Cái gì càng chia sẻ càng nhiều lên? | niềm vui/nụ cười/kiến thức/tình yêu',
  'Cái gì trắng như tuyết, mặn như biển? | muối/hạt muối'
].join('\n');

/** Đúng hay Sai (tiếng Việt) — nhận định | đúng/sai */
export const TRUE_FALSE_VI_BANK = [
  'Mặt Trời mọc ở hướng Đông. | đúng',
  'Một tuần có 8 ngày. | sai',
  'Cá voi là loài cá. | sai',
  'Nước sôi ở 100 độ C (áp suất tiêu chuẩn). | đúng',
  'Thủ đô của Việt Nam là TP. Hồ Chí Minh. | sai',
  'Con nhện có 8 chân. | đúng',
  'Trái Đất quay quanh Mặt Trời. | đúng',
  'Chim cánh cụt biết bay. | sai',
  'Hình tam giác có 4 cạnh. | sai',
  '5 × 5 = 25. | đúng',
  'Mặt Trăng tự phát ra ánh sáng. | sai',
  'Cà chua là một loại quả. | đúng',
  'Tết Trung thu vào ngày 15 tháng 8 âm lịch. | đúng',
  'Sao Hỏa được gọi là "hành tinh đỏ". | đúng',
  'Người trưởng thành có 32 chiếc răng vĩnh viễn (tính cả răng khôn). | đúng',
  'Kim cương là chất cứng nhất trong tự nhiên. | đúng',
  'Rắn là loài động vật có vú. | sai',
  'Đỉnh Everest là núi cao nhất thế giới. | đúng',
  'Nước biển có vị ngọt. | sai',
  'Dơi là loài động vật có vú. | đúng',
  'Một năm nhuận có 366 ngày. | đúng',
  'Châu Phi là châu lục lớn nhất thế giới. | sai',
  '100 − 1 = 90. | sai',
  'Cây xanh thải ra khí oxy khi quang hợp. | đúng',
  'Âm thanh truyền được trong chân không. | sai',
  'Ong mật làm ra mật ong. | đúng',
  'Vịnh Hạ Long thuộc tỉnh Quảng Ninh. | đúng',
  'Bóng đá mỗi đội có 11 người trên sân. | đúng',
  'Số 0 là số lẻ. | sai',
  'Cầu vồng có 7 màu. | đúng',
  'Tháng 2 luôn có 30 ngày. | sai',
  'Con bạch tuộc có 8 xúc tu. | đúng',
  'Nước đóng băng ở 0 độ C. | đúng',
  'Sao Thủy là hành tinh gần Mặt Trời nhất. | đúng',
  'Gấu trúc chủ yếu ăn tre. | đúng',
  'Lạc đà trữ nước trong bướu. | sai',
  'Việt Nam có hình chữ S. | đúng',
  'Người lớn có khoảng 206 chiếc xương. | đúng',
  'Tia chớp xuất hiện sau tiếng sấm. | sai',
  'Đà điểu là loài chim lớn nhất thế giới. | đúng'
].join('\n');

/** Đúng hay Sai (English, easy) — statement | true/false */
export const TRUE_FALSE_EN_BANK = [
  'A cat has four legs. 🐱 | true',
  'The sun is cold. ☀️ | false',
  'Fish can swim. 🐟 | true',
  'Bananas are blue. 🍌 | false',
  'There are seven days in a week. | true',
  'Snow is black. ❄️ | false',
  '2 + 2 = 5 | false',
  'Cows say "moo". 🐮 | true',
  'An apple is a fruit. 🍎 | true',
  'We sleep at night. 🌙 | true',
  'Dogs can fly. 🐶 | false',
  'The sky is usually blue. | true',
  'Ice is hot. 🧊 | false',
  'January is the first month of the year. | true',
  'A bike has three wheels. 🚲 | false',
  'We see with our eyes. 👀 | true',
  'We hear with our nose. 👃 | false',
  'Grass is green. 🌿 | true',
  'An elephant is smaller than a mouse. 🐘 | false',
  'Ten is bigger than five. | true',
  'Birds have feathers. 🐦 | true',
  'Milk is usually white. 🥛 | true',
  'A triangle has four sides. 🔺 | false',
  'Monday comes after Sunday. | true',
  'Spiders have six legs. 🕷️ | false',
  '"Happy" is the opposite of "sad". | true',
  'We drink bread. 🍞 | false',
  'The plural of "child" is "children". | true',
  '"Went" is the past tense of "go". | true',
  'A doctor works in a hospital. 🏥 | true',
  'Penguins live in the desert. 🐧 | false',
  'The moon comes out at night. 🌕 | true',
  '"Big" and "large" mean the same. | true',
  'A year has ten months. | false',
  'Tigers have stripes. 🐯 | true',
  'Chickens lay eggs. 🐔 | true',
  'The opposite of "hot" is "warm". | false',
  '"She is my brother." is correct. | false',
  'Water is wet. 💧 | true',
  'A clock tells the time. ⏰ | true'
].join('\n');

/** Phe nào đông hơn? — câu hỏi | lựa chọn A | lựa chọn B */
export const MAJORITY_BANK = [
  'Buổi sáng uống gì? | 🧋 Trà sữa | ☕ Cà phê',
  'Nuôi thú cưng nào? | 🐶 Chó | 🐱 Mèo',
  'Đi chơi ở đâu? | 🏖️ Biển | ⛰️ Núi',
  'Ăn sáng món gì? | 🍜 Phở | 🥖 Bánh mì',
  'Mùa nào đẹp hơn? | ☀️ Mùa hè | ❄️ Mùa đông',
  'Xem phim gì? | 😂 Hài | 👻 Kinh dị',
  'Thích dậy lúc nào? | 🌅 Dậy sớm | 🌙 Thức khuya',
  'Chọn siêu năng lực nào? | 🦸 Bay | 🫥 Tàng hình',
  'Đồ ăn vặt? | 🍟 Khoai tây chiên | 🍦 Kem',
  'Nghe nhạc gì? | 🎤 Nhạc Việt | 🎧 Nhạc ngoại',
  'Đi du lịch bằng gì? | ✈️ Máy bay | 🚆 Tàu hỏa',
  'Chọn trái cây? | 🥭 Xoài | 🍉 Dưa hấu',
  'Ở nhà hay ra ngoài cuối tuần? | 🛋️ Ở nhà | 🎡 Ra ngoài',
  'Mì ăn liền hay cơm? | 🍜 Mì | 🍚 Cơm',
  'Chơi game hay đọc truyện? | 🎮 Chơi game | 📚 Đọc truyện',
  'Trà đá hay nước mía? | 🧊 Trà đá | 🥤 Nước mía',
  'Phim hoạt hình hay phim người đóng? | 🧸 Hoạt hình | 🎬 Người đóng',
  'Ăn cay được không? | 🌶️ Càng cay càng thích | 🙅 Không ăn cay',
  'Học buổi nào? | 🌞 Buổi sáng | 🌚 Buổi tối',
  'Chọn màu? | 🔵 Xanh dương | 🔴 Đỏ',
  'Đi xe máy hay xe đạp? | 🏍️ Xe máy | 🚲 Xe đạp',
  'Mưa hay nắng? | 🌧️ Mưa | ☀️ Nắng',
  'Kẹo hay socola? | 🍬 Kẹo | 🍫 Socola',
  'Bún chả hay bún bò? | 🥢 Bún chả | 🍲 Bún bò',
  'Nhắn tin hay gọi điện? | 💬 Nhắn tin | 📞 Gọi điện',
  'Sinh tố hay nước ép? | 🥤 Sinh tố | 🧃 Nước ép',
  'Tết về quê hay đi du lịch? | 🏡 Về quê | 🧳 Đi du lịch',
  'Ngủ trưa hay không? | 😴 Có ngủ trưa | 💪 Không ngủ trưa',
  'Pizza hay gà rán? | 🍕 Pizza | 🍗 Gà rán',
  'Hát karaoke hay nhảy? | 🎤 Hát | 💃 Nhảy',
  'Đọc sách giấy hay ebook? | 📖 Sách giấy | 📱 Ebook',
  'Làm việc nhóm hay một mình? | 👥 Nhóm | 🧍 Một mình',
  'Bánh chưng hay bánh tét? | 🟩 Bánh chưng | 🟫 Bánh tét',
  'Chó to hay chó nhỏ? | 🐕 Chó to | 🐩 Chó nhỏ',
  'Học tiếng Anh qua gì? | 🎬 Phim | 🎵 Bài hát',
  'Quà sinh nhật? | 🎁 Đồ vật | 💌 Lời chúc',
  'Chọn thời tiết? | 🍂 Mát mẻ | 🔥 Nóng ấm',
  'Uống trà hay uống nước ngọt? | 🍵 Trà | 🥤 Nước ngọt',
  'Chụp ảnh hay quay video? | 📸 Ảnh | 🎥 Video',
  'Đi bộ hay chạy bộ? | 🚶 Đi bộ | 🏃 Chạy bộ'
].join('\n');

/** Ước lượng — câu hỏi | đáp án (số) | đơn vị (tuỳ chọn) */
export const ESTIMATE_BANK = [
  'Một ngày có bao nhiêu phút? | 1440 | phút',
  'Một giờ có bao nhiêu giây? | 3600 | giây',
  'Một năm thường (không nhuận) có bao nhiêu giờ? | 8760 | giờ',
  'Một ngày có bao nhiêu giây? | 86400 | giây',
  'Một tuần có bao nhiêu giờ? | 168 | giờ',
  'Đàn piano tiêu chuẩn có bao nhiêu phím? | 88 | phím',
  'Đàn piano 88 phím có bao nhiêu phím đen? | 36 | phím',
  'Người trưởng thành có khoảng bao nhiêu chiếc xương? | 206 | xương',
  'Nước sôi ở bao nhiêu độ F? | 212 | °F',
  'Nước đóng băng ở bao nhiêu độ F? | 32 | °F',
  'Bàn cờ vua có bao nhiêu ô? | 64 | ô',
  'Bộ bài tây (không tính Joker) có bao nhiêu lá? | 52 | lá',
  'Chiến thắng Điện Biên Phủ vào năm nào? | 1954',
  'Tuyên ngôn Độc lập của Việt Nam được đọc năm nào? | 1945',
  'Lý Thái Tổ dời đô về Thăng Long năm nào? | 1010',
  'Tốc độ ánh sáng khoảng bao nhiêu nghìn km mỗi giây? | 300 | nghìn km/s',
  'Đỉnh Everest cao khoảng bao nhiêu mét? | 8849 | m',
  'Đường bờ biển Việt Nam dài khoảng bao nhiêu km? | 3260 | km',
  '12 × 12 bằng bao nhiêu? | 144',
  '25% của 800 là bao nhiêu? | 200',
  '2 mũ 10 bằng bao nhiêu? | 1024',
  'Bảng chữ cái tiếng Anh có bao nhiêu chữ? | 26 | chữ',
  'Bảng chữ cái tiếng Việt có bao nhiêu chữ? | 29 | chữ',
  'Năm nhuận có bao nhiêu ngày? | 366 | ngày',
  'World Cup bóng đá đầu tiên diễn ra năm nào? | 1930',
  'Tháp Eiffel được hoàn thành năm nào? | 1889',
  'Con người lần đầu đặt chân lên Mặt Trăng năm nào? | 1969',
  'Thế vận hội hiện đại đầu tiên diễn ra năm nào? | 1896',
  'Tàu Titanic chìm năm nào? | 1912',
  'Khoảng cách trung bình từ Trái Đất đến Mặt Trăng khoảng bao nhiêu nghìn km? | 384 | nghìn km',
  'Cự ly chạy marathon dài bao nhiêu mét? | 42195 | m',
  'Một tá có bao nhiêu? | 12',
  'Con nhện có bao nhiêu chân? | 8 | chân',
  'Một thế kỷ có bao nhiêu năm? | 100 | năm',
  '99 + 199 bằng bao nhiêu? | 298',
  'Một kilômét bằng bao nhiêu centimét? | 100000 | cm',
  'Một trận bóng đá chính thức (2 hiệp) dài bao nhiêu phút? | 90 | phút',
  '1000 − 357 bằng bao nhiêu? | 643'
].join('\n');
