/** English entries (Vietnamese source text → English). See ../i18n.ts. */
export const EN_APP: Record<string, string> = {
  // ── App shell: top bar, connection, status ─────────────────────────────
  'Comment / tim / gift của viewer → game trên overlay OBS.': 'Viewer comments / likes / gifts → games on your OBS overlay.',
  'Chế độ': 'Mode',
  '🎵 Nhạc': '🎵 Music',
  'Cỡ chữ giao diện': 'Interface text size',
  'Chữ nhỏ hơn': 'Smaller text',
  'Chữ to hơn': 'Larger text',
  'Ngôn ngữ': 'Language',
  'Chưa kết nối': 'Not connected',
  'Đang kết nối…': 'Connecting…',
  'Đã kết nối': 'Connected',
  'Lỗi kết nối': 'Connection error',
  'Chọn game rồi bấm ▶ Bắt đầu, hoặc 🤖 Chạy thử để xem overlay.': 'Pick a game and press ▶ Start, or 🤖 Demo to preview the overlay.',
  '① Kết nối TikTok': '① Connect TikTok',
  '@username đang LIVE': '@username who is LIVE',
  'Ngắt kết nối': 'Disconnect',
  'Kết nối': 'Connect',
  'Đang LIVE: công cụ test đang bật, event test sẽ tác động lên game thật.': 'LIVE: test tools are on, test events affect the real game.',
  'Ẩn': 'Hide',
  'Hiện công cụ test': 'Show test tools',
  'Chưa LIVE vẫn thử được: chọn game rồi bấm 🤖 Chạy thử.': 'Not LIVE yet? You can still try: pick a game and press 🤖 Demo.',
  'Vào phòng': 'Joined',
  'Overlay đã sẵn sàng.': 'Overlay is ready.',
  '🎮 Chọn & chuyển game': '🎮 Pick & switch games',

  // ── Messages from the main process (translated in the renderer) ────────
  'Hãy nhập username TikTok.': 'Please enter a TikTok username.',
  'Cảnh báo từ TikTok: {error}': 'TikTok warning: {error}',
  'Overlay server chưa khởi động.': 'The overlay server has not started yet.',
  'Overlay server chưa chạy.': 'The overlay server is not running.',
  'Cổng {0} đang bị chương trình khác dùng (có thể là một cửa sổ app khác). App sẽ tự thử lại khi cổng trống.': 'Port {0} is used by another program (maybe another app window). The app will retry once the port is free.',
  'Không mở được overlay server: {error}': 'Could not start the overlay server: {error}',
  'Nội dung không hợp lệ.': 'Invalid content.',
  // Native dialogs (main, in the controller's language).
  'Lưu file mẫu': 'Save sample file',
  'Chọn file nhạc': 'Choose music files',
  'Thêm vào playlist': 'Add to playlist',

  // ── Auto host hint and how-to chips ────────────────────────────────────
  'Tặng {gift} · đổi game': 'Send {gift} · switch game',
  '!doigame · {count} người gõ là đổi game': '!doigame · {count} people type it to switch',
  'mỗi game {count} lượt': 'rounds per game: {count}',
  'mỗi game {count} phút': '{count} min per game',
  'viewer bầu chọn game tiếp theo, {per}': 'viewers vote for the next game, {per}',
  'ngẫu nhiên': 'random order',
  'lần lượt': 'in order',
  '{how}, dừng sau {minutes} phút (chỉnh ở panel {panel})': '{how}, stops after {minutes} min (change in the {panel} panel)',
  '{how} (chỉnh ở panel {panel})': '{how} (change in the {panel} panel)',

  // ── Game test tools, dictionary, LIVE log ──────────────────────────────
  'Đã nhập {count} từ vào từ điển {language}': 'Imported {count} words into the {language} dictionary',
  'tiếng Việt': 'Vietnamese',
  'tiếng Anh': 'English',
  'Lệnh chung & sự kiện': 'Global commands & events',
  '+20 tim': '+20 likes',
  '(đổi game)': '(switch game)',
  'vào phòng': 'join',
  'Gõ comment thử (vd: apple, 42, A)': 'Type a test comment (e.g. apple, 42, A)',
  'Gửi': 'Send',
  '📜 Nhật ký LIVE': '📜 LIVE log',
  '⚠ phòng quá đông: bỏ qua {count} comment': '⚠ room too busy: skipped {count} comments',
  'Comment, tim, gift… sẽ hiện ở đây.': 'Comments, likes, gifts… will show up here.',
  'Đã mở cửa sổ game: kéo để di chuyển, bấm vào cửa sổ để hiện nút ☰ (danh sách game) và ✕. OBS → Window Capture → “Game Overlay”': 'Game window opened: drag to move, click it to show ☰ (game list) and ✕. OBS → Window Capture → “Game Overlay”',
  'Không mở được cửa sổ game: {error}': 'Could not open the game window: {error}',
  'Đã đóng cửa sổ game': 'Game window closed',

  // ── Music tab ──────────────────────────────────────────────────────────
  'Chọn bài': 'Track picked',
  'Hết bài': 'Track ended',
  'Bài thắng đã bị xoá khỏi playlist': 'The winning track was removed from the playlist',
  '@{user} dùng {command}': '@{user} used {command}',
  '@{user} chọn #{number}': '@{user} picked #{number}',
  '@{user} tìm “{query}”': '@{user} searched “{query}”',
  'Đạt {count} likes': 'Reached {count} likes',
  'Đủ {count} {gift}': '{count} {gift} reached',
  'Đủ {seconds}s': '{seconds}s played',
  'Không phát được: {error}': 'Could not play: {error}',
  'Không có file nào được chọn': 'No file selected',
  'Đã thêm {count} file nhạc từ máy': 'Added {count} music files from this computer',
  'Đã thêm {count} file bằng native picker': 'Added {count} files with the native picker',
  'Native picker lỗi: {error}. Hãy dùng Add music.': 'Native picker failed: {error}. Use Add music instead.',
  'Chưa chọn bài': 'No track selected',
  'Chọn file nhạc để bắt đầu': 'Choose music files to start',
  'Dùng native Electron dialog': 'Use the native Electron dialog',
  'Action gần nhất:': 'Last action:',
  'Chưa có nhạc': 'No music yet',
  'Nhấn để chọn MP3 / M4A / WAV từ máy': 'Click to choose MP3 / M4A / WAV files from this computer',
  'Xóa khỏi playlist': 'Remove from playlist',
  'Rules nhạc': 'Music rules',
  'Đổi bài theo thời gian': 'Switch track on a timer',
  'Nghe đủ số giây rồi tự next': 'Play this many seconds, then skip to the next',
  'Giây': 'Seconds',
  'Ví dụ viewer gõ !next': 'E.g. a viewer types !next',
  'Comment số → chọn bài': 'Number comment → pick track',
  '1 → bài #1, 2 → bài #2…': '1 → track #1, 2 → track #2…',
  'Comment tìm tên bài': 'Comment to search a track',
  '!song chill → bài chứa chữ chill': '!song chill → a track whose name contains chill',
  'Số lượng': 'Amount',

  // ── Hooks: demo bot speeds (rendered in GamePanel), welcome alerts ─────
  'Chậm': 'Slow',
  'Vừa': 'Medium',
  'Nhanh': 'Fast',
  'Cảm ơn {name} đã follow!': 'Thanks for the follow, {name}!',
  'Chào mừng {name}!': 'Welcome, {name}!',

  // ── General settings (FeaturesPanel) ───────────────────────────────────
  'Cài đặt chung': 'General settings',
  '💬 Lệnh chat': '💬 Chat commands',
  '(đang tắt)': '(off)',
  '(đang bật)': '(on)',
  'Bật !start, !stop, !help, !rank…': 'Enable !start, !stop, !help, !rank…',
  'Lệnh riêng của game (!join, !hit…) luôn chạy khi game đang chơi': 'Game commands (!join, !hit…) always work while a game runs',
  'Mod được dùng lệnh streamer': 'Mods allowed to use host commands',
  'vd: mod_1, @mod_2': 'e.g. mod_1, @mod_2',
  'Tài khoản LIVE @{user} luôn dùng được lệnh streamer.': 'The LIVE account @{user} can always use host commands.',
  'Khi kết nối, tài khoản đang LIVE luôn dùng được lệnh streamer.': 'Once connected, the LIVE account can always use host commands.',
  'Nút test trong app cũng dùng được.': 'The app’s test buttons can too.',
  'Chống spam (giây)': 'Anti-spam (seconds)',
  'Mỗi viewer chỉ được 1 lệnh / câu trả lời trong khoảng này. 0 = tắt.': 'Each viewer gets 1 command / answer per this interval. 0 = off.',
  '🔊 Âm thanh game': '🔊 Game sounds',
  'Âm thanh khi bắt đầu, trúng đòn, trả lời đúng/sai, thắng': 'Sounds for start, hits, right/wrong answers and wins',
  'Có tiếng tích tắc 5 giây cuối. Phát trong app, OBS thu cùng âm thanh app.': 'Ticks during the last 5 seconds. Plays in the app; OBS captures it with the app audio.',
  '🏆 Điểm fan': '🏆 Fan points',
  'Cộng điểm cho mọi comment, tim, gift': 'Give points for every comment, like and gift',
  'Điểm vào chung bảng xếp hạng với game': 'Points go to the same leaderboard as the games',
  'Mỗi comment': 'Per comment',
  'Giãn cách (giây)': 'Interval (seconds)',
  'Số tim = 1 điểm': 'Likes per 1 point',
  'Mỗi gift': 'Per gift',
  '👋 Chào người mới': '👋 Welcome newcomers',
  'Hiện lời cảm ơn khi có người follow': 'Show a thank-you when someone follows',
  'Chào cả người vào phòng': 'Also greet viewers who join',
  'Phòng đông sẽ bỏ bớt, follow được ưu tiên': 'Busy rooms skip some; follows come first',
  'Tiếng chuông': 'Chime',
  'Phát trong app, OBS thu cùng âm thanh app': 'Plays in the app; OBS captures it with the app audio',

  // ── OBS panel (OverlayPanel, OverlayPreview, shared/overlay.ts labels) ─
  '④ Đưa lên OBS': '④ Put it on OBS',
  'Đang mở overlay server…': 'Starting the overlay server…',
  'Đã copy link. OBS → Browser Source → dán link, {width}×{height}': 'Link copied. OBS → Browser Source → paste the link, {width}×{height}',
  'Không copy được: {error}': 'Could not copy: {error}',
  'Khung video': 'Video frame',
  'Tuỳ chỉnh': 'Custom',
  '9:16 dọc': '9:16 portrait',
  '16:9 ngang': '16:9 landscape',
  '1:1 vuông': '1:1 square',
  'Rộng': 'Width',
  'Cao': 'Height',
  'Vị trí game trong khung': 'Game position in the frame',
  'Cỡ game': 'Game size',
  'Nhỏ': 'Small',
  'Lớn': 'Large',
  'Rất lớn': 'X-large',
  'Toàn màn': 'Full',
  'Tránh vùng TikTok che': 'Avoid areas TikTok covers',
  'Game phủ kín khung (trừ vùng TikTok che); bảng xếp hạng nằm dưới game.': 'The game fills the frame (except areas TikTok covers); the leaderboard sits below it.',
  'Game phủ kín khung; bảng xếp hạng nằm dưới game.': 'The game fills the frame; the leaderboard sits below it.',
  'Game phủ kín khung; bảng xếp hạng nằm dưới game hoặc cột bên phải.': 'The game fills the frame; the leaderboard sits below it or in a right column.',
  '🔄 Cập nhật cửa sổ game': '🔄 Update game window',
  '🪟 Mở cửa sổ game': '🪟 Open game window',
  '✕ Đóng cửa sổ game': '✕ Close game window',
  'Cửa sổ game: kéo bất kỳ đâu để di chuyển, kéo góc để đổi cỡ. Bấm vào cửa sổ để hiện nút ✕ (hoặc phím Esc); thanh này tự ẩn khi quay lại app nên không lọt vào stream.': 'Game window: drag anywhere to move, drag a corner to resize. Click the window to show the ✕ button (or press Esc); the bar hides when you return to the app, so it never shows on stream.',
  'Cửa sổ game → OBS': 'Game window → OBS',
  'Link → OBS': 'Link → OBS',
  'Tuỳ chọn hiển thị': 'Display options',
  'Phần hiện trên overlay': 'Shown on the overlay',
  'Chào người mới': 'Welcome alerts',
  'Bảng xếp hạng': 'Leaderboard',
  'Bài đang phát': 'Now playing',
  'Nền cửa sổ game': 'Game window background',
  'Xanh (chroma key)': 'Green (chroma key)',
  'Nền tối': 'Dark',
  'Trong suốt': 'Transparent',
  'Xem trước overlay': 'Overlay preview',
  'TikTok: avatar, số người xem': 'TikTok: avatar, viewer count',
  'TikTok: nút like, share, gift': 'TikTok: like, share, gift buttons',
  'TikTok: comment, ô chat': 'TikTok: comments, chat box',

  // ── Overlay page (viewers see these) ───────────────────────────────────
  'Đóng cửa sổ game': 'Close game window',
  'Đang chờ TikLiveVPN…': 'Waiting for TikLiveVPN…',
  'Kết thúc': 'Finished',
  '🏆 Bảng xếp hạng': '🏆 Leaderboard',
  'Bắt đầu!': 'Start!',
  'Chiến thắng!': 'Victory!',
  'Hết giờ!': 'Time’s up!',
  '{count} người': '{count} players',
  '❤️ Thả tim để xuất phát!': '❤️ Tap likes to start racing!',
  'Vòng quay thử thách': 'Challenge wheel',
  'Không tìm thấy #root trong overlay.html': '#root not found in overlay.html',
  // Game window: game list / back to the list
  'Về danh sách game': 'Back to game list',
  'Chơi {title}': 'Play {title}',
  'Đã mở danh sách game: bấm một game trong cửa sổ game để chơi': 'Game list opened: click a game in the game window to play it',
  'Không bắt đầu được {title}': 'Couldn\'t start {title}'
};
