/** English entries (Vietnamese source text → English). See ../i18n.ts. */
export const EN_GAMES3: Record<string, string> = {
  // Shared by several games
  'Thời gian (giây)': 'Time (seconds)',
  'Giây mỗi lượt': 'Seconds per turn',
  'Cách viết khác': 'Alternative form',
  'Thả tim': 'Likes',
  'Tặng gift': 'Send a gift',
  'Thả tim / gift': 'Likes / gifts',
  'Kiểm tra từ': 'Word check',
  'Chỉ từ có trong từ điển': 'Only words in the dictionary',
  '“{word}” đã dùng rồi!': '“{word}” was already used!',
  'Nối đúng: {word}': 'Valid link: {word}',
  'Từ đã dùng: {word}': 'Used word: {word}',

  // Boss (boss.ts)
  'Đánh boss 👾': 'Boss fight 👾',
  'Thả tim = 1 dmg, gift = nhiều dmg. Hạ boss trước khi hết giờ để streamer làm phần thưởng. Tham gia +1, hạ boss +2, đòn kết liễu +5.':
    'Like = 1 dmg, gift = big dmg. Defeat the boss before time runs out and the host does the reward. Joining +1, boss defeated +2, final blow +5.',
  'Đánh bằng comment (chống spam áp dụng)': 'Attack by comment (spam cooldown applies)',
  '1 dmg mỗi tim': '1 dmg per like',
  'Sát thương lớn': 'Big damage',
  'Máu boss': 'Boss HP',
  'Dmg mỗi gift': 'Dmg per gift',
  'Dmg mỗi !hit': 'Dmg per !hit',
  '0 = tắt lệnh !hit.': '0 = !hit command off.',
  'Phần thưởng': 'Reward',
  'Streamer hát 1 bài theo yêu cầu': 'Host sings a requested song',
  'Boss đã bị hạ! Đòn kết liễu: {name}.': 'Boss defeated! Final blow: {name}.',
  'Boss thắng, còn {hp}/{max} HP': 'Boss wins with {hp}/{max} HP left',
  'Boss đã bị hạ!': 'Boss defeated!',
  'Boss thắng 😈': 'Boss wins 😈',
  'Thả tim = 1 dmg': 'Like = 1 dmg',

  // Word Chain EN (englishWordChain.ts)
  'Comment một từ tiếng Anh bắt đầu bằng chữ cái cuối của từ trước (apple → egg → giraffe). Không lặp từ. Mỗi từ +1, hết lượt không ai nối thì kết thúc.':
    'Comment an English word starting with the last letter of the previous one (apple → egg → giraffe). No repeats. Each word +1; the game ends when nobody links in time.',
  'Từ bắt đầu bằng chữ cái cuối của từ trước': 'A word starting with the last letter of the previous word',
  'Số chữ cái tối thiểu': 'Minimum letters',
  'Từ trông hợp lệ (có nguyên âm)': 'Word looks valid (has a vowel)',
  'Chế độ từ điển nên dùng khi đã nhập file từ điển tiếng Anh.': 'Use dictionary mode after importing an English dictionary file.',
  '“{word}” không hợp lệ.': '“{word}” is not valid.',
  'Time\'s up! Chuỗi {n} từ, dừng ở “{word}”.': 'Time\'s up! Chain of {n} words, stopped at “{word}”.',
  'Chưa ai nối được “{word}”.': 'Nobody linked “{word}”.',
  'Sai chữ đầu': 'Wrong first letter',

  // Fastest finger (fastestFinger.ts)
  'Ai nhanh tay ⚡': 'Fastest finger ⚡',
  'Màn hình hiện một từ. Ai comment đúng từ đó (đúng dấu) đầu tiên thì thắng.':
    'A word appears on screen. The first to comment it exactly (with accents) wins.',
  'từ trên màn hình': 'the word on screen',
  'Gõ đúng từ đang hiện, nhanh nhất thắng': 'Type the word shown, fastest wins',
  'Điểm người thắng': 'Winner points',
  'Danh sách từ': 'Word list',
  'Mỗi dòng một từ/cụm từ. Để trống = dùng từ có sẵn. Nhập được file .txt / .csv.':
    'One word/phrase per line. Empty = built-in words. You can import a .txt / .csv file.',
  '⚡ {name} nhanh tay nhất!': '⚡ {name} was the fastest!',
  'Hết giờ, không ai gõ đúng.': 'Time\'s up, nobody typed it right.',
  'Gõ sai': 'Wrong typing',
  'Gõ đúng: {word}': 'Correct: {word}',
  'Gõ chính xác từ này nhanh nhất!': 'Type this exact word first!',
  'Thắng': 'Winner',

  // Guess the number (guessNumber.ts)
  'Đoán số 🔢': 'Guess the number 🔢',
  'Comment một số. Màn hình báo cao hơn / thấp hơn và thu hẹp khoảng. Ai đoán trúng trước được điểm.':
    'Comment a number. The screen says higher / lower and narrows the range. First to guess it scores.',
  'Đoán một số': 'Guess a number',
  'Số lớn nhất': 'Largest number',
  'Điểm khi trúng': 'Points for a hit',
  '{name} đoán {value} → cao hơn ⬆': '{name} guessed {value} → higher ⬆',
  '{name} đoán {value} → thấp hơn ⬇': '{name} guessed {value} → lower ⬇',
  '🎉 {name} đoán trúng số {n}!': '🎉 {name} guessed the number {n}!',
  'Hết giờ! Số bí mật là {n}.': 'Time\'s up! The secret number was {n}.',
  'Đoán {n}': 'Guess {n}',
  'Đoán trúng': 'Correct guess',
  'Đoán số bí mật từ 1 đến {max}': 'Guess the secret number from 1 to {max}',
  '🎯 Trúng': '🎯 Hit',
  '⬆ Cao hơn': '⬆ Higher',
  '⬇ Thấp hơn': '⬇ Lower',

  // Name It (nameIt.ts)
  'Màn hình hiện chủ đề và các ô đáp án ẩn. Viewer comment từ tiếng Anh thuộc chủ đề để lật ô (số nhiều cũng được). Mỗi ô lật được +1.':
    'The screen shows a topic and hidden answer slots. Viewers comment English words from the topic to reveal slots (plurals OK). Each slot revealed +1.',
  'Gõ một từ thuộc chủ đề': 'Type a word from the topic',
  'Chủ đề': 'Topics',
  'Mỗi dòng: Chủ đề | đáp án[/từ khác] | … (2–12 đáp án). Nhập được file .txt / .csv (Excel, Google Sheets).':
    'Each line: Topic | answer[/alternative] | … (2–12 answers). You can import a .txt / .csv file (Excel, Google Sheets).',
  'Không có chủ đề hợp lệ.': 'No valid topics.',
  '{name} tìm ra “{answer}”': '{name} found “{answer}”',
  'Tìm được {count}/{total} đáp án{party}.': 'Found {count}/{total} answers{party}.',
  'Đáp án: {answer}': 'Answer: {answer}',
  'Trả lời sai': 'Wrong answer',
  'Comment từ tiếng Anh • Đã tìm {count}/{total}': 'Comment English words • Found {count}/{total}',

  // Duck race (race.ts)
  'Đua vịt 🏁': 'Duck race 🏁',
  'Thả tim để có nhân vật và chạy tới trước, gift = tăng tốc. Về đích đầu tiên thắng; hết giờ thì ai xa nhất thắng. Top 3: +5/+3/+2.':
    'Send likes to get a racer and run forward, gifts = boost. First to the finish wins; at time-out the furthest wins. Top 3: +5/+3/+2.',
  'Vào vạch xuất phát': 'Join the starting line',
  'Chạy bằng comment (chống spam áp dụng)': 'Run by comment (spam cooldown applies)',
  'Chạy / tăng tốc': 'Run / boost',
  'Độ dài đường đua': 'Track length',
  'Bước chạy mỗi gift': 'Steps per gift',
  'Bước chạy mỗi !run': 'Steps per !run',
  '0 = tắt lệnh !run.': '0 = !run command off.',
  'Nhân vật': 'Racer',
  '{name} vào vạch xuất phát': '{name} is on the starting line',
  '🏆 {name} về đích đầu tiên!': '🏆 {name} finished first!',
  '🏆 {name} chạy xa nhất!': '🏆 {name} ran the furthest!',
  'Không ai tham gia đua.': 'Nobody joined the race.',
  '!join để vào • Tim{run} để chạy • Gift = +{n} bước': '!join to enter • Likes{run} to run • Gift = +{n} steps',

  // Rock Paper Scissors (rockPaperScissors.ts)
  'Kéo Búa Bao ✊': 'Rock Paper Scissors ✊',
  'Búa': 'Rock',
  'Bao': 'Paper',
  'Kéo': 'Scissors',
  'Mỗi hiệp comment búa, bao hoặc kéo (hoặc ✊ ✋ ✌️, 1/2/3). Hết giờ máy ra tay: thắng máy được điểm (càng nhanh càng nhiều), hòa được ít điểm.':
    'Each round comment rock, paper or scissors (or ✊ ✋ ✌️, 1/2/3). At time-out the house plays: beat it to score (faster = more), a draw scores a little.',
  'búa / bao / kéo': 'rock / paper / scissors',
  'Hoặc ✊ ✋ ✌️, 1 / 2 / 3, rock / paper / scissors': 'Or ✊ ✋ ✌️, 1 / 2 / 3, búa / bao / kéo',
  'Số hiệp mỗi lượt': 'Rounds per game',
  'Giây mỗi hiệp': 'Seconds per round',
  'Giây xem kết quả': 'Seconds to show the result',
  'Điểm thắng tối đa': 'Max win points',
  'Điểm hòa': 'Draw points',
  'Máy ra {hand}! 🏆 {wins} thắng • 🤝 {draws} hòa • {losses} thua': 'House plays {hand}! 🏆 {wins} won • 🤝 {draws} drew • {losses} lost',
  'Dừng giữa hiệp. ': 'Stopped mid-round. ',
  '🏁 Tổng kết': '🏁 Final results',
  '{rounds} hiệp • {players} người có điểm': '{rounds} rounds • {players} scored',
  'Máy ra {hand}!': 'House plays {hand}!',
  'Hiệp {n}/{total}: ✊ ✋ ✌️': 'Round {n}/{total}: ✊ ✋ ✌️',
  '🏆 {wins} thắng • 🤝 {draws} hòa': '🏆 {wins} won • 🤝 {draws} drew',
  'Comment búa / bao / kéo • {n} người đã ra tay': 'Comment rock / paper / scissors • {n} played',

  // Team battle (teamBattle.ts)
  'Comment A hoặc B để vào đội (không đổi được). Tim và gift của thành viên cộng điểm cho đội. Đội thua chịu phạt.':
    'Comment A or B to join a team (no switching). Members\' likes and gifts score for their team. The losing team takes the penalty.',
  'Vào đội A hoặc B': 'Join team A or B',
  'Vào đội đang ít người hơn': 'Join the smaller team',
  'Cộng điểm cho đội mình': 'Score for your team',
  'Tên đội A': 'Team A name',
  'Tên đội B': 'Team B name',
  'Điểm mỗi gift': 'Points per gift',
  'Hình phạt': 'Penalty',
  'Đội Đỏ': 'Red Team',
  'Đội Xanh': 'Blue Team',
  'Đội A': 'Team A',
  'Đội B': 'Team B',
  'Đội thua hát tặng đội thắng 1 câu': 'Losing team sings a line for the winners',
  '{name} vào {team}': '{name} joined {team}',
  'Hòa {a} – {b}!': 'Draw {a} – {b}!',
  '{team} thắng {a} – {b}!': '{team} wins {a} – {b}!',
  'Vào đội A': 'Join team A',
  'Comment A / B hoặc !join để vào đội • Tim +1 • Gift +{n}': 'Comment A / B or !join to join • Like +1 • Gift +{n}',

  // Challenge wheel (wheel.ts)
  'Vòng quay thử thách 🎡': 'Challenge wheel 🎡',
  'Mỗi gift (hoặc gift chỉ định) quay 1 lần; ô trúng là thử thách cho streamer. Chạy đến khi bấm Chốt. Người quay +1 điểm mỗi lượt.':
    'Each gift (or the chosen gift) spins once; the landed slot is a challenge for the host. Runs until you press End. Spinners +1 point per spin.',
  'Mỗi gift quay 1 lần': 'Each gift spins once',
  'Streamer/mod quay miễn phí 1 lần': 'Host/mod spins once for free',
  'Gift để quay': 'Gift to spin',
  'Để trống = gift nào cũng quay.': 'Empty = any gift spins.',
  'Giây mỗi lượt quay': 'Seconds per spin',
  'Các ô thử thách': 'Challenge slots',
  'Mỗi dòng một ô, 2–12 ô.': 'One slot per line, 2–12 slots.',
  'Vòng quay cần ít nhất 2 ô thử thách.': 'The wheel needs at least 2 challenge slots.',
  '🎡 {name} đang quay…': '🎡 {name} is spinning…',
  'Đã quay {n} lần.': 'Spun {n} times.',
  'Tặng {gift} để quay': 'Send {gift} to spin',
  'gift bất kỳ': 'any gift',
  'Hàng chờ: {n}': 'Queue: {n}',

  // Vietnamese word chain (wordChain.ts)
  'Nối chữ 🔤': 'Word chain (VI) 🔤',
  'Comment từ 2 âm tiết bắt đầu bằng chữ cuối của từ trước (đúng dấu). Không lặp từ. Mỗi từ nối được +1 điểm. Hết lượt không ai nối thì kết thúc.':
    'Comment a 2-syllable Vietnamese word starting with the last syllable of the previous word (with accents). No repeats. Each linked word +1 point. The game ends when nobody links in time.',
  'Từ 2 âm tiết bắt đầu bằng chữ cuối của từ trước': 'A 2-syllable word starting with the last syllable of the previous word',
  'Âm tiết tiếng Việt hợp lệ': 'Valid Vietnamese syllables',
  'Chế độ từ điển nên dùng khi đã nhập file từ điển lớn.': 'Use dictionary mode after importing a large dictionary file.',
  'Bắt đầu': 'Start',
  '“{word}” không có trong từ điển.': '“{word}” is not in the dictionary.',
  '{name} nối “{word}”': '{name} linked “{word}”',
  'Hết lượt! Chuỗi dài {n} từ, không ai nối được “{word}”.': 'Time\'s up! Chain of {n} words, nobody linked “{word}”.',
  'Không ai nối được “{word}”.': 'Nobody linked “{word}”.',
  'Nối sai chữ': 'Wrong syllable',
  'Nối từ bắt đầu bằng “{syllable}”': 'Next word starts with “{syllable}”',
  // Default wheel challenges / like milestones (translated when a round starts)
  'Hát 1 câu bài bất kỳ': 'Sing a line of any song',
  'Hít đất 10 cái': 'Do 10 push-ups',
  'Nhảy 15 giây': 'Dance for 15 seconds',
  'Kể 1 chuyện cười': 'Tell a joke',
  'Nói giọng miền khác 1 phút': 'Talk in another accent for 1 min',
  'Làm mặt xấu 5 giây': 'Pull a funny face for 5 s',
  'Đọc to tên người tặng': 'Read the gifter\'s name aloud',
  'Uống 1 ngụm nước chanh': 'Take a sip of lemon juice'
};
