/** English entries (Vietnamese source text → English). See ../i18n.ts. */
export const EN_GAMES2: Record<string, string> = {
  // Shared settings / texts used by several of these games
  'Số câu mỗi lượt': 'Questions per round',
  'Giây mỗi câu': 'Seconds per question',
  'Thời gian (giây)': 'Time (seconds)',
  'Thứ tự câu hỏi': 'Question order',
  'Ngẫu nhiên (không lặp đến khi hết)': 'Random (no repeats until all used)',
  'Đúng thứ tự trong ngân hàng / file': 'Same order as the bank / file',
  'Câu hỏi': 'Questions',
  'Chưa có câu hỏi hợp lệ.': 'No valid questions yet.',
  '🏁 Tổng kết': '🏁 Results',
  '{count} câu • {players} người có điểm': '{count} questions • {players} scored',
  'Hết giờ': "Time's up",

  // Golden Bell (goldenBell.ts)
  'Rung chuông vàng 🔔': 'Golden Bell 🔔',
  'Ai cũng vào cuộc ở câu 1: comment a / b / c / d. Từ câu 2, trả lời sai hoặc không trả lời là bị loại. Người trụ lại cuối cùng thắng lớn!':
    'Everyone plays question 1: comment a / b / c / d. From question 2 on, a wrong answer or no answer knocks you out. The last one standing wins big!',
  'Chọn đáp án — sai là bị loại': 'Pick an answer — wrong means you are out',
  'Bộ câu hỏi có sẵn': 'Built-in question set',
  'Tiếng Anh – dễ (mới bắt đầu) · {0} câu': 'English – easy (beginners) · {0} questions',
  'Tiếng Anh – ngữ pháp & từ vựng · {0} câu': 'English – grammar & vocabulary · {0} questions',
  'Kiến thức chung (tiếng Việt) · {0} câu': 'General knowledge (Vietnamese) · {0} questions',
  'Số câu tối đa': 'Max questions',
  'Thưởng người trụ lại': 'Survivor bonus',
  'Mỗi người còn trụ lại khi kết thúc được cộng thêm.': 'Added for everyone still standing at the end.',
  'Câu hỏi riêng (tuỳ chọn)': 'Your own questions (optional)',
  'Để trống = dùng bộ câu hỏi có sẵn ở trên. Mỗi dòng: Câu hỏi | A | B | C | D | Đáp án đúng. Nhập được file .txt / .csv.':
    'Leave empty = use the built-in set above. Each line: Question | A | B | C | D | Correct answer. You can import a .txt / .csv file.',
  'Bộ câu hỏi trống hoặc sai định dạng.': 'The question set is empty or badly formatted.',
  'Đáp án {letter}: {answer} • 💥 {out} người bị loại, còn {alive}': 'Answer {letter}: {answer} • 💥 {out} out, {alive} left',
  '✅ Không ai bị loại': '✅ Nobody out',
  '🔔 {names} rung chuông vàng! (+{points})': '🔔 {names} rings the Golden Bell! (+{points})',
  '🔔 {count} người trụ lại: {names} (+{points})': '🔔 {count} survivors: {names} (+{points})',
  '🔔 Không ai trụ lại đến cuối!': '🔔 Nobody made it to the end!',
  '🔔 Rung chuông vàng!': '🔔 Golden Bell!',
  'Không ai trụ lại': 'No survivors',
  'Trả lời đúng ({letter})': 'Correct answer ({letter})',
  '🔔 {count} người trụ lại': '🔔 {count} survivors',
  '🔔 Không ai trụ lại': '🔔 No survivors',
  '{count} câu • {players} người tham gia': '{count} questions • {players} players',
  'Ai cũng tham gia được': 'Everyone can play',
  '🔔 Còn {alive}/{joined} người': '🔔 {alive}/{joined} left',
  '💥 {out} bị loại': '💥 {out} out',
  'Sai là bị loại!': 'Wrong = out!',
  '{total} đã trả lời': '{total} answered',

  // True or False (trueFalse.ts)
  'Đúng hay Sai ⭕': 'True or False ⭕',
  'Tiếng Anh – dễ': 'English – easy',
  'Kiến thức (tiếng Việt)': 'General knowledge (Vietnamese)',
  'Tiếng Anh – dễ · {0} câu': 'English – easy · {0} questions',
  'Kiến thức (tiếng Việt) · {0} câu': 'General knowledge (Vietnamese) · {0} questions',
  'Màn hình hiện một câu nhận định: comment "đúng" hoặc "sai" (hoặc d/s, true/false). Chỉ tính lần đầu, đúng càng nhanh càng nhiều điểm.':
    'A statement appears on screen: comment "true" or "false" (or t/f, đúng/sai). Only your first answer counts; the faster you are right, the more points.',
  'đúng / sai': 'true / false',
  'Hoặc d / s, true / false, a / b': 'Or t / f, đúng / sai, a / b',
  'Comment đúng / sai': 'Comment true / false',
  'Mỗi dòng: câu nhận định | đúng hoặc sai (true/false).': 'Each line: statement | true or false (đúng/sai).',
  '⭕ Đúng': '⭕ True',
  '❌ Sai': '❌ False',

  // Vietnamese word games (vietnameseGames.ts) — the puzzles/answers stay Vietnamese
  'Đuổi hình bắt chữ 🖼️': 'Picture Puzzle (VN) 🖼️',
  'đáp án': 'answer',
  'Gõ thẳng đáp án tiếng Việt (có dấu hay không đều được)': 'Type the Vietnamese answer (with or without accents)',
  'Nhìn các emoji, đoán từ tiếng Việt (gõ có dấu hay không dấu đều được).': 'Look at the emojis and guess the Vietnamese word (accents optional).',
  'Câu đố hình': 'Picture puzzles',
  'Mỗi dòng: emoji | đáp án[/đáp án khác] | gợi ý.': 'Each line: emoji | answer[/other answer] | hint.',
  'Gợi ý: {hint} • {blanks}': 'Hint: {hint} • {blanks}',
  'Câu đố vui 🧠': 'Riddles (VN) 🧠',
  'Gõ thẳng đáp án (có dấu hay không đều được)': 'Type the answer (with or without accents)',
  'Câu đố mẹo dân gian: gõ đáp án (có dấu hay không dấu đều được).': 'Vietnamese folk riddles: type the answer (accents optional).',
  'Câu đố': 'Riddles',
  'Mỗi dòng: câu đố | đáp án[/đáp án khác] | gợi ý (tuỳ chọn).': 'Each line: riddle | answer[/other answer] | hint (optional).',
  'Gợi ý: {hint}': 'Hint: {hint}',
  'Đáp án {count} từ': 'Answer: {count} words',

  // Estimate (estimate.ts)
  'Ước lượng 🎯': 'Closest Guess 🎯',
  'Mỗi câu có đáp án là một con số: comment con số bạn đoán (chỉ tính lần đầu). Ba người đoán gần nhất được điểm, đoán trúng y hệt thưởng thêm.':
    'Every answer is a number: comment your guess (only your first counts). The 3 closest guesses score, and an exact hit gets a bonus.',
  'Gõ một con số (1.440 hay 1,440 đều được)': 'Type a number (1.440 or 1,440 both work)',
  'Giây xem đáp án': 'Seconds to show the answer',
  'Điểm người gần nhất': 'Points for the closest',
  'Hạng 2 được 60%, hạng 3 được 30%; đoán trúng y hệt +50%.': '2nd gets 60%, 3rd gets 30%; an exact guess +50%.',
  'Mỗi dòng: câu hỏi | đáp án (số) | đơn vị (tuỳ chọn). Nhập được file .txt / .csv.':
    'Each line: question | answer (number) | unit (optional). You can import a .txt / .csv file.',
  '🎯 Đáp án: {answer}': '🎯 Answer: {answer}',
  'gần nhất: {name} ({guess})': 'closest: {name} ({guess})',
  'Đoán gần đúng': 'Close guess',
  'Đoán trúng: {answer}': 'Exact guess: {answer}',
  'Đoán xa': 'Far-off guess',
  'lệch {diff}': 'off by {diff}',
  'Gõ một con số ({unit})': 'Type a number ({unit})',
  'Gõ một con số': 'Type a number',
  '{total} người đã đoán': '{total} guessed',

  // Defuse the Bomb (bomb.ts)
  'Gỡ bom 💣': 'Defuse the Bomb 💣',
  'Có nhiều dây, một dây là bom! Mỗi người được cắt 1 dây: comment số dây. Dây an toàn được điểm, càng về sau càng nhiều. Cắt hết dây an toàn là gỡ bom thành công — cắt trúng bom là BÙM!':
    'Lots of wires, one of them is the bomb! Each viewer cuts 1 wire: comment its number. Safe wires score, more and more as it goes. Cut every safe wire to defuse it — cut the bomb and BOOM!',
  'Cắt dây số 3 (hoặc !cut 3), mỗi người 1 lần': 'Cut wire 3 (or !cut 3), once per viewer',
  'Số dây': 'Wires',
  'Điểm dây đầu tiên': 'Points for the first wire',
  'Mỗi dây an toàn sau đó được thêm 50%.': 'Each safe wire after that gets 50% more.',
  'Thưởng gỡ bom thành công': 'Defuse bonus',
  'Chia cho mọi người đã cắt dây an toàn.': 'Shared by everyone who cut a safe wire.',
  '💥 BÙM! {name} cắt trúng dây bom số {wire}!': '💥 BOOM! {name} cut the bomb wire {wire}!',
  '💥 {name} cắt trúng bom!': '💥 {name} hit the bomb!',
  '✅ Gỡ bom thành công!': '✅ Bomb defused!',
  '✂️ {name} cắt dây {wire}: an toàn! (+{points})': '✂️ {name} cut wire {wire}: safe! (+{points})',
  '💥 BÙM! {name} cắt trúng bom (dây {wire}).': '💥 BOOM! {name} hit the bomb (wire {wire}).',
  '✅ Gỡ bom thành công! {count} người chia {points} điểm thưởng.': '✅ Bomb defused! {count} viewers share {points} bonus points.',
  '⏰ Hết giờ! Bom ở dây {wire}, may mà chưa nổ.': "⏰ Time's up! The bomb was wire {wire} — lucky it didn't blow.",
  '💥 BÙM!': '💥 BOOM!',
  'Cắt dây an toàn {wire}': 'Cut safe wire {wire}',
  'Cắt dây bom {wire}': 'Cut bomb wire {wire}',
  '✅ Đã gỡ bom!': '✅ Defused!',
  '💣 Còn {count} dây': '💣 {count} wires left',
  'Bom ở dây số {wire}': 'The bomb was wire {wire}',
  '1 dây là bom! Gõ số dây để cắt (1–{wires}) • mỗi người 1 lần': '1 wire is the bomb! Type a number to cut (1–{wires}) • once each',

  // Like Challenge (likeChallenge.ts) — milestone rewards are the streamer's own text
  'Thử thách tim ❤️': 'Like Challenge ❤️',
  'Cả phòng cùng thả tim để lấp đầy thanh ❤️ (quà cũng tính thành tim). Mỗi mốc mở khóa một thử thách cho streamer; đạt mốc cuối là thắng. Người thả nhiều tim nhất được điểm.':
    'The whole room taps likes to fill the ❤️ bar (gifts count as likes too). Each milestone unlocks a challenge for the host; reach the last one to win. Top likers score points.',
  'Thả tim ❤️': 'Tap likes ❤️',
  'Mỗi tim đẩy thanh lên': 'Every like fills the bar',
  'Tặng quà 🎁': 'Send a gift 🎁',
  'Mỗi quà = nhiều tim': 'Each gift = many likes',
  'Mỗi quà = bao nhiêu tim': 'Likes per gift',
  'Số tim = 1 điểm': 'Likes per 1 point',
  'Các mốc thử thách': 'Challenge milestones',
  'Mỗi dòng: số tim | thử thách của streamer (tối đa 12 mốc). Mốc lớn nhất là đích.':
    'Each line: likes | host challenge (up to 12 milestones). The biggest one is the goal.',
  'Chưa có mốc hợp lệ (vd: 300 | Streamer hát 1 câu).': 'No valid milestones yet (e.g. 300 | Host sings a line).',
  '🎉 Đạt {likes} tim: {reward}!': '🎉 {likes} likes: {reward}!',
  '🏆 Hoàn thành thử thách {likes} tim!': '🏆 {likes}-like challenge complete!',
  'Thả nhiều nhất: {name}': 'Top liker: {name}',
  '⏰ Hết giờ: {total}/{target} tim, mở được {reached} mốc.': "⏰ Time's up: {total}/{target} likes, {reached} milestones unlocked.",
  '❤️ Hoàn thành!': '❤️ Complete!',
  'Mốc tiếp: {likes} tim → {reward}': 'Next: {likes} likes → {reward}',
  '🏆 Đã hoàn thành mọi mốc!': '🏆 All milestones done!',
  '👑 {name} thả nhiều nhất': '👑 {name} top liker',
  '❤️ Tim cả phòng': '❤️ Room likes',

  // Majority (majority.ts)
  'Phe nào đông hơn? 🤝': 'Pick the Majority 🤝',
  'Mỗi câu có 2 lựa chọn: comment a hoặc b. Phe đông người hơn được điểm — đoán xem mọi người chọn gì! Số phiếu ẩn đến khi công bố.':
    'Each question has 2 options: comment a or b. The bigger side scores — guess what everyone picks! Votes stay hidden until the reveal.',
  'Chọn phe (hoặc 1 / 2), không đổi được': 'Pick a side (or 1 / 2), no changes',
  'Giây xem kết quả': 'Seconds to show results',
  'Điểm phe đông': 'Points for the majority',
  'Điểm khi hòa': 'Points on a tie',
  'Mỗi dòng: câu hỏi | lựa chọn A | lựa chọn B. Nhập được file .txt / .csv.': 'Each line: question | option A | option B. You can import a .txt / .csv file.',
  '🤝 Hòa {a} – {b}!': "🤝 It's a tie {a} – {b}!",
  '🏆 Phe {side} thắng {high} – {low}': '🏆 {side} wins {high} – {low}',
  '🤝 Hòa': '🤝 Tie',
  'Chọn a': 'Pick a',
  'Chọn b': 'Pick b',
  'Hòa!': 'Tie!',
  'Phe đông hơn được điểm': 'The bigger side scores',
  'Comment a / b': 'Comment a / b',
  'Đoán phe đông hơn!': 'Guess the majority!',
  '{total} người đã chọn': '{total} voted',

  // Memory (memory.ts) — createMemoryGame texts
  'Lật hình ghép cặp 🃏': 'Memory Match 🃏',
  'Các thẻ úp giấu từng cặp hình giống nhau. Comment 2 số (vd "3 8") để lật: trùng cặp thì giữ nguyên và được điểm, khác thì úp lại. Tìm hết các cặp để kết thúc!':
    'Face-down cards hide matching pairs. Comment 2 numbers (e.g. "3 8") to flip them: a match stays open and scores, otherwise they flip back. Find every pair to finish!',
  'Lật thẻ số 3 và số 8 (hoặc 3-8, !lat 3 8)': 'Flip cards 3 and 8 (or 3-8, !lat 3 8)',
  'Số cặp thẻ': 'Pairs of cards',
  'Điểm mỗi cặp': 'Points per pair',
  'Cặp thẻ riêng (tuỳ chọn)': 'Your own pairs (optional)',
  'Để trống = dùng bộ có sẵn. Mỗi dòng: mặt A | mặt B (hai mặt của một cặp). Nhập được file .txt / .csv.':
    'Leave empty = use the built-in set. Each line: face A | face B (the two faces of a pair). You can import a .txt / .csv file.',
  '{name} tìm được cặp {a} – {b}!': '{name} found the pair {a} – {b}!',
  '🎉 Tìm đủ {found} cặp!': '🎉 All {found} pairs found!',
  'Giỏi nhất: {name} ({pairs} cặp)': 'Best: {name} ({pairs} pairs)',
  '⏰ Hết giờ! Tìm được {found}/{total} cặp.': "⏰ Time's up! {found}/{total} pairs found.",
  '🃏 {pairs} cặp': '🃏 {pairs} pairs',
  'Lật đúng cặp': 'Flip a matching pair',
  'Lật sai cặp': 'Flip a wrong pair',
  '🎉 Tìm đủ các cặp!': '🎉 All pairs found!',
  '🃏 Còn {left} cặp': '🃏 {left} pairs left',
  'Comment 2 số để lật (vd 3 8) • trùng hình được điểm': 'Comment 2 numbers to flip (e.g. 3 8) • matches score',
  '{pairs} cặp': '{pairs} pairs',
  // Default wheel challenges / like milestones (translated when a round starts)
  'Streamer nói "cảm ơn" bằng 3 thứ tiếng': 'Host says "thank you" in 3 languages',
  'Streamer hát 1 câu': 'Host sings a line',
  'Streamer nhảy 15 giây': 'Host dances for 15 seconds',
  'Streamer làm mặt xấu 5 giây': 'Host pulls a funny face for 5 s',
  'Streamer đọc tên top 3 thả tim': 'Host reads out the top 3 likers'
};
