/** English entries (Vietnamese source text → English). See ../i18n.ts. */
export const EN_UI: Record<string, string> = {
  // GameLibrary
  '{n} game': '{n} games',
  '✅ Chọn 1 hoặc nhiều game để chạy': '✅ Pick one or more games to run',
  '＋ Nhóm mới': '＋ New group',
  'Tên nhóm': 'Group name',
  'Xoá nhóm': 'Delete group',
  'Viewer chỉ thấy và chọn được {n} game của nhóm này': 'Viewers only see and can pick the {n} games in this group',
  '(số trên thẻ = số viewer gõ khi bầu chọn).': '(the number on a card = what viewers type to vote).',
  'Nhóm dài có thể tràn overlay, nên để ≤ 10 game.': 'Long groups may overflow the overlay; keep it to ≤ 10 games.',
  'Nhóm “Tất cả game” luôn gồm mọi game; bấm ＋ Nhóm mới để chọn riêng.': 'The “All games” group always holds every game; click ＋ New group to pick your own.',
  '⏹ Dừng chạy tự động': '⏹ Stop auto run',
  'Chạy game đã chọn': 'Run the selected game',
  'Chạy {n} game đã chọn': 'Run {n} selected games',
  'Đang chạy': 'Running',
  'Bỏ khỏi nhóm “{name}”': 'Remove from group “{name}”',
  'Thêm vào nhóm “{name}”': 'Add to group “{name}”',

  // GamePanel
  'File quá lớn (tối đa {mb} MB).': 'File too large (max {mb} MB).',
  'Đã nhập “{name}” (cắt còn {limit} ký tự).': 'Imported “{name}” (trimmed to {limit} characters).',
  'Đã nhập “{name}”.': 'Imported “{name}”.',
  'Đã lưu file mẫu. Mở bằng Notepad/TextEdit hoặc Excel, sửa theo mẫu rồi bấm Nhập file.': 'Sample file saved. Open it in Notepad/TextEdit or Excel, edit it following the sample, then click Import file.',
  '{n} dòng': '{n} lines',
  '⬇ File mẫu': '⬇ Sample file',
  '📂 Nhập file': '📂 Import file',
  '✅ {n} dòng dùng được': '✅ {n} usable lines',
  '⚠ {n} dòng sai mẫu, sẽ bỏ qua: dòng {lines}': '⚠ {n} lines don’t match the format and will be skipped: lines {lines}',
  'Đang quay…': 'Spinning…',
  'Ô vừa trúng: {segment}': 'Landed on: {segment}',
  '● Đang chơi': '● Playing',
  'Vừa kết thúc': 'Just ended',
  'Sẵn sàng': 'Ready',
  '⏹ Chốt kết quả': '⏹ End & score',
  '✕ Huỷ': '✕ Cancel',
  'Tắt bot': 'Stop bot',
  '▶ Bắt đầu': '▶ Start',
  'Bắt đầu và cho viewer ảo tự chơi để xem overlay': 'Start and let fake viewers play so you can preview the overlay',
  '🤖 Chạy thử': '🤖 Demo',
  '⚙ Cài đặt game': '⚙ Game settings',
  'Từ điển tiếng Việt: {builtin} từ có sẵn + {imported} từ đã nhập': 'Vietnamese dictionary: {builtin} built-in words + {imported} imported',
  'Từ điển tiếng Anh: {builtin} từ có sẵn + {imported} từ đã nhập': 'English dictionary: {builtin} built-in words + {imported} imported',
  'Nhập .txt': 'Import .txt',
  'Xoá': 'Clear',
  'Khôi phục cài đặt gốc': 'Restore default settings',
  '🧪 Test không cần LIVE': '🧪 Test without going LIVE',
  'Giả lập viewer chơi game này': 'Simulate viewers playing this game',
  '🤖 Bot tự chơi': '🤖 Auto-play bot',
  'Tốc độ bot': 'Bot speed',
  'Bấm ▶ Bắt đầu (hoặc 🤖 Chạy thử) để hiện nút giả lập cho game này.': 'Click ▶ Start (or 🤖 Demo) to show the simulation buttons for this game.',
  '🏆 Bảng xếp hạng': '🏆 Leaderboard',
  'Chưa có điểm. Điểm cộng dồn qua mọi game đến khi Reset.': 'No points yet. Points add up across all games until Reset.',

  // AutoPlayPanel
  '● Đang tự động': '● Auto on',
  'Tự động: tắt': 'Auto: off',
  '🗳 Viewer đang chọn game': '🗳 Viewers are picking a game',
  'chờ phiếu đầu': 'waiting for first vote',
  '✅ Chốt ngay': '✅ Decide now',
  'LIVE còn': 'LIVE left',
  'Đã LIVE': 'LIVE for',
  '▶ Chơi ngay': '▶ Play now',
  '🔁 Đang chơi: {title}': '🔁 Playing: {title}',
  'ván {n}/{total}': 'round {n}/{total}',
  'đổi sau {time}': 'switch in {time}',
  'ván {n} · chơi mãi': 'round {n} · plays on',
  '🔄 Đã nhận lệnh đổi game: hết ván này sẽ về màn chọn game.': '🔄 Switch requested: the game list opens when this round ends.',
  '🔄 Đổi khi hết ván': '🔄 Switch after this round',
  '⏭ Đổi game ngay': '⏭ Switch game now',
  '+15 phút LIVE': '+15 min LIVE',
  '⏹ Tắt tự động': '⏹ Turn auto off',
  '▶ Bật tự động': '▶ Turn auto on',
  '📚 Nhóm game đang dùng:': '📚 Game group in use:',
  'Game đang chơi tự chạy ván mới liên tục. Khi có lệnh đổi game (quà, !doigame) thì chờ hết ván, chúc mừng người thắng rồi mở danh sách cho viewer chọn; không ai chọn hoặc hoà phiếu thì bốc ngẫu nhiên.': 'The game keeps starting new rounds forever. When a switch is asked (gift, !doigame) the current round finishes, the winners are celebrated, then viewers pick the next game from the list; no votes or a tie = random pick.',
  'Game đang chơi tự chạy ván mới liên tục. Khi có lệnh đổi game (quà, !doigame) thì chờ hết ván rồi sang game tiếp theo.': 'The game keeps starting new rounds forever. When a switch is asked (gift, !doigame) the current round finishes, then the next game starts.',
  '“Bật tự động”: tự mở game đầu tiên và dừng khi hết thời lượng LIVE.': '“Turn auto on”: starts the first game by itself and stops when the LIVE length is over.',
  'Thời lượng LIVE (phút)': 'LIVE length (minutes)',
  '0 = không giới hạn. Báo trên overlay khi còn 5 phút.': '0 = no limit. The overlay warns when 5 minutes are left.',
  'Đổi ở đây áp dụng từ lần bật sau; đang LIVE thì dùng “+15 phút”.': 'Changes here apply the next time auto starts; while LIVE, use “+15 min”.',
  'Đổi game khi': 'Switch game when',
  'Chỉ khi có lệnh đổi game (chơi mãi)': 'Only when asked (plays on forever)',
  'Chơi xong số ván': 'A number of rounds is played',
  'Chơi đủ số phút': 'A number of minutes is played',
  'Số ván mỗi game': 'Rounds per game',
  'Mỗi game (phút)': 'Per game (minutes)',
  '1 ván = 1 bộ câu hỏi (vd 10 câu) hoặc 1 trận. Quà / !doigame luôn đổi được game; đổi game luôn chờ hết ván đang chơi, không cắt ngang.': '1 round = 1 set of questions (e.g. 10) or 1 match. Gifts / !doigame can always switch the game; a switch always waits for the current round to end, never cutting it off.',
  'Nghỉ giữa ván (giây)': 'Break between rounds (seconds)',
  'Thời gian xem màn chúc mừng người thắng trước ván mới.': 'Time to show the winners’ celebration before the next round.',
  'Thứ tự': 'Order',
  'Lần lượt': 'In order',
  'Ngẫu nhiên': 'Random',
  'Tự bật khi kết nối TikTok': 'Turn on when TikTok connects',
  'Thời lượng LIVE tính từ lúc bật tự động': 'The LIVE length counts from when auto turns on',
  '🗳 Viewer chọn game': '🗳 Viewers pick the game',
  '(đang tắt)': '(off)',
  'Hiện danh sách game để viewer chọn': 'Show a game list for viewers to pick from',
  'Khi chưa có game (và mỗi lần đổi game), overlay hiện các game của nhóm đang dùng, đánh số; viewer comment số để chọn': 'When no game is on (and at every game switch), the overlay lists the current group’s games by number; viewers comment a number to pick',
  'Thời gian chọn (giây)': 'Voting time (seconds)',
  'Mỗi comment số = 1 phiếu (có chống spam). Sau mỗi lần đổi game thì đếm ngược ngay; hết giờ mà không ai chọn hoặc hoà phiếu thì báo trên overlay và bốc ngẫu nhiên. Lần đầu (chưa chơi game nào) đếm từ phiếu đầu tiên.': 'Each number comment = 1 vote (spam-protected). After a game switch the countdown starts right away; if nobody votes or votes are tied, the overlay says so and a random game is drawn. The very first list (no game played yet) counts down from the first vote.',
  'Phiếu mỗi quà': 'Votes per gift',
  'Quà bất kỳ cộng phiếu cho game người tặng đã chọn (chưa chọn thì cho game đang dẫn đầu). 0 = quà không tính.': 'Any gift adds votes to the game the sender picked (or to the leading game if they haven’t picked). 0 = gifts don’t count.',
  '!doigame cần (người)': '!doigame needs (viewers)',
  'Đủ số viewer gõ {command} thì hết ván này sẽ quay lại màn chọn game. Streamer/mod gõ là đủ. 0 = viewer không đổi được.': 'Once this many viewers type {command}, the game list returns when the current round ends. One command from the host/mods is enough. 0 = viewers can’t switch.',
  '🎁 Quà đổi game': '🎁 Gift to switch game',
  'Viewer tặng quà → hết ván đổi game (về màn chọn game)': 'Viewer sends a gift → switch game after this round (back to the pick screen)',
  'Viewer tặng quà → hết ván đổi sang game tiếp theo': 'Viewer sends a gift → next game after this round',
  'Chạy cả khi không bật tự động. Overlay hiện gợi ý tặng quà.': 'Works even when auto is off. The overlay shows a gift hint.',
  'Tên quà': 'Gift name',
  'vd: Rose': 'e.g. Rose',
  'Số lượng': 'Amount',
  'Cộng dồn quà của mọi viewer; đủ số lượng thì hết ván này sẽ đổi game.': 'Gifts from all viewers add up; once the amount is reached, the game switches when the current round ends.',
  'Giữ game tối thiểu (giây)': 'Minimum game time (seconds)',
  'Quà trong khoảng này tính từ lúc game bắt đầu không được tính, để game mới kịp chơi.': 'Gifts in this window from the start of a game don’t count, so the new game gets played.',
  // AI question generation
  'Đã lưu key và kết nối thử thành công.': 'Key saved and test connection succeeded.',
  'Đã lưu key nhưng kết nối thử lỗi:': 'Key saved, but the test connection failed:',
  'Đã xoá key.': 'Key removed.',
  'Kết nối thành công, key dùng được.': 'Connected: the key works.',
  'Đã đổi model: {model}': 'Model changed: {model}',
  '🤖 AI tạo câu hỏi': '🤖 AI question maker',
  '✅ Sẵn sàng': '✅ Ready',
  'Chưa có key': 'No key yet',
  'Dùng AI tạo câu hỏi và đáp án cho các game có bộ câu hỏi: mở ⚙ Cài đặt game → ✨ Tạo bằng AI. Bạn xem lại trước khi thêm vào.': 'Use AI to write questions and answers for games with a question bank: open ⚙ Game settings → ✨ Generate with AI. You review them before adding.',
  'Nhà cung cấp AI': 'AI provider',
  '🔐 Đã lưu key {hint}. Key được mã hoá trên máy này, app không hiển thị lại.': '🔐 Key {hint} saved. It is encrypted on this computer and never shown again.',
  'Chưa có key {provider}. Tạo key miễn phí tại {url} rồi dán vào ô dưới.': 'No {provider} key yet. Create a free key at {url} and paste it below.',
  'Dán key mới để thay': 'Paste a new key to replace it',
  'Dán API key vào đây': 'Paste your API key here',
  '💾 Lưu key': '💾 Save key',
  '🔌 Kiểm tra': '🔌 Test',
  '🗑 Xoá key': '🗑 Remove key',
  'Đang xử lý…': 'Working…',
  'Mặc định: {model}. Để trống = mặc định. Đổi model nếu nhà cung cấp ngừng hỗ trợ model cũ.': 'Default: {model}. Empty = default. Change it if the provider retires the old model.',
  'Máy này không mã hoá được key, nên key chỉ được giữ đến khi tắt app.': 'This computer can\'t encrypt keys, so the key is kept only until the app closes.',
  'Dễ': 'Easy',
  'Vừa': 'Medium',
  'Khó': 'Hard',
  'Theo mẫu của game': 'Same as the game\'s sample',
  'Tiếng Việt': 'Vietnamese',
  'Tiếng Anh': 'English',
  'AI trả về {n} dòng nhưng không dòng nào đúng mẫu của game. Thử lại hoặc đổi chủ đề.': 'The AI returned {n} lines but none match this game\'s format. Try again or change the topic.',
  'Đã thêm {n} dòng từ AI ({skipped} dòng không vừa giới hạn độ dài của ô).': 'Added {n} AI lines ({skipped} didn\'t fit the field\'s length limit).',
  'Đã thêm {n} dòng từ AI. Nhớ kiểm tra lại nội dung trước khi LIVE.': 'Added {n} AI lines. Double-check them before going LIVE.',
  '✨ Tạo bằng AI': '✨ Generate with AI',
  'Đóng': 'Close',
  'Chủ đề': 'Topic',
  'vd: động vật, lịch sử Việt Nam, từ vựng du lịch… (để trống = đa dạng)': 'e.g. animals, world history, travel vocabulary… (empty = mixed)',
  'Số dòng': 'Lines',
  'Độ khó': 'Difficulty',
  'Ngôn ngữ nội dung': 'Content language',
  '⏳ Đang tạo…': '⏳ Generating…',
  '✨ Tạo': '✨ Generate',
  '🔄 Tạo lại': '🔄 Regenerate',
  'AI thường mất 5–30 giây.': 'The AI usually takes 5–30 seconds.',
  'đã bỏ {n} dòng trùng hoặc sai mẫu': 'dropped {n} duplicate or malformed lines',
  '⚠ {n} dòng bạn sửa bị sai mẫu, sẽ không thêm': '⚠ {n} edited lines don\'t match the format and won\'t be added',
  'Kết quả AI (sửa được)': 'AI result (editable)',
  'Xem và sửa lại nếu cần: AI có thể sai kiến thức.': 'Review and fix if needed: the AI can get facts wrong.',
  '➕ Thêm vào cuối': '➕ Append',
  '🔁 Thay toàn bộ': '🔁 Replace all',
  'Chưa có API key cho nhà cung cấp đang chọn (panel 🤖 AI tạo câu hỏi).': 'No API key for the selected provider (🤖 AI question maker panel).',
  'API key sai, hết hạn hoặc không có quyền dùng model này.': 'The API key is wrong, expired, or can\'t use this model.',
  'Yêu cầu không hợp lệ (kiểm tra tên model).': 'Invalid request (check the model name).',
  'Hết lượt miễn phí / vượt giới hạn của nhà cung cấp. Đợi một lúc hoặc đổi nhà cung cấp.': 'Free quota used up / provider rate limit. Wait a bit or switch provider.',
  'Không kết nối được tới nhà cung cấp AI (kiểm tra mạng).': 'Can\'t reach the AI provider (check your network).',
  'AI trả lời quá lâu, thử lại với ít câu hơn.': 'The AI took too long; try fewer lines.',
  'AI không trả về dòng nào dùng được, thử lại hoặc đổi chủ đề.': 'The AI returned nothing usable; try again or change the topic.',
  'Nhà cung cấp AI báo lỗi.': 'The AI provider returned an error.',
  'Không lưu được cài đặt AI trên máy.': 'Couldn\'t save the AI settings on this computer.',
  'Key không đúng định dạng (dán lại, không có dấu cách).': 'The key format looks wrong (paste it again, without spaces).',
  'Tên model không hợp lệ.': 'Invalid model name.',
  'Thêm API key ở panel 🤖 AI tạo câu hỏi trước (Gemini, Groq hoặc Grok).': 'Add an API key in the 🤖 AI question maker panel first (Gemini, Groq or Grok).',
  'API key {provider}': '{provider} API key',

  // Comment history (ChatHistory.tsx)
  '💬 Lịch sử bình luận': '💬 Comment history',
  'Tìm theo tên hoặc nội dung…': 'Search by name or text…',
  'Chỉ bình luận': 'Comments only',
  'Xuất .txt': 'Export .txt',
  'Không có bình luận nào khớp.': 'No matching comments.',
  'Bình luận trong LIVE sẽ hiện ở đây theo thời gian.': 'LIVE comments will appear here over time.',
  'Đang hiện {shown}/{total} dòng mới nhất': 'Showing the newest {shown}/{total} lines',
  '{count} dòng': '{count} lines',
  '↓ {count} bình luận mới': '↓ {count} new comments',
  '🎁 tặng': '🎁 sent',
  '➕ đã follow': '➕ followed',
  'Đã lưu {count} dòng bình luận.': 'Saved {count} comment lines.',
  'Không lưu được file: {error}': 'Could not save the file: {error}',

  // Layout: sidebar tabs, start / game / test / connect popups, Euler key
  'Kết nối TikTok LIVE': 'Connect to TikTok LIVE',
  '📡 Đang kết nối TikTok…': '📡 Connecting to TikTok…',
  '📡 Chưa kết nối TikTok LIVE.': '📡 Not connected to TikTok LIVE.',
  '🔑 Kết nối TikTok': '🔑 TikTok connection',
  '🧪 Công cụ test': '🧪 Test tools',
  'Bình luận': 'Comments',
  'Nhạc': 'Music',
  'Cài đặt': 'Settings',
  '🎮 Chưa có game nào chạy': '🎮 No game running',
  '⏭ Đổi game': '⏭ Change game',
  '▶ Bắt đầu game': '▶ Start a game',
  '🧪 Test': '🧪 Test',
  'Bấm ▶ Bắt đầu game để chọn game và chơi, hoặc bật chạy tự động cả nhóm game.': 'Click ▶ Start a game to pick a game and play it, or run a whole game group automatically.',
  'Game đang chạy: chốt hoặc huỷ ván để sửa cài đặt.': 'This game is running: end or cancel the round to change its settings.',
  '⏭ Đổi sang game này': '⏭ Switch to this game',
  '▶ Chơi game này': '▶ Play this game',
  'Chọn một game': 'Pick a game',
  '⚙ Cài đặt': '⚙ Settings',
  'Cách chơi': 'How to play',
  '🎯 Chơi một game': '🎯 Play one game',
  '🔁 Tự động cả nhóm': '🔁 Auto-run the group',
  'Nhóm game': 'Game group',
  '🔍 Tìm game…': '🔍 Search games…',
  'Tìm game': 'Search games',
  'Không có game nào khớp.': 'No matching game.',
  'Bấm để chọn, bấm đúp để chơi ngay.': 'Click to pick, double-click to play right away.',
  'Game tự chơi ván này sang ván khác và đổi game theo ⚙️ Cài đặt → 🔁 Tự động. Sửa danh sách game của nhóm ở tab 📚 Game.': 'Games play round after round and switch following ⚙️ Settings → 🔁 Auto. Edit the group’s games in the 📚 Game tab.',
  'Đã lưu key. Lần kết nối sau sẽ dùng key này.': 'Key saved. The next connection will use it.',
  'Key của Euler Stream (dịch vụ ký kết nối TikTok LIVE) giúp kết nối ổn định hơn và ít bị giới hạn số lần kết nối. Không bắt buộc: không có key app vẫn thử các cách khác. Lấy key ở trang eulerstream.com.': 'A Euler Stream key (the service that signs TikTok LIVE connections) makes connecting more reliable and less rate-limited. Optional: without a key the app still tries the other ways. Get a key at eulerstream.com.',
  '🔑 Đang dùng key {hint}': '🔑 Using key {hint}',
  'từ biến môi trường SIGN_API_KEY': 'from the SIGN_API_KEY environment variable',
  'Dán key Euler Stream': 'Paste the Euler Stream key',
  'Key Euler Stream': 'Euler Stream key',
  'Lưu key': 'Save key',
  'Xoá key': 'Remove key',
  'Máy không mã hoá được key: key chỉ giữ đến khi tắt app.': 'This computer can’t encrypt the key: it is kept only until the app quits.',
  'Key không hợp lệ (16–400 ký tự, không dấu cách).': 'Invalid key (16–400 characters, no spaces).',
  'Không lưu được key.': 'Couldn’t save the key.',
  '📡 Kết nối TikTok LIVE': '📡 Connect to TikTok LIVE',
  '🔑 Key Euler Stream (tuỳ chọn)': '🔑 Euler Stream key (optional)',
  '🔁 Chạy tự động': '🔁 Auto run',
  '({n} game). Viewer chỉ thấy và chọn được các game này; đổi nhóm ở tab 📚 Game.': '({n} games). Viewers only see and can pick these games; change the group in the 📚 Game tab.',
  '🔁 Cài đặt chạy tự động': '🔁 Auto run settings',
  '📚 Thư viện game': '📚 Game library',
  'Bấm vào thẻ để xem cách chơi, cài đặt và chơi game. Bấm ✓ / ＋ ở góc thẻ để thêm / bỏ game khỏi nhóm.': 'Click a card to see how to play, its settings, and play it. Click ✓ / ＋ in a card’s corner to add / remove it from the group.',
  '🔁 Tự động': '🔁 Auto',
  '{how}, dừng sau {minutes} phút (chỉnh ở tab {panel})': '{how}, stops after {minutes} min (set in the {panel} tab)',
  '{how} (chỉnh ở tab {panel})': '{how} (set in the {panel} tab)',
  '📺 Đưa lên OBS': '📺 Put it on OBS',
  '⚙️ Cài đặt': '⚙️ Settings',
  'Trang chính': 'Home',
  '🔊 Chung': '🔊 General',
  '🚀 3 bước để LIVE': '🚀 3 steps to go LIVE',
  'Kết nối TikTok': 'Connect TikTok',
  'Đã kết nối @{name}': 'Connected to @{name}',
  'Dừng': 'Stop',
  'Bật LIVE trên TikTok trước, rồi nhập username (phần sau @).': 'Start your LIVE on TikTok first, then enter your username (the part after @).',
  'Thêm key / tuỳ chọn': 'Add key / options',
  'Đưa game lên màn hình LIVE': 'Put the game on your LIVE screen',
  'OBS / TikTok LIVE Studio: thêm Window Capture “Game Overlay”, hoặc Browser Source rồi dán link.': 'OBS / TikTok LIVE Studio: add a Window Capture of “Game Overlay”, or a Browser Source and paste the link.',
  'Chỉnh khung, vị trí': 'Frame and position',
  'Bắt đầu chơi': 'Start playing',
  '▶ Tự chơi {n} game': '▶ Auto-play {n} games',
  '🎯 Chọn 1 game': '🎯 Pick 1 game',
  'Nhóm “{group}”: {hint}': 'Group “{group}”: {hint}'
};
