/** English entries (Vietnamese source text → English): versus games. See ../i18n.ts. */
export const EN_VERSUS: Record<string, string> = {
  'Thành trì Đỏ – Xanh 🏰': 'Red vs Blue Castles 🏰',
  'Quiz Đỏ – Xanh 🆚': 'Red vs Blue Quiz 🆚',
  '{n} trận đấu': '{n} duels',
  'Đấu súng miền Tây 🤠': 'Wild West Duel 🤠',
  'Vua của đồi 👑': 'King of the Hill 👑',
  'Hai phe công thành: chọn phe Đỏ hoặc Xanh, rồi bắn thành địch bằng !ban, thả tim hoặc tặng quà; !sua để sửa thành mình. Thành nào về 0 máu trước thì thua; hết giờ phe còn nhiều máu hơn thắng.': 'Two sides besiege each other: pick Red or Blue, then shoot the enemy castle with !ban, likes or gifts; !sua repairs your own. The first castle at 0 HP loses; at the end, the side with more HP wins.',
  'Hai phe thi trả lời: chọn phe bằng !do / !xanh (hoặc trả lời luôn để vào phe ít người hơn), rồi comment a, b, c, d. Đúng càng nhanh càng nhiều điểm cho mình và cho phe. Hết lượt, phe nhiều điểm hơn thắng và mọi thành viên được thưởng.': 'Two sides race to answer: pick a side with !do / !xanh (or just answer to join the smaller one), then comment a, b, c, d. Faster right answers score more for you and your side. At the end the side with more points wins and all its members get a bonus.',
  'Gõ !join để vào hàng chờ đấu súng. Mỗi lượt 2 người đối đầu: chờ đến khi màn hình hiện "BẮN!" rồi gõ !ban thật nhanh, ai bắn trước người đó thắng. Bắn trước hiệu lệnh là thua ngay. Người thắng ở lại đấu tiếp, thắng liên tiếp được thưởng thêm.': 'Type !join to queue for a duel. Two players face off at a time: wait until the screen shows "BẮN!" (FIRE!), then type !ban fast; the first to shoot wins. Shooting before the signal loses at once. The winner stays on; win streaks earn a bonus.',
  'Cả phòng tranh một vương miện: gõ !cuop để cướp ngai. Vừa lên ngai được vài giây khiên, không ai cướp được. Giữ ngai càng lâu càng nhiều điểm. Vua tặng quà để thêm khiên; người khác tặng quà thì cướp được ngai xuyên khiên.': 'The whole room fights over one crown: type !cuop to seize the throne. A new king gets a few seconds of shield. The longer you hold it, the more points. The king\'s gifts add shield time; anyone else\'s gift takes the crown through the shield.',
  'Vào phe Đỏ hoặc Xanh (không đổi được)': 'Join Red or Blue (can\'t switch)',
  'Chọn phe Đỏ hoặc Xanh (không đổi được)': 'Pick Red or Blue (can\'t switch)',
  'Bắn thành phe địch': 'Shoot the enemy castle',
  'Sửa thành phe mình': 'Repair your castle',
  'Thả tim / tặng quà': 'Likes / gifts',
  'Tim bắn nhẹ, quà bắn cực mạnh': 'Likes hit lightly, gifts hit hard',
  'Chọn đáp án (chỉ tính lần đầu)': 'Pick an answer (first one counts)',
  'Vào hàng chờ đấu súng': 'Queue for a duel',
  'Bắn khi thấy "BẮN!" (bắn sớm là thua)': 'Shoot when you see "BẮN!" (FIRE!) — too early loses',
  'Cướp vương miện (khi vua hết khiên)': 'Seize the crown (when the king has no shield)',
  'Tặng quà': 'Send a gift',
  'Vua: thêm khiên • Người khác: cướp xuyên khiên': 'King: more shield • Others: seize through the shield',
  'Máu mỗi thành': 'HP per castle',
  'Phòng đông thì tăng lên (tim và quà trừ máu rất nhanh).': 'Raise it for busy rooms (likes and gifts drain HP fast).',
  'Sát thương mỗi !ban': 'Damage per !ban',
  'Sát thương mỗi tim': 'Damage per like',
  'Sát thương mỗi quà': 'Damage per gift',
  'Máu hồi mỗi !sua': 'HP restored per !sua',
  'Thưởng mỗi thành viên phe thắng': 'Bonus per member of the winning side',
  'Chờ hiệu lệnh ít nhất (giây)': 'Min wait for the signal (seconds)',
  'Chờ hiệu lệnh nhiều nhất (giây)': 'Max wait for the signal (seconds)',
  'Điểm mỗi trận thắng': 'Points per duel won',
  'Giây khiên sau khi lên ngai': 'Shield seconds after taking the throne',
  'Phòng đông nên để 3–5 giây để vương miện không đổi chủ liên tục.': 'For busy rooms use 3–5 seconds so the crown doesn\'t change hands nonstop.',
  'Giây khiên mỗi quà': 'Shield seconds per gift',
  'Điểm mỗi giây giữ ngai': 'Points per second on the throne',
  'Phe Đỏ': 'Red side',
  'Phe Xanh': 'Blue side',
  'Vào phe Đỏ': 'Join Red',
  'Vào phe Xanh': 'Join Blue',
  '{name} vào {team}': '{name} joined {team}',
  '{team} · {n} người': '{team} · {n} players',
  '!ban / tim bắn thành địch (-{shot} / -{like}) • Quà -{gift} • !sua +{repair}': '!ban / likes hit the enemy (-{shot} / -{like}) • Gift -{gift} • !sua +{repair}',
  '💥 Thành {team} đã sập!': '💥 {team}\'s castle fell!',
  '🏰 Hòa! Hai thành còn {hp} máu.': '🏰 Draw! Both castles have {hp} HP.',
  '🤝 Hòa!': '🤝 Draw!',
  '🏰 {team} thắng! MVP: {name} ({n} điểm công/thủ)': '🏰 {team} wins! MVP: {name} ({n} attack/defense points)',
  '🏰 {team} thắng!': '🏰 {team} wins!',
  '🏆 {team} thắng!': '🏆 {team} wins!',
  'Đáp án {letter}: {answer} • {red} +{a} · {blue} +{b}': 'Answer {letter}: {answer} • {red} +{a} · {blue} +{b}',
  '{red} +{a} · {blue} +{b}': '{red} +{a} · {blue} +{b}',
  '🆚 Hòa {a} – {b}!': '🆚 Draw {a} – {b}!',
  '🆚 {team} thắng {a} – {b}! Mỗi thành viên có điểm +{bonus}': '🆚 {team} wins {a} – {b}! Every scoring member +{bonus}',
  'Hàng chờ đã đầy ({n} người)': 'The queue is full ({n} players)',
  '{name} vào hàng chờ (#{n})': '{name} joined the queue (#{n})',
  '💥 {loser} bắn sớm! {winner} thắng': '💥 {loser} shot too early! {winner} wins',
  '🤠 {winner} hạ {loser} ({ms} ms)': '🤠 {winner} beat {loser} ({ms} ms)',
  '😴 Không ai bắn!': '😴 Nobody shot!',
  '🤠 {a} ⚔️ {b}: chuẩn bị…': '🤠 {a} ⚔️ {b}: get ready…',
  '🔥 BẮN!': '🔥 FIRE!',
  '🤠 {name} thắng nhiều nhất: {n} trận • Nhanh nhất: {fast} ({ms} ms)': '🤠 {name} won the most: {n} duels • Fastest: {fast} ({ms} ms)',
  'Chưa có trận đấu nào.': 'No duels yet.',
  '✋ Chờ hiệu lệnh… bắn sớm là THUA!': '✋ Wait for the signal… shooting early LOSES!',
  '{vs}: gõ !ban ngay!': '{vs}: type !ban now!',
  '{n} thắng · {ms} ms': '{n} wins · {ms} ms',
  '{n} thắng': '{n} wins',
  '🏆 {name} thắng!': '🏆 {name} wins!',
  '💥 {name} bắn sớm!': '💥 {name} shot too early!',
  '⚡ Phản xạ {ms} ms': '⚡ Reaction {ms} ms',
  'Không ai bắn trong {s} giây': 'Nobody shot within {s} seconds',
  '🤠 {name} chờ đối thủ': '🤠 {name} awaits a challenger',
  'Gõ !join để vào hàng chờ • {n} người đang chờ': 'Type !join to queue • {n} waiting',
  '🛡 {name} đang có khiên {s} giây': '🛡 {name} is shielded for {s} s',
  '👑 {name} cướp ngai của {old}!': '👑 {name} took the crown from {old}!',
  '👑 {name} lên ngai!': '👑 {name} takes the throne!',
  '🎁👑 {name} tặng quà cướp ngai!': '🎁👑 {name}\'s gift seizes the crown!',
  '👑 {name} giữ ngai lâu nhất: {s} giây ({n} lần đổi chủ)': '👑 {name} held the throne longest: {s} s ({n} steals)',
  'Chưa ai lên ngai.': 'Nobody took the throne.',
  '👑 {name}': '👑 {name}',
  '👑 Ngai đang trống!': '👑 The throne is empty!',
  'Gõ !cuop để lên ngai!': 'Type !cuop to take the throne!',
  '🛡 Khiên {s} giây • Giữ ngai {h} giây': '🛡 Shield {s} s • On the throne {h} s',
  'Giữ ngai {h} giây • Gõ !cuop để cướp!': 'On the throne {h} s • Type !cuop to steal!',
  '{s} giây': '{s} s'
};
