/** English entries (Vietnamese source text → English): versus games. See ../i18n.ts. */
export const EN_VERSUS: Record<string, string> = {
  'Thành trì Đỏ – Xanh 🏰': 'Red vs Blue Castles 🏰',
  'Quiz Đỏ – Xanh 🆚': 'Red vs Blue Quiz 🆚',
  '{n} trận đấu': '{n} duels',
  'Đấu súng miền Tây 🤠': 'Wild West Duel 🤠',
  'Vua của đồi 👑': 'King of the Hill 👑',
  'Hai phe công thành: chọn phe Đỏ hoặc Xanh, rồi bắn thành địch bằng !ban, thả tim hoặc tặng quà; !sua để sửa thành mình. Thành nào về 0 máu trước thì thua; hết giờ phe còn nhiều máu hơn thắng.': 'Two sides besiege each other: pick Red or Blue, then shoot the enemy castle with !ban, likes or gifts; !sua repairs your own. The first castle at 0 HP loses; at the end, the side with more HP wins.',
  'Hai phe thi trả lời: chọn phe bằng !do / !xanh (hoặc trả lời luôn để vào phe ít người hơn), rồi comment a, b, c, d. Đúng càng nhanh càng nhiều điểm cho mình và cho phe. Hết lượt, phe nhiều điểm hơn thắng và mọi thành viên được thưởng.': 'Two sides race to answer: pick a side with !do / !xanh (or just answer to join the smaller one), then comment a, b, c, d. Faster right answers score more for you and your side. At the end the side with more points wins and all its members get a bonus.',
  'Gõ !join để vào hàng chờ đấu súng. Mỗi lượt 2 người đối đầu: chờ đến khi màn hình hiện "BẮN!" rồi gõ !ban thật nhanh, ai bắn trước người đó thắng. Bắn trước hiệu lệnh là thua ngay. Người thắng ở lại đấu tiếp, thắng liên tiếp được thưởng thêm.': 'Type !join to queue for a duel. Two players face off at a time: wait until the screen shows "BẮN!" (FIRE!), then type !ban fast; the first to shoot wins. Shooting before the signal loses at once. The winner stays on; win streaks earn a bonus.',
  'Cả phòng tranh một vương miện: gõ !cuop để cướp ngai. Vừa lên ngai được vài giây khiên, không ai cướp được. Giữ ngai càng lâu càng nhiều điểm. Vua tặng quà để thêm khiên; người khác tặng quà thì cướp được ngai xuyên khiên.': 'The whole room fights over one crown: type !cuop to seize the throne. A new king gets a few seconds of shield. The longer you hold it, the more points. The king\'s gifts add shield time; anyone else\'s gift takes the crown through the shield.',
  'Vào phe Đỏ hoặc Xanh (không đổi được)': 'Join Red or Blue (can\'t switch)',
  'Chọn phe Đỏ hoặc Xanh (không đổi được)': 'Pick Red or Blue (can\'t switch)',
  'Bắn thành phe địch': 'Shoot the enemy castle',
  'Sửa thành phe mình': 'Repair your castle',
  'Thả tim / tặng quà': 'Likes / gifts',
  'Tim bắn nhẹ, quà bắn cực mạnh': 'Likes hit lightly, gifts hit hard',
  'Chọn đáp án (chỉ tính lần đầu)': 'Pick an answer (first one counts)',
  'Vào hàng chờ đấu súng': 'Queue for a duel',
  'Bắn khi thấy "BẮN!" (bắn sớm là thua)': 'Shoot when you see "BẮN!" (FIRE!) — too early loses',
  'Cướp vương miện (khi vua hết khiên)': 'Seize the crown (when the king has no shield)',
  'Tặng quà': 'Send a gift',
  'Vua: thêm khiên • Người khác: cướp xuyên khiên': 'King: more shield • Others: seize through the shield',
  'Máu mỗi thành': 'HP per castle',
  'Phòng đông thì tăng lên (tim và quà trừ máu rất nhanh).': 'Raise it for busy rooms (likes and gifts drain HP fast).',
  'Sát thương mỗi !ban': 'Damage per !ban',
  'Sát thương mỗi tim': 'Damage per like',
  'Sát thương mỗi quà': 'Damage per gift',
  'Máu hồi mỗi !sua': 'HP restored per !sua',
  'Thưởng mỗi thành viên phe thắng': 'Bonus per member of the winning side',
  'Chờ hiệu lệnh ít nhất (giây)': 'Min wait for the signal (seconds)',
  'Chờ hiệu lệnh nhiều nhất (giây)': 'Max wait for the signal (seconds)',
  'Điểm mỗi trận thắng': 'Points per duel won',
  'Giây khiên sau khi lên ngai': 'Shield seconds after taking the throne',
  'Phòng đông nên để 3–5 giây để vương miện không đổi chủ liên tục.': 'For busy rooms use 3–5 seconds so the crown doesn\'t change hands nonstop.',
  'Giây khiên mỗi quà': 'Shield seconds per gift',
  'Điểm mỗi giây giữ ngai': 'Points per second on the throne',
  'Phe Đỏ': 'Red side',
  'Phe Xanh': 'Blue side',
  'Vào phe Đỏ': 'Join Red',
  'Vào phe Xanh': 'Join Blue',
  '{name} vào {team}': '{name} joined {team}',
  '{team} · {n} người': '{team} · {n} players',
  '!ban / tim bắn thành địch (-{shot} / -{like}) • Quà -{gift} • !sua +{repair}': '!ban / likes hit the enemy (-{shot} / -{like}) • Gift -{gift} • !sua +{repair}',
  '💥 Thành {team} đã sập!': '💥 {team}\'s castle fell!',
  '🏰 Hòa! Hai thành còn {hp} máu.': '🏰 Draw! Both castles have {hp} HP.',
  '🤝 Hòa!': '🤝 Draw!',
  '🏰 {team} thắng! MVP: {name} ({n} điểm công/thủ)': '🏰 {team} wins! MVP: {name} ({n} attack/defense points)',
  '🏰 {team} thắng!': '🏰 {team} wins!',
  '🏆 {team} thắng!': '🏆 {team} wins!',
  'Đáp án {letter}: {answer} • {red} +{a} · {blue} +{b}': 'Answer {letter}: {answer} • {red} +{a} · {blue} +{b}',
  '{red} +{a} · {blue} +{b}': '{red} +{a} · {blue} +{b}',
  '🆚 Hòa {a} – {b}!': '🆚 Draw {a} – {b}!',
  '🆚 {team} thắng {a} – {b}! Mỗi thành viên có điểm +{bonus}': '🆚 {team} wins {a} – {b}! Every scoring member +{bonus}',
  'Hàng chờ đã đầy ({n} người)': 'The queue is full ({n} players)',
  '{name} vào hàng chờ (#{n})': '{name} joined the queue (#{n})',
  '💥 {loser} bắn sớm! {winner} thắng': '💥 {loser} shot too early! {winner} wins',
  '🤠 {winner} hạ {loser} ({ms} ms)': '🤠 {winner} beat {loser} ({ms} ms)',
  '😴 Không ai bắn!': '😴 Nobody shot!',
  '🤠 {a} ⚔️ {b}: chuẩn bị…': '🤠 {a} ⚔️ {b}: get ready…',
  '🔥 BẮN!': '🔥 FIRE!',
  '🤠 {name} thắng nhiều nhất: {n} trận • Nhanh nhất: {fast} ({ms} ms)': '🤠 {name} won the most: {n} duels • Fastest: {fast} ({ms} ms)',
  'Chưa có trận đấu nào.': 'No duels yet.',
  '✋ Chờ hiệu lệnh… bắn sớm là THUA!': '✋ Wait for the signal… shooting early LOSES!',
  '{vs}: gõ !ban ngay!': '{vs}: type !ban now!',
  '{n} thắng · {ms} ms': '{n} wins · {ms} ms',
  '{n} thắng': '{n} wins',
  '🏆 {name} thắng!': '🏆 {name} wins!',
  '💥 {name} bắn sớm!': '💥 {name} shot too early!',
  '⚡ Phản xạ {ms} ms': '⚡ Reaction {ms} ms',
  'Không ai bắn trong {s} giây': 'Nobody shot within {s} seconds',
  '🤠 {name} chờ đối thủ': '🤠 {name} awaits a challenger',
  'Gõ !join để vào hàng chờ • {n} người đang chờ': 'Type !join to queue • {n} waiting',
  '🛡 {name} đang có khiên {s} giây': '🛡 {name} is shielded for {s} s',
  '👑 {name} cướp ngai của {old}!': '👑 {name} took the crown from {old}!',
  '👑 {name} lên ngai!': '👑 {name} takes the throne!',
  '🎁👑 {name} tặng quà cướp ngai!': '🎁👑 {name}\'s gift seizes the crown!',
  '👑 {name} giữ ngai lâu nhất: {s} giây ({n} lần đổi chủ)': '👑 {name} held the throne longest: {s} s ({n} steals)',
  'Chưa ai lên ngai.': 'Nobody took the throne.',
  '👑 {name}': '👑 {name}',
  '👑 Ngai đang trống!': '👑 The throne is empty!',
  'Gõ !cuop để lên ngai!': 'Type !cuop to take the throne!',
  '🛡 Khiên {s} giây • Giữ ngai {h} giây': '🛡 Shield {s} s • On the throne {h} s',
  'Giữ ngai {h} giây • Gõ !cuop để cướp!': 'On the throne {h} s • Type !cuop to steal!',
  '{s} giây': '{s} s',

  // Arena games (arena.ts)
  'Đấu trường bóng 🫧': 'Bubble arena 🫧',
  'Gõ !join hoặc !thamgia trong thời gian chờ để có một quả bóng mang avatar của bạn trên sân. Mỗi câu hỏi comment a, b, c hoặc d: đúng thì bóng to lên (càng nhanh càng to) và được cộng điểm. Bóng to đẩy bóng nhỏ, ai bị đẩy ra khỏi sân thì bị loại. Sân thu hẹp dần; người cuối cùng còn trên sân thắng.':
    'Type !join or !thamgia during the waiting time to get a ball with your avatar on the field. For each question comment a, b, c or d: a correct answer grows your ball (faster = bigger) and scores points. Big balls push small ones; a ball pushed off the field is out. The field shrinks; the last ball on it wins.',
  'Đảo sinh tồn 🏝': 'Survival island 🏝',
  'Gõ !join hoặc !thamgia trong thời gian chờ để lên đảo. Mỗi người có vài tim. Mỗi câu hỏi comment a, b, c hoặc d: sai hoặc không trả lời thì mất 1 tim, hết tim thì rơi xuống biển. Cả đảo cùng sai thì không ai mất tim. Đảo thu hẹp dần; người trụ lại cuối cùng thắng.':
    'Type !join or !thamgia during the waiting time to get on the island. Everyone has a few lives. For each question comment a, b, c or d: a wrong or missing answer costs a life; at zero you fall into the sea. If the whole island misses, nobody loses a life. The island shrinks; the last survivor wins.',
  'Vào sân (trong thời gian chờ)': 'Join the field (during the waiting time)',
  'Trả lời: đúng càng nhanh bóng càng to': 'Answer: the faster you’re right, the bigger your ball',
  'Trả lời: sai hoặc không trả lời = mất 1 tim': 'Answer: wrong or no answer = −1 life',
  'Thời gian chờ người chơi (giây)': 'Waiting time for players (seconds)',
  'Viewer gõ !join hoặc !thamgia trong lúc chờ. Chưa đủ người thì tự chờ thêm.': 'Viewers type !join or !thamgia while waiting. Without enough players the wait is extended.',
  'Số người tối thiểu': 'Minimum players',
  'Số người tối đa': 'Maximum players',
  'Đủ người thì bắt đầu ngay.': 'Starts at once when full.',
  'Bóng to lên mỗi câu đúng (%)': 'Ball growth per correct answer (%)',
  'Trả lời ngay = to thêm đúng mức này, sát hết giờ = một phần ba.': 'An instant answer grows by this much, one at the deadline by a third.',
  'Số tim mỗi người': 'Lives per player',
  'Sân thu hẹp mỗi câu (%)': 'Field shrinks per question (%)',
  'Từ câu thứ 3, sân nhỏ dần để trận nào cũng kết thúc. 0 = không thu hẹp.': 'From question 3 the field closes in so every match ends. 0 = no shrinking.',
  'Tối đa số câu mỗi trận': 'Max questions per match',
  'Hết số câu mà còn nhiều người thì người mạnh nhất thắng. Câu hỏi không lặp lại giữa các trận cho đến khi dùng hết bộ.': 'If several players are left after that many questions, the strongest wins. Questions don’t repeat between matches until the bank is used up.',
  'Gõ !join hoặc !thamgia để vào sân!': 'Type !join or !thamgia to join!',
  '{n}/{max} người · cần ít nhất {min} người': '{n}/{max} players · at least {min} needed',
  '{name} vào sân ({n} người)': '{name} joined ({n} players)',
  'Đủ {n} người! Bắt đầu ngay…': '{n} players, full! Starting…',
  '👋 vào sân': '👋 joined',
  'Chờ thêm người chơi… cần ít nhất {min} người (đang có {n}). Gõ !join!': 'Waiting for more players… at least {min} needed ({n} so far). Type !join!',
  'Chưa đủ người chơi ({n}/{min}). Trận mới sẽ mở để mọi người tham gia!': 'Not enough players ({n}/{min}). A new match opens for everyone to join!',
  'Không còn ai trên sân.': 'Nobody is left on the field.',
  'còn {n} người': '{n} left',
  '💨 bị đẩy ra': '💨 pushed out',
  '🌊 rơi xuống biển': '🌊 fell into the sea',
  '✅ {correct} người đúng: bóng to lên!': '✅ {correct} correct: balls grow!',
  '✅ {correct} người đúng · 💨 {out} người bị đẩy ra!': '✅ {correct} correct · 💨 {out} pushed out!',
  '✅ {correct} người đúng': '✅ {correct} correct',
  '✅ {correct} người đúng · 🌊 {out} người rơi xuống biển!': '✅ {correct} correct · 🌊 {out} fell into the sea!',
  '🫧 {name} là quả bóng cuối cùng trên sân!': '🫧 {name} is the last ball on the field!',
  '🏝 {name} là người sống sót cuối cùng!': '🏝 {name} is the last survivor!',

  // Party arena games (partyGames.ts)
  'Ghế âm nhạc 🪑': 'Musical chairs 🪑',
  'Gõ !join hoặc !thamgia trong thời gian chờ để vào vòng. Mỗi câu hỏi có ít ghế hơn số người. Comment a, b, c hoặc d: ai đúng nhanh nhất giành ghế trước, rồi đến người trả lời sai, người im lặng xếp cuối. Ai không có ghế thì bị loại; người giành chiếc ghế cuối cùng thắng.':
    'Type !join or !thamgia during the waiting time to get in. Every question there are fewer chairs than players. Comment a, b, c or d: the fastest correct answers grab chairs first, then wrong answers, silent players last. No chair = out; whoever takes the last chair wins.',
  'Trả lời: đúng càng nhanh càng dễ giành ghế': 'Answer: the faster you’re right, the surer your chair',
  '🪑 {chairs} ghế cho {n} người': '🪑 {chairs} chairs for {n} players',
  '🪑 mất ghế': '🪑 no chair',
  '✅ {correct} người đúng · 🪑 {out} người mất ghế': '✅ {correct} correct · 🪑 {out} left without a chair',
  '🪑 {name} giành chiếc ghế cuối cùng!': '🪑 {name} took the last chair!',

  'Băng tan 🧊': 'Melting ice 🧊',
  'Gõ !join hoặc !thamgia trong thời gian chờ để đứng lên một tảng băng. Trời nắng dần, băng tan mỗi câu. Comment a, b, c hoặc d: đúng nhanh thì băng gần như không tan, sai hoặc im lặng thì tan gấp đôi. Băng tan hết thì rơi xuống nước; người còn băng cuối cùng thắng.':
    'Type !join or !thamgia during the waiting time to stand on an ice floe. The sun gets hotter and the ice melts every question. Comment a, b, c or d: a fast correct answer barely melts it, a wrong or missing one melts it twice as fast. No ice left = into the water; the last one on the ice wins.',
  'Trả lời: đúng nhanh = băng ít tan': 'Answer: fast and right = the ice barely melts',
  '☀️ {temp}°C · đúng nhanh thì băng ít tan': '☀️ {temp}°C · fast and right melts less',
  '💦 băng tan hết': '💦 ice melted',
  '✅ {correct} người đúng · 💦 {out} người rơi xuống nước!': '✅ {correct} correct · 💦 {out} fell into the water!',
  '✅ {correct} người đúng · ☀️ băng tan dần…': '✅ {correct} correct · ☀️ the ice is melting…',
  '🧊 {name} còn đứng trên tảng băng cuối cùng!': '🧊 {name} is on the last ice floe!',

  'Võ đài loại trực tiếp 🥊': 'Knockout ring 🥊',
  'Gõ !join hoặc !thamgia trong thời gian chờ để vào giải. Người chơi được chia cặp 1 đấu 1. Mỗi câu hỏi comment a, b, c hoặc d: trong mỗi cặp ai đúng nhanh hơn thì thắng và vào vòng sau; cả hai sai thì đấu lại câu sau. Thắng liên tiếp đến chung kết để vô địch.':
    'Type !join or !thamgia during the waiting time to enter the tournament. Players are paired 1 v 1. For each question comment a, b, c or d: in each pair the faster correct answer wins and goes through; if both miss, they fight again next question. Keep winning to the final to be champion.',
  'Trả lời: đúng nhanh hơn đối thủ thì thắng cặp đấu': 'Answer: right and faster than your opponent wins the bout',
  '🥊 Chung kết!': '🥊 Final!',
  '🥊 Vòng {round} · {open} cặp đang đấu': '🥊 Round {round} · {open} bouts on',
  '🥊 bị hạ': '🥊 knocked out',
  '✅ {correct} người đúng · 🥊 {out} người bị hạ': '✅ {correct} correct · 🥊 {out} knocked out',
  '🤝 Chưa phân thắng bại: đấu lại câu sau!': '🤝 No winner yet: fight again next question!',
  '🥊 {name} vô địch võ đài!': '🥊 {name} is the ring champion!',

  'Chuyền bom 💣': 'Hot potato 💣',
  'Gõ !join hoặc !thamgia trong thời gian chờ để vào vòng. Vài người được phát bom, ngòi cháy trong 1–3 câu. Mỗi câu hỏi comment a, b, c hoặc d: người cầm bom trả lời đúng thì chuyền bom cho người im lặng hoặc sai (hoặc trả lời chậm nhất). Ngòi cháy hết thì bom nổ, người đang cầm bị loại. Người sống sót cuối cùng thắng.':
    'Type !join or !thamgia during the waiting time to get in. A few players get bombs whose fuses burn for 1–3 questions. For each question comment a, b, c or d: a bomb holder who answers correctly passes it to a silent or wrong player (or the slowest). When a fuse runs out the bomb explodes and its holder is out. The last survivor wins.',
  'Trả lời: đang cầm bom thì trả lời đúng để chuyền đi': 'Answer: holding a bomb? Answer correctly to pass it on',
  '💣 {bombs} quả bom · còn {n} người': '💣 {bombs} bombs · {n} left',
  '💥 BÙM!': '💥 BOOM!',
  '✅ {correct} người đúng · 💥 {out} quả bom nổ!': '✅ {correct} correct · 💥 {out} bombs went off!',
  '✅ {correct} người đúng · 💣 bom được chuyền đi…': '✅ {correct} correct · 💣 bombs passed on…',
  '💣 {name} sống sót qua mọi quả bom!': '💣 {name} survived every bomb!',

  'Bắn bóng bay 🏹': 'Balloon shoot-out 🏹',
  'Gõ !join hoặc !thamgia trong thời gian chờ để nhận một chùm bóng bay. Mỗi câu hỏi comment a, b, c hoặc d: mỗi người đúng được bắn vỡ 1 quả bóng của đối thủ (ai đúng nhanh bắn trước; người sai hoặc im lặng bị nhắm trước, rồi đến người đúng nhưng chậm nhất). Hết bóng thì bị loại; xạ thủ cuối cùng thắng.':
    'Type !join or !thamgia during the waiting time to get a bunch of balloons. For each question comment a, b, c or d: every correct answer pops one opponent balloon (fastest shoots first; wrong or silent players are targeted first, then the slowest correct answers). No balloons left = out; the last shooter wins.',
  'Trả lời: đúng thì được bắn 1 quả bóng của đối thủ': 'Answer: right = pop one opponent balloon',
  'Số bóng bay mỗi người': 'Balloons per player',
  '🏹 còn {n} xạ thủ': '🏹 {n} shooters left',
  '🎈 hết bóng!': '🎈 out of balloons!',
  '🏹 {correct} phát bắn · {out} người hết bóng': '🏹 {correct} shots · {out} out of balloons',
  '🏹 {correct} phát bắn!': '🏹 {correct} shots!',
  '🏹 {name} là xạ thủ cuối cùng!': '🏹 {name} is the last shooter!',
};
